// Runtime shared by every C# parser generated by parsuna.
//
// A generated grammar namespace supplies token/rule-kind enums (backed by
// `ushort` / `ushort`), a DfaMatcher, a skip predicate, and a Step
// callback. This library provides everything else.

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Parsuna.Runtime;

/// <summary>Source position: byte offset plus 1-based line/column.</summary>
public readonly record struct Pos(int Offset, int Line, int Column);

/// <summary>Half-open span <c>[Start, End)</c> over the source.</summary>
public readonly record struct Span(Pos Start, Pos End)
{
    public static Span Point(Pos p) => new(p, p);
}

/// <summary>
/// A lexed token: kind id, source span, and the matched text.
/// </summary>
/// <remarks>
/// <c>Kind</c> is a <c>ushort</c> matching the generated <c>TokenKind</c>
/// enum's underlying value. EOF = 0; grammar tokens have ids starting at
/// 1; the lexer emits <see cref="Lexer.ErrorKind"/> (0xFFFF) when no DFA
/// pattern matched at the current position.
/// </remarks>
public sealed record Token(ushort Kind, Span Span, string Text);

/// <summary>A recoverable parse or lex error with its source span.</summary>
public sealed record ParseError(string Message, Span Span)
{
    public override string ToString()
    {
        var (s, e) = (Span.Start, Span.End);
        var loc = s == e ? $"{s.Line}:{s.Column}" : $"{s.Line}:{s.Column}-{e.Line}:{e.Column}";
        return $"error[{loc}]: {Message}";
    }
}

/// <summary>
/// A single pull-parser event. Pattern-match on the concrete subtype to
/// extract its payload:
/// <code>
///   switch (ev) {
///       case EnterEvent e: ...; break;
///       case ExitEvent e:  ...; break;
///       case TokenEvent t: ...; break;
///       case ErrorEvent x: ...; break;
///   }
/// </code>
/// </summary>
public abstract record Event;

/// <summary>Opens the subtree of the given rule; <c>Pos</c> is the start of the first child.</summary>
public sealed record EnterEvent(int Rule, Pos Pos) : Event;

/// <summary>Closes the subtree of the given rule; <c>Pos</c> is the end of the last child.</summary>
public sealed record ExitEvent(int Rule, Pos Pos) : Event;

/// <summary>A token consumed from the input, including skip tokens
/// and the synced-to-expected token after a recovery.</summary>
public sealed record TokenEvent(Token Token) : Event;

/// <summary>A token consumed during error recovery — emitted between
/// an <see cref="ErrorEvent"/> and the recovery's sync point. Distinct
/// from <see cref="TokenEvent"/> so consumers can drop it from their
/// AST or render it as an error span without tracking recovery state
/// externally.</summary>
public sealed record GarbageEvent(Token Token) : Event;

/// <summary>A recoverable parse or lex error.</summary>
public sealed record ErrorEvent(ParseError Error) : Event;

/// <summary>
/// Grammar-specific compiled lexer DFA. Generated code supplies this as a
/// method: a per-state switch that avoids the data-dependent table load a
/// table-driven DFA pays on every byte.
/// </summary>
/// <remarks>
/// Writes three ints to <paramref name="output"/>:
/// [0] bestLen (0 = no accept), [1] bestKind (error sentinel when no
/// accept reached), [2] scanned (== bufLen - start when the scan ran out
/// of buffer rather than hitting a dead transition; used to detect
/// buffer exhaustion mid-token).
/// </remarks>
public delegate void DfaMatcher(byte[] buf, int start, int bufLen, int[] output);

/// <summary>Byte-level lexer. Reads from a <see cref="Stream"/> in 16 KiB chunks. The grammar-specific DFA is supplied as a <see cref="DfaMatcher"/>.</summary>
public sealed class Lexer
{
    private const int Chunk = 16384;

    /// <summary>
    /// Token-kind sentinel emitted when no DFA pattern matches at the current
    /// position. Distinct from any grammar token id (0..0xFFFE), so dispatch
    /// arms naturally fall through to the recovery path.
    /// </summary>
    public const ushort ErrorKind = 0xFFFF;

    private readonly Stream _stream;
    private byte[] _buf;
    private int _bufLen;
    private int _bufPos;
    private bool _eof;
    private int _offset;
    private int _line = 1;
    private int _col = 1;
    private readonly DfaMatcher _matcher;
    private readonly int[] _matchOut = new int[3];

    public Lexer(Stream stream, DfaMatcher matcher)
    {
        _stream = stream;
        _buf = new byte[Chunk * 2];
        _matcher = matcher;
    }

    private Pos CurPos() => new(_offset, _line, _col);

    private bool ReadMore()
    {
        if (_eof) return false;
        if (_buf.Length - _bufLen < Chunk)
        {
            int newLen = _buf.Length;
            while (newLen - _bufLen < Chunk) newLen *= 2;
            Array.Resize(ref _buf, newLen);
        }
        int n = _stream.Read(_buf, _bufLen, _buf.Length - _bufLen);
        if (n <= 0) { _eof = true; return false; }
        _bufLen += n;
        return true;
    }

    private void Ensure(int want)
    {
        while (!_eof && _bufLen - _bufPos < want)
        {
            if (!ReadMore()) break;
        }
    }

    // Fast-path: bump column directly for pure ASCII non-newline slices;
    // byte-by-byte walk otherwise so multi-byte codepoints count as one column.
    private void Advance(int n)
    {
        int end = _bufPos + n;
        bool needsWalk = false;
        for (int k = _bufPos; k < end; k++)
        {
            byte b = _buf[k];
            if (b == (byte)'\n' || b >= 0x80) { needsWalk = true; break; }
        }
        if (!needsWalk)
        {
            _col += n;
            _offset += n;
            _bufPos = end;
        }
        else
        {
            while (_bufPos < end)
            {
                byte b = _buf[_bufPos++]; _offset++;
                if (b == (byte)'\n') { _line++; _col = 1; }
                else if ((b & 0xC0) != 0x80) _col++;
            }
        }
        if (_bufPos > 65536)
        {
            Array.Copy(_buf, _bufPos, _buf, 0, _bufLen - _bufPos);
            _bufLen -= _bufPos; _bufPos = 0;
        }
    }

    private (int Len, ushort Kind) LongestMatch()
    {
        while (true)
        {
            _matcher(_buf, _bufPos, _bufLen, _matchOut);
            int scanned = _matchOut[2];
            int viewLen = _bufLen - _bufPos;
            if (!_eof && scanned == viewLen)
            {
                if (ReadMore()) continue;
            }
            return (_matchOut[0], (ushort)_matchOut[1]);
        }
    }

    /// <summary>
    /// Produce the next token. Returns repeated EOF once input is fully
    /// consumed; lex failures (no DFA pattern matched) come through with
    /// <c>Token.Kind == <see cref="ErrorKind"/></c> (0xFFFF).
    /// </summary>
    public Token NextToken()
    {
        Ensure(Chunk);
        if (_bufLen - _bufPos == 0) { var p = CurPos(); return new Token(0, Span.Point(p), ""); }
        var best = LongestMatch();
        var start = CurPos();
        if (best.Len == 0)
        {
            byte b = _buf[_bufPos];
            int cpLen = b < 0x80 ? 1 : b < 0xE0 ? 2 : b < 0xF0 ? 3 : 4;
            int take = Math.Min(cpLen, _bufLen - _bufPos);
            string text = Encoding.UTF8.GetString(_buf, _bufPos, take);
            Advance(take);
            return new Token(ErrorKind, new Span(start, CurPos()), text);
        }
        string tokText = Encoding.UTF8.GetString(_buf, _bufPos, best.Len);
        Advance(best.Len);
        return new Token(best.Kind, new Span(start, CurPos()), tokText);
    }
}

/// <summary>Grammar-specific callbacks a generated parser wires into
/// the runtime.</summary>
/// <remarks>
/// <c>Step</c> runs one state body of the dispatch and returns the
/// event that body produced, or <c>null</c> if the body was a pure
/// transition step — the runtime's <c>NextEvent</c> loop calls
/// <c>Step</c> again in that case.
/// </remarks>
public sealed record ParserConfig(
    int K,
    Predicate<ushort> IsSkip,
    bool HasSkips,
    Func<Parser, Event?> Step)
{
    /// <summary>End-of-input token kind. Always 0; a constant rather than a
    /// per-grammar value so generated code and consumers don't sprinkle
    /// magic numbers.</summary>
    public const ushort EofKind = 0;
}

/// <summary>
/// Pull-based parser. Obtain one via a generated <c>ParseXxx</c> factory
/// and iterate it (or call <see cref="NextEvent"/> directly) to walk the parse.
/// </summary>
/// <remarks>
/// The parser keeps a ring of <c>K</c> lookahead slots (sized to the
/// grammar's LL(k)) and a return stack. Each call to
/// <see cref="NextEvent"/> runs in one of three modes — pump (refill
/// lookahead, possibly yielding a skip), recovery (one
/// <see cref="GarbageEvent"/> or synced <see cref="TokenEvent"/>),
/// or drive (one call to the generated <see cref="ParserConfig.Step"/>
/// callback) — and yields at most one event before looping again.
///
/// <para><b>Skip handling</b> is driven by pump-mode: when the lexer
/// hands the runtime a skip token <c>NextEvent</c> returns it as a
/// <see cref="TokenEvent"/> directly. The lookahead refills one lex
/// token at a time, so a long comment run never piles up — each skip
/// is yielded in turn before the next pump iteration runs.</para>
/// </remarks>
public sealed class Parser : IEnumerable<Event>, IEnumerator<Event>
{
    /// <summary>Sentinel state meaning "the parser has terminated".</summary>
    public const int Terminated = -1;

    /// <summary>In-flight error recovery state. Set by <see cref="RecoverTo"/>
    /// and the slow path of <see cref="TryConsume"/>; cleared once the
    /// lookahead lands on a sync token (or EOF). Each call to
    /// <see cref="NextEvent"/> drains exactly one garbage token before
    /// yielding, so a long run of unexpected input doesn't pile up in
    /// the queue.</summary>
    private struct Recovery
    {
        /// <summary>Token kinds to recover *to*. Recovery consumes garbage
        /// until the lookahead matches one of these (or EOF).</summary>
        public ushort[] Sync;
        /// <summary>Non-zero when the recovery was triggered by an
        /// <see cref="TryConsume"/> for that kind: if the sync set lands
        /// on the expected kind, the recovery finalisation also consumes
        /// the token (so the surrounding rule proceeds as if it had
        /// matched). Zero (no expected kind) for the dispatch-error
        /// path. Stored as a one-past-EOF encoding: 0 means "no
        /// expected", any other value is the literal expected kind + 1.</summary>
        public int ExpectedPlusOne;
    }

    private readonly Lexer _lex;
    // Lookahead ring. Null slots are awaiting refill — pump-mode in
    // NextEvent pulls lex tokens one-at-a-time until every slot holds a
    // structural token. Generated Step code only ever runs when all
    // slots are filled, so Look(i) can return the value unconditionally.
    //
    // Empty slots are always a contiguous suffix — Consume parks the
    // new null at index K-1 and pump fills the leftmost empty slot.
    private readonly Token?[] _look;
    private Pos _prevEnd;
    private int _state;
    private readonly Stack<int> _ret = new();

    private Event? _current;

    private Recovery _recovery;
    private bool _recoveryActive;

    private readonly ParserConfig _cfg;

    public Parser(Lexer lex, int entry, ParserConfig cfg)
    {
        _lex = lex;
        _cfg = cfg;
        _state = entry;
        _look = new Token?[cfg.K];
        _prevEnd = default;
    }

    /// <summary>Peek at the i-th lookahead token. Generated <c>Step</c>
    /// only runs after pump-mode has filled every slot.</summary>
    public Token Look(int i) => _look[i]!;

    /// <summary>Current state id. Read at the top of every step iteration.</summary>
    public int State() => _state;
    public void SetState(int s) => _state = s;
    public void PushRet(int s) => _ret.Push(s);
    public int PopRet() => _ret.Count > 0 ? _ret.Pop() : Terminated;

    /// <summary>True iff the current lookahead matches any of the given prefixes.</summary>
    public bool MatchesFirst(ushort[][] set)
    {
        foreach (var seq in set)
        {
            bool match = true;
            for (int i = 0; i < seq.Length; i++)
            {
                if (_look[i]!.Kind != seq[i]) { match = false; break; }
            }
            if (match) return true;
        }
        return false;
    }

    /// <summary>Build an Enter event for <paramref name="rule"/>.
    /// Records the rule's start position so a later Exit without any
    /// intervening tokens still produces a zero-width span at the
    /// expected place.</summary>
    public Event Enter(int rule)
    {
        var pos = _look[0]!.Span.Start;
        _prevEnd = pos;
        return new EnterEvent(rule, pos);
    }

    /// <summary>Build an Exit event for <paramref name="rule"/>,
    /// positioned at the end of the last consumed token (or the rule's
    /// start for empty rules).</summary>
    public Event Exit(int rule) => new ExitEvent(rule, _prevEnd);

    // Pop the current lookahead token and shift the buffer up by one.
    // Slot K-1 is left null so pump-mode can refill it (yielding one
    // skip per call) before the next Step reads lookahead. Internal —
    // callers wrap the result in the appropriate event subtype.
    private Token TakeToken()
    {
        var t = _look[0]!;
        _prevEnd = t.Span.End;
        for (int i = 0; i < _cfg.K - 1; i++) _look[i] = _look[i + 1];
        _look[_cfg.K - 1] = null;
        return t;
    }

    /// <summary>Consume the current lookahead token and return it as a
    /// <see cref="TokenEvent"/>. Used on TryConsume's success path and
    /// on recovery's "synced-to-expected" path — both yield legitimate
    /// parse data.</summary>
    public Event Consume() => new TokenEvent(TakeToken());

    /// <summary>Try to consume a token of <paramref name="kind"/>. On a
    /// hit returns a <see cref="TokenEvent"/>. On a miss returns an
    /// <see cref="ErrorEvent"/> and arms recovery — subsequent
    /// <see cref="NextEvent"/> calls skip <see cref="GarbageEvent"/>s
    /// one at a time until the lookahead lands on <paramref name="sync"/>
    /// (when it does, the matching token comes through as a normal
    /// <see cref="TokenEvent"/>).</summary>
    public Event TryConsume(ushort kind, ushort[] sync, string name)
    {
        if (_look[0]!.Kind == kind) return Consume();
        var ev = ErrorHere($"expected {name}");
        _recovery = new Recovery { Sync = sync, ExpectedPlusOne = kind + 1 };
        _recoveryActive = true;
        return ev;
    }

    private static bool ContainsKind(ushort[] set, ushort k)
    {
        foreach (var x in set) if (x == k) return true;
        return false;
    }

    /// <summary>Arm recovery without an expected kind. Called from a
    /// dispatch error leaf: the surrounding <c>cur</c> is already
    /// pointing at the post-recovery state, and the returned
    /// <see cref="ErrorEvent"/> makes Step yield so recovery-mode can
    /// take over.</summary>
    public void RecoverTo(ushort[] sync)
    {
        _recovery = new Recovery { Sync = sync, ExpectedPlusOne = 0 };
        _recoveryActive = true;
    }

    /// <summary>Build a recoverable error event at the current
    /// lookahead.</summary>
    public Event ErrorHere(string msg) =>
        new ErrorEvent(new ParseError(msg, _look[0]!.Span));

    // True iff some lookahead slot still needs to be filled. Empty
    // slots are always a contiguous suffix, so checking slot K-1 is
    // the O(1) form of "any slot is null".
    private bool PumpPending() => _look[_cfg.K - 1] is null;

    /// <summary>
    /// Produce the next event from the parse, or <c>null</c> once the
    /// entire input has been consumed.
    /// </summary>
    /// <remarks>
    /// The loop runs three modes — pump (refill lookahead, possibly
    /// yielding a skip), recovery (one Garbage / synced-Token event
    /// per call), and drive (one Step call). Each mode yields at most
    /// one event before the loop runs again.
    /// </remarks>
    public Event? NextEvent()
    {
        while (true)
        {
            if (PumpPending())
            {
                var t = _lex.NextToken();
                if (_cfg.HasSkips && _cfg.IsSkip(t.Kind))
                {
                    return new TokenEvent(t);
                }
                for (int i = 0; i < _look.Length; i++)
                {
                    if (_look[i] is null) { _look[i] = t; break; }
                }
                continue;
            }
            if (_recoveryActive)
            {
                ushort look0 = _look[0]!.Kind;
                bool synced = look0 == ParserConfig.EofKind
                    || ContainsKind(_recovery.Sync, look0);
                if (synced)
                {
                    bool wasExpected = _recovery.ExpectedPlusOne != 0
                        && (ushort)(_recovery.ExpectedPlusOne - 1) == look0;
                    _recoveryActive = false;
                    if (wasExpected) return Consume();
                    continue;
                }
                return new GarbageEvent(TakeToken());
            }
            if (_state == Terminated)
            {
                // EOF gate. On the first visit with trailing input,
                // raise an error and arm a sync-empty recovery so the
                // rest of the input drains as Garbage events one per
                // call. Once recovery has eaten its way to EOF the
                // lookahead pins at EOF (the lexer keeps yielding it),
                // so this is naturally idempotent — subsequent visits
                // just return null.
                if (_look[0]!.Kind == ParserConfig.EofKind) return null;
                var ev = ErrorHere("expected end of input");
                _recovery = new Recovery { Sync = Array.Empty<ushort>(), ExpectedPlusOne = 0 };
                _recoveryActive = true;
                return ev;
            }
            var stepEv = _cfg.Step(this);
            if (stepEv is not null) return stepEv;
        }
    }

    public Event Current => _current!;
    object IEnumerator.Current => Current;
    public bool MoveNext() { var ev = NextEvent(); _current = ev; return ev is not null; }
    public void Reset() => throw new NotSupportedException("Parser is single-pass.");
    public void Dispose() { }

    public IEnumerator<Event> GetEnumerator() => this;
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
