// SPDX-License-Identifier: LGPL-3.0-or-later
//
// Package parsunart is the runtime shared by every Go parser generated by
// parsuna.
//
// A generated grammar package supplies its own TokenKind / RuleKind types
// (as int16 / uint16 aliases), a DfaConfig, a skip-kind predicate, and a
// Drive callback that runs the state machine. Everything else — lexing,
// lookahead, skip routing, event queueing, error recovery — lives here.
package parsunart

import (
	"fmt"
	"io"
	"unicode/utf8"
)

// Pos is a source position: byte offset plus 1-based line/column.
type Pos struct {
	Offset uint32
	Line   uint32
	Column uint32
}

// Span is a half-open range [Start, End) over the source.
type Span struct {
	Start, End Pos
}

// PointSpan is a zero-width span at a single point.
func PointSpan(p Pos) Span { return Span{Start: p, End: p} }

// Token is a lexed token: kind, source span, and the matched text.
//
// Kind is the matched token kind; KindOK is false only when the lexer
// could not match any pattern at the current position. EOF is its own
// kind value (KindOK is true). Read Kind only when KindOK is true.
type Token struct {
	Kind   uint16
	KindOK bool
	Span   Span
	Text   string
}

// ParseError is a recoverable parse or lex error with its source span.
type ParseError struct {
	Message string
	Span    Span
}

// String formats the error as `error[line:col]: message`.
func (d ParseError) String() string {
	s, e := d.Span.Start, d.Span.End
	if s == e {
		return fmt.Sprintf("error[%d:%d]: %s", s.Line, s.Column, d.Message)
	}
	return fmt.Sprintf("error[%d:%d-%d:%d]: %s", s.Line, s.Column, e.Line, e.Column, d.Message)
}

// EventTag discriminates Event payload fields.
type EventTag uint8

const (
	EvEnter EventTag = iota
	EvExit
	EvToken
	EvError
)

// Event is a single pull-parser event. Tag is one of the EV_* constants;
// the matching payload field (Rule, Token, Err) carries the data.
type Event struct {
	Tag   EventTag
	Rule  uint16
	Pos   Pos
	Token Token
	Err   ParseError
}

// Terminated is the sentinel state that means "parser finished".
const Terminated = -1

// MatcherFunc is the grammar-specific compiled DFA the runtime drives.
// It scans buf[start:] for the longest matching token. Returns
// (bestLen, bestKind, scanned):
//   - bestLen: bytes consumed by the longest match. 0 means no accept
//     state was reached, in which case bestKind is meaningless.
//   - bestKind: token kind of the longest match (only valid when
//     bestLen > 0).
//   - scanned: total bytes walked past start; equals len(buf)-start when
//     the scan stopped at end of input rather than a dead transition. The
//     streaming lexer uses this to detect buffer exhaustion mid-token.
type MatcherFunc func(buf []byte, start int) (int, uint16, int)

const lexChunk = 16384

// Lexer is a streaming DFA-driven lexer over an io.Reader. The grammar-
// specific DFA is supplied as a MatcherFunc.
type Lexer struct {
	reader    io.Reader
	buf       []byte
	bufPos    int
	eof       bool
	offset    uint32
	line, col uint32
	matcher   MatcherFunc
	eofKind   uint16
}

// NewLexer builds a lexer over r. eofKind is the kind value returned at
// end-of-input; lex failures (no DFA pattern matched) come through as a
// Token with KindOK == false.
func NewLexer(r io.Reader, matcher MatcherFunc, eofKind uint16) *Lexer {
	return &Lexer{reader: r, line: 1, col: 1, matcher: matcher, eofKind: eofKind}
}

func (l *Lexer) pos() Pos { return Pos{Offset: l.offset, Line: l.line, Column: l.col} }

func (l *Lexer) readMore() bool {
	if l.eof {
		return false
	}
	if cap(l.buf)-len(l.buf) < lexChunk {
		newCap := cap(l.buf) * 2
		if newCap < len(l.buf)+lexChunk {
			newCap = len(l.buf) + lexChunk*2
		}
		nb := make([]byte, len(l.buf), newCap)
		copy(nb, l.buf)
		l.buf = nb
	}
	n, err := l.reader.Read(l.buf[len(l.buf) : len(l.buf)+lexChunk])
	if n > 0 {
		l.buf = l.buf[:len(l.buf)+n]
	}
	if err != nil || n == 0 {
		l.eof = true
		return n > 0
	}
	return true
}

func (l *Lexer) ensure(want int) {
	for !l.eof && len(l.buf)-l.bufPos < want {
		if !l.readMore() {
			break
		}
	}
}

// advance bumps position. Fast-path for pure ASCII non-newline slices,
// byte-by-byte walk otherwise so lines/columns track multi-byte UTF-8.
func (l *Lexer) advance(n int) {
	end := l.bufPos + n

	needsWalk := false
	for i := l.bufPos; i < end; i++ {
		b := l.buf[i]
		if b == '\n' || b >= 0x80 {
			needsWalk = true
			break
		}
	}
	if !needsWalk {
		l.col += uint32(n)
		l.offset += uint32(n)
		l.bufPos = end
	} else {
		for l.bufPos < end {
			b := l.buf[l.bufPos]
			l.bufPos++
			l.offset++
			if b == '\n' {
				l.line++
				l.col = 1
			} else if (b & 0xC0) != 0x80 {
				l.col++
			}
		}
	}
	if l.bufPos > 65536 {
		copy(l.buf, l.buf[l.bufPos:])
		l.buf = l.buf[:len(l.buf)-l.bufPos]
		l.bufPos = 0
	}
}

func (l *Lexer) longestMatch() (int, uint16) {
	for {
		bestLen, bestKind, scanned := l.matcher(l.buf, l.bufPos)
		viewLen := len(l.buf) - l.bufPos
		if !l.eof && scanned == viewLen {
			if l.readMore() {
				continue
			}
		}
		return bestLen, bestKind
	}
}

// NextToken produces the next token. Emits repeated EOF once input ends.
// Lex failures come through with KindOK == false.
func (l *Lexer) NextToken() Token {
	l.ensure(lexChunk)
	if len(l.buf)-l.bufPos == 0 {
		p := l.pos()
		return Token{Kind: l.eofKind, KindOK: true, Span: PointSpan(p)}
	}
	bestLen, bestKind := l.longestMatch()
	start := l.pos()
	if bestLen == 0 {
		_, n := utf8.DecodeRune(l.buf[l.bufPos:])
		if n < 1 {
			n = 1
		}
		text := string(l.buf[l.bufPos : l.bufPos+n])
		l.advance(n)
		return Token{KindOK: false, Span: Span{Start: start, End: l.pos()}, Text: text}
	}
	text := string(l.buf[l.bufPos : l.bufPos+bestLen])
	l.advance(bestLen)
	return Token{Kind: bestKind, KindOK: true, Span: Span{Start: start, End: l.pos()}, Text: text}
}

// Config is the grammar-specific callback bundle a generated parser wires
// into the runtime.
type Config struct {
	K       int
	EofKind uint16
	IsSkip  func(kind uint16) bool
	Drive   func(p *Parser)
}

// Parser is the pull-based parser. Obtain one via NewParser, then call
// NextEvent in a loop.
type Parser struct {
	lex          *Lexer
	lookBuf      []Token
	prevEnd      Pos
	state        int
	ret          []int
	queue        []Event
	pendingSkips []Token
	eofChecked   bool
	cfg          Config
}

// NewParser builds a parser starting at state `entry`.
func NewParser(lex *Lexer, entry int, cfg Config) *Parser {
	p := &Parser{lex: lex, state: entry, cfg: cfg, lookBuf: make([]Token, 0, cfg.K)}
	for i := 0; i < cfg.K; i++ {
		p.lookBuf = append(p.lookBuf, p.pumpToken())
	}
	p.prevEnd = p.lookBuf[0].Span.Start
	return p
}

// Look peeks at the i-th lookahead token.
func (p *Parser) Look(i int) Token { return p.lookBuf[i] }

// State returns the current state id.
func (p *Parser) State() int { return p.state }

// SetState overwrites the current state id.
func (p *Parser) SetState(s int) { p.state = s }

// PushRet pushes a return address onto the call stack.
func (p *Parser) PushRet(s int) { p.ret = append(p.ret, s) }

// PopRet pops the top return address, or Terminated when the stack is empty.
func (p *Parser) PopRet() int {
	if len(p.ret) == 0 {
		return Terminated
	}
	s := p.ret[len(p.ret)-1]
	p.ret = p.ret[:len(p.ret)-1]
	return s
}

// QueueIsEmpty reports whether no events are queued.
func (p *Parser) QueueIsEmpty() bool { return len(p.queue) == 0 }

// MatchesFirst reports whether the current lookahead matches any prefix
// in set. Used by generated dispatch logic with k > 1 lookahead.
// A lookahead slot whose KindOK is false never matches.
func (p *Parser) MatchesFirst(set [][]uint16) bool {
outer:
	for _, seq := range set {
		for i, want := range seq {
			if !p.lookBuf[i].KindOK || p.lookBuf[i].Kind != want {
				continue outer
			}
		}
		return true
	}
	return false
}

func containsKind(set []uint16, k uint16) bool {
	for _, x := range set {
		if x == k {
			return true
		}
	}
	return false
}

// Enter emits an Enter event for the given rule kind.
func (p *Parser) Enter(rule uint16) {
	pos := p.lookBuf[0].Span.Start
	p.prevEnd = pos
	p.emit(Event{Tag: EvEnter, Rule: rule, Pos: pos})
}

// Exit emits an Exit event for the given rule kind, anchored at the end
// of the previously consumed token.
func (p *Parser) Exit(rule uint16) {
	p.emit(Event{Tag: EvExit, Rule: rule, Pos: p.prevEnd})
}

// Consume consumes the current lookahead and emits it as a token event.
func (p *Parser) Consume() {
	prev := p.lookBuf[0]
	p.prevEnd = prev.Span.End
	p.emit(Event{Tag: EvToken, Token: prev})
	p.advanceLook()
}

// TryConsume consumes a token of the given kind; on mismatch, emits an
// error, recovers to `sync`, and retries once.
func (p *Parser) TryConsume(kind uint16, sync []uint16, name string) {
	if p.lookBuf[0].KindOK && p.lookBuf[0].Kind == kind {
		p.Consume()
		return
	}
	p.ErrorHere("expected " + name)
	p.RecoverTo(sync)
	if p.lookBuf[0].KindOK && p.lookBuf[0].Kind == kind {
		p.Consume()
	}
}

// RecoverTo consumes tokens until the lookahead matches sync (or EOF).
// Tokens with KindOK == false are unconditionally consumed during
// recovery — they never match a sync kind and aren't EOF.
func (p *Parser) RecoverTo(sync []uint16) {
	for {
		t := p.lookBuf[0]
		if t.KindOK && t.Kind == p.cfg.EofKind {
			return
		}
		if t.KindOK && containsKind(sync, t.Kind) {
			return
		}
		p.emit(Event{Tag: EvToken, Token: t})
		p.advanceLook()
	}
}

// ErrorHere raises a recoverable error at the current lookahead.
func (p *Parser) ErrorHere(msg string) {
	p.queue = append(p.queue, Event{Tag: EvError, Err: ParseError{Message: msg, Span: p.lookBuf[0].Span}})
}

// NextEvent returns the next parse event and true, or a zero Event and
// false once input is fully consumed.
func (p *Parser) NextEvent() (Event, bool) {
	for {
		if len(p.queue) > 0 {
			ev := p.queue[0]
			p.queue = p.queue[1:]
			return ev, true
		}
		if p.state == Terminated {
			if !p.eofChecked {
				p.eofChecked = true
				atEof := func() bool {
					t := p.lookBuf[0]
					return t.KindOK && t.Kind == p.cfg.EofKind
				}
				if !atEof() {
					p.ErrorHere("expected end of input")
					for !atEof() {
						p.emit(Event{Tag: EvToken, Token: p.lookBuf[0]})
						p.advanceLook()
					}
				}
				p.flushSkipsBefore(p.lookBuf[0].Span.End)
				continue
			}
			return Event{}, false
		}
		p.cfg.Drive(p)
	}
}

func (p *Parser) pumpToken() Token {
	for {
		t := p.lex.NextToken()
		if t.KindOK && p.cfg.IsSkip(t.Kind) {
			p.pendingSkips = append(p.pendingSkips, t)
			continue
		}
		return t
	}
}

func (p *Parser) advanceLook() {
	p.lookBuf = append(p.lookBuf[1:], p.pumpToken())
}

// flushSkipsBefore drains skip tokens whose end offset is <= pos.Offset.
// Called before every event so whitespace/comments appear in source order.
func (p *Parser) flushSkipsBefore(pos Pos) {
	for len(p.pendingSkips) > 0 && p.pendingSkips[0].Span.End.Offset <= pos.Offset {
		t := p.pendingSkips[0]
		p.pendingSkips = p.pendingSkips[1:]
		p.queue = append(p.queue, Event{Tag: EvToken, Token: t})
	}
}

func (p *Parser) emit(ev Event) {
	var start Pos
	switch ev.Tag {
	case EvEnter, EvExit:
		start = ev.Pos
	case EvToken:
		start = ev.Token.Span.Start
	default:
		start = ev.Err.Span.Start
	}
	p.flushSkipsBefore(start)
	p.queue = append(p.queue, ev)
}
