use std::fmt::Write;
use std::path::PathBuf;

use crate::codegen::common::screaming_snake;
use crate::codegen::EmittedFile;
use crate::lowering::lexer_dfa::{DfaState, START};
use crate::lowering::recovery::{Insertion, PostFirst};
use crate::lowering::{Body, DispatchLeaf, DispatchTree, Instr, StateTable, Tail};

/// Per-backend arguments. Currently empty — kept as a struct (deriving
/// [`clap::Args`]) so the CLI can flatten any future flags in directly
/// and the [`emit`] signature stays stable.
#[derive(clap::Args, Clone, Debug, Default)]
pub struct Args {}

pub fn emit(st: &StateTable, _args: &Args) -> Vec<EmittedFile> {
    let stem = if st.grammar_name.is_empty() {
        "parser".to_string()
    } else {
        st.grammar_name.clone()
    };
    let upper = stem.to_ascii_uppercase();

    let mut h = String::new();
    emit_header(&mut h, st, &stem, &upper);

    let mut c = String::new();
    emit_impl(&mut c, st, &stem, &upper);

    vec![
        EmittedFile {
            path: PathBuf::from(format!("{}.h", stem)),
            contents: h,
        },
        EmittedFile {
            path: PathBuf::from(format!("{}.c", stem)),
            contents: c,
        },
    ]
}

fn emit_header(h: &mut String, st: &StateTable, stem: &str, upper: &str) {
    writeln!(h, "/* Generated by parsuna. Do not edit by hand.").unwrap();
    writeln!(h, " *").unwrap();
    writeln!(
        h,
        " * Pull-based, recoverable parser for the `{stem}` grammar. This header"
    )
    .unwrap();
    writeln!(
        h,
        " * is self-contained: it exposes the {stem}_* API and has no dependency"
    )
    .unwrap();
    writeln!(
        h,
        " * on the internal parsuna runtime. Build against the emitted {stem}.c,"
    )
    .unwrap();
    writeln!(h, " * which pulls in the header-only runtime internally.").unwrap();
    writeln!(h, " *").unwrap();
    writeln!(
        h,
        " * Usage:  p = {stem}_parser_new_<rule>_from_string(src, len);"
    )
    .unwrap();
    writeln!(
        h,
        " *   or    p = {stem}_parser_new_<rule>_from_read_fn(fn, ctx);"
    )
    .unwrap();
    writeln!(h, " *         while ({stem}_next(p, &ev)) {{ ... }}").unwrap();
    writeln!(h, " *         {stem}_parser_free(p);").unwrap();
    writeln!(h, " */").unwrap();
    writeln!(h, "#ifndef {upper}_H").unwrap();
    writeln!(h, "#define {upper}_H").unwrap();
    writeln!(h, "#include <stddef.h>").unwrap();
    writeln!(h, "#include <stdint.h>").unwrap();
    writeln!(h, "#ifdef __cplusplus").unwrap();
    writeln!(h, "extern \"C\" {{").unwrap();
    writeln!(h, "#endif").unwrap();
    writeln!(h).unwrap();

    /* Public value types. Layouts mirror the runtime's internal types
     * (guarded by _Static_asserts in the .c); that lets the .c cast
     * pointers between them without copying. */
    writeln!(
        h,
        "/* Source position: byte offset plus 1-based line/column. */"
    )
    .unwrap();
    writeln!(
        h,
        "typedef struct {{ uint32_t offset, line, column; }} {stem}_Pos;"
    )
    .unwrap();
    writeln!(h).unwrap();
    writeln!(h, "/* Half-open span [start, end) over the source. */").unwrap();
    writeln!(
        h,
        "typedef struct {{ {stem}_Pos start, end; }} {stem}_Span;"
    )
    .unwrap();
    writeln!(h).unwrap();
    writeln!(h, "/* A lexed token: kind, span, and matched text.").unwrap();
    writeln!(h, " *").unwrap();
    writeln!(
        h,
        " * In *reader* mode ({stem}_parser_new_<rule>_from_read_fn) `text` is an"
    )
    .unwrap();
    writeln!(
        h,
        " * allocation owned by the parser until the next call to {stem}_next and is"
    )
    .unwrap();
    writeln!(
        h,
        " * NUL-terminated; in *string* mode ({stem}_parser_new_<rule>_from_string)"
    )
    .unwrap();
    writeln!(
        h,
        " * `text` points directly into the caller's source buffer (zero-copy) and"
    )
    .unwrap();
    writeln!(
        h,
        " * is NOT NUL-terminated. Use `text_len` in both modes. */"
    )
    .unwrap();
    writeln!(
        h,
        "typedef struct {{ uint16_t kind; {stem}_Span span; char *text; size_t text_len; }} {stem}_Token;"
    )
    .unwrap();
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* A recoverable error. `message` is owned by the parser until the next"
    )
    .unwrap();
    writeln!(h, " * call to {stem}_next. */").unwrap();
    writeln!(
        h,
        "typedef struct {{ char *message; {stem}_Span span; }} {stem}_Error;"
    )
    .unwrap();
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* Event discriminator: ENTER/EXIT delimit a rule subtree, TOKEN carries"
    )
    .unwrap();
    writeln!(
        h,
        " * a consumed structural token (including skips), GARBAGE is a token"
    )
    .unwrap();
    writeln!(
        h,
        " * dropped during error recovery (between an ERROR event and its sync"
    )
    .unwrap();
    writeln!(h, " * point), ERROR is a recoverable diagnostic. */").unwrap();
    writeln!(h, "typedef enum {{").unwrap();
    writeln!(h, "  {upper}_EV_ENTER,").unwrap();
    writeln!(h, "  {upper}_EV_EXIT,").unwrap();
    writeln!(h, "  {upper}_EV_TOKEN,").unwrap();
    writeln!(h, "  {upper}_EV_GARBAGE,").unwrap();
    writeln!(h, "  {upper}_EV_ERROR").unwrap();
    writeln!(h, "}} {stem}_EventTag;").unwrap();
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* A single parse event; inspect `tag` to decide which payload field to read. */"
    )
    .unwrap();
    writeln!(h, "typedef struct {{").unwrap();
    writeln!(h, "  {stem}_EventTag tag;").unwrap();
    writeln!(h, "  int rule;").unwrap();
    writeln!(h, "  {stem}_Pos pos;").unwrap();
    writeln!(h, "  {stem}_Token token;").unwrap();
    writeln!(h, "  {stem}_Error error;").unwrap();
    writeln!(h, "}} {stem}_Event;").unwrap();
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* Reader callback: fill up to `max` bytes into `out`, return number of"
    )
    .unwrap();
    writeln!(
        h,
        " * bytes written (0 for EOF, negative to signal an error). */"
    )
    .unwrap();
    writeln!(
        h,
        "typedef int (*{stem}_ReadFn)(void *ctx, char *out, int max);"
    )
    .unwrap();
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* Opaque parser state. Obtain via {stem}_parser_new_<rule>_from_string or"
    )
    .unwrap();
    writeln!(
        h,
        " * {stem}_parser_new_<rule>_from_read_fn; free via {stem}_parser_free. */"
    )
    .unwrap();
    writeln!(h, "typedef struct {stem}_Parser {stem}_Parser;").unwrap();
    writeln!(h).unwrap();

    writeln!(
        h,
        "/* Token kinds this grammar can emit. TK_EOF is the runtime end-of-input"
    )
    .unwrap();
    writeln!(
        h,
        " * sentinel; the rest come from the grammar's `token` declarations. Lex"
    )
    .unwrap();
    writeln!(
        h,
        " * failures (no DFA pattern matched) come through as Token instances with"
    )
    .unwrap();
    writeln!(h, " * kind == {upper}_LEX_ERROR. */").unwrap();
    writeln!(h, "typedef enum {{").unwrap();
    writeln!(h, "  {upper}_TK_EOF = 0,").unwrap();
    for t in &st.tokens {
        writeln!(h, "  {upper}_TK_{} = {},", t.name, t.kind).unwrap();
    }
    writeln!(h, "}} {stem}_TokenKind;").unwrap();
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* Lex-failure sentinel: Token.kind == {upper}_LEX_ERROR means the lexer"
    )
    .unwrap();
    writeln!(
        h,
        " * could not match any pattern at the current position. The token still"
    )
    .unwrap();
    writeln!(
        h,
        " * carries the offending byte(s); the parser surfaces a recoverable EV_ERROR"
    )
    .unwrap();
    writeln!(h, " * event alongside. */").unwrap();
    writeln!(h, "#define {upper}_LEX_ERROR ((uint16_t)0xFFFFu)").unwrap();
    writeln!(h).unwrap();

    writeln!(
        h,
        "/* One value per non-fragment rule. Attached via `rule` to"
    )
    .unwrap();
    writeln!(
        h,
        " * {upper}_EV_ENTER/{upper}_EV_EXIT events so callers can identify each subtree. */"
    )
    .unwrap();
    writeln!(h, "typedef enum {{").unwrap();
    for (i, n) in st.rule_kinds.iter().enumerate() {
        writeln!(h, "  {upper}_RK_{} = {i},", screaming_snake(n)).unwrap();
    }
    if st.rule_kinds.is_empty() {
        writeln!(h, "  {upper}_RK__none").unwrap();
    }
    writeln!(h, "}} {stem}_RuleKind;").unwrap();
    writeln!(h).unwrap();

    writeln!(
        h,
        "/* Distinct grammar labels (`name:NAME` form). `Token.label` stores"
    )
    .unwrap();
    writeln!(
        h,
        " * the matching constant's value (or `0` for unlabeled positions);"
    )
    .unwrap();
    writeln!(
        h,
        " * compare via `tok.label == {upper}_LK_FOO` to dispatch on the"
    )
    .unwrap();
    writeln!(h, " * position name without strings. */").unwrap();
    writeln!(h, "typedef enum {{").unwrap();
    if st.labels.is_empty() {
        writeln!(h, "  {upper}_LK__none = 0").unwrap();
    } else {
        for (i, n) in st.labels.iter().enumerate() {
            writeln!(h, "  {upper}_LK_{} = {},", screaming_snake(n), i + 1).unwrap();
        }
    }
    writeln!(h, "}} {stem}_LabelKind;").unwrap();
    writeln!(h).unwrap();

    writeln!(
        h,
        "/* Grammar-declared name for a token kind (or \"?\" if unknown). */"
    )
    .unwrap();
    writeln!(h, "const char *{stem}_token_kind_name(int k);").unwrap();
    writeln!(
        h,
        "/* Grammar-declared name for a rule kind (or \"?\" if unknown). */"
    )
    .unwrap();
    writeln!(h, "const char *{stem}_rule_kind_name(int k);").unwrap();
    writeln!(h).unwrap();

    writeln!(
        h,
        "/* Optional flags accepted by the `*_with_options` constructors. The"
    )
    .unwrap();
    writeln!(
        h,
        " * no-options constructors use a zero-initialized struct (all defaults). */"
    )
    .unwrap();
    writeln!(h, "typedef struct {{").unwrap();
    writeln!(
        h,
        "    /* When non-zero, skip tokens (whitespace, comments) are silently"
    )
    .unwrap();
    writeln!(
        h,
        "     * consumed instead of yielded as EV_TOKEN events. */"
    )
    .unwrap();
    writeln!(h, "    int drop_skips;").unwrap();
    writeln!(
        h,
        "    /* When non-zero, every Token whose `Token.label` is NULL (i.e."
    )
    .unwrap();
    writeln!(
        h,
        "     * that didn't match a `name:NAME` position) is silently consumed."
    )
    .unwrap();
    writeln!(h, "     * Implies skip-token suppression. */").unwrap();
    writeln!(h, "    int drop_unlabeled_tokens;").unwrap();
    writeln!(h, "}} {stem}_Options;").unwrap();
    writeln!(h).unwrap();

    for (name, _) in &st.entry_states {
        writeln!(
            h,
            "/* Zero-copy parser over the `{name}` rule, reading from an in-memory"
        )
        .unwrap();
        writeln!(
            h,
            " * buffer. The caller keeps ownership of `src`, which must remain live"
        )
        .unwrap();
        writeln!(
            h,
            " * and unmodified until {stem}_parser_free. `len` is the number of bytes."
        )
        .unwrap();
        writeln!(
            h,
            " * Token.text fields point directly into `src` (not NUL-terminated). */"
        )
        .unwrap();
        writeln!(
            h,
            "{stem}_Parser *{stem}_parser_new_{name}_from_string(const char *src, size_t len);"
        )
        .unwrap();
        writeln!(h).unwrap();
        writeln!(
            h,
            "/* Streaming parser over the `{name}` rule, pulling bytes through `read_fn`."
        )
        .unwrap();
        writeln!(
            h,
            " * The runtime buffers and copies as needed; Token.text fields are owned"
        )
        .unwrap();
        writeln!(
            h,
            " * and NUL-terminated. Returns a heap-allocated handle; free with"
        )
        .unwrap();
        writeln!(h, " * {stem}_parser_free. */").unwrap();
        writeln!(
            h,
            "{stem}_Parser *{stem}_parser_new_{name}_from_read_fn({stem}_ReadFn read_fn, void *ctx);"
        )
        .unwrap();
        writeln!(h).unwrap();
        writeln!(
            h,
            "/* `_with_options` variants accept a {stem}_Options struct controlling"
        )
        .unwrap();
        writeln!(
            h,
            " * skip-token and unlabeled-token suppression. Otherwise identical to"
        )
        .unwrap();
        writeln!(h, " * the constructors above. */").unwrap();
        writeln!(
            h,
            "{stem}_Parser *{stem}_parser_new_{name}_from_string_with_options(const char *src, size_t len, {stem}_Options opts);"
        )
        .unwrap();
        writeln!(
            h,
            "{stem}_Parser *{stem}_parser_new_{name}_from_read_fn_with_options({stem}_ReadFn read_fn, void *ctx, {stem}_Options opts);"
        )
        .unwrap();
    }
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* Produce the next event into `*out`. Returns 1 on fresh event, 0 once"
    )
    .unwrap();
    writeln!(
        h,
        " * the input is fully consumed. String fields inside `*out` are owned"
    )
    .unwrap();
    writeln!(h, " * by `p` and stay valid only until the next call. */").unwrap();
    writeln!(h, "int {stem}_next({stem}_Parser *p, {stem}_Event *out);").unwrap();
    writeln!(h).unwrap();
    writeln!(
        h,
        "/* Free every allocation owned by `p`, including `p` itself. */"
    )
    .unwrap();
    writeln!(h, "void {stem}_parser_free({stem}_Parser *p);").unwrap();

    writeln!(h).unwrap();
    writeln!(h, "#ifdef __cplusplus").unwrap();
    writeln!(h, "}}").unwrap();
    writeln!(h, "#endif").unwrap();
    writeln!(h, "#endif").unwrap();
}

fn emit_impl(c: &mut String, st: &StateTable, stem: &str, upper: &str) {
    writeln!(c, "#include \"{stem}.h\"").unwrap();
    writeln!(c, "#include <stdlib.h>").unwrap();
    writeln!(c, "#include <string.h>").unwrap();
    writeln!(c).unwrap();
    /* Monomorphize the runtime: PARSUNA_K is consumed inside
     * parsuna_rt.h so `look_buf`, is_skip, and step are baked in at
     * compile time rather than dispatched through a Config vtable.
     * EOF is always token kind 0 (PARSUNA_TK_EOF in the runtime,
     * re-exported as `{upper}_TK_EOF` in the public header); lex
     * failures use PARSUNA_LEX_ERROR (always 0xFFFF, re-exported as
     * `{upper}_LEX_ERROR`). */
    writeln!(c, "#define PARSUNA_K {}", st.k).unwrap();
    writeln!(c, "#include \"parsuna_rt.h\"").unwrap();
    writeln!(c).unwrap();
    /* ABI compatibility between the public `<stem>_*` types exposed in
     * the header and the runtime's internal (unprefixed) types. If this
     * ever breaks, the pointer casts below become undefined. */
    writeln!(
        c,
        "/* Compile-time check that the public types line up byte-for-byte"
    )
    .unwrap();
    writeln!(
        c,
        " * with the runtime's internal ones, so pointer casts are sound. */"
    )
    .unwrap();
    writeln!(
        c,
        "_Static_assert(sizeof({stem}_Pos)   == sizeof(Pos),   \"Pos layout mismatch\");"
    )
    .unwrap();
    writeln!(
        c,
        "_Static_assert(sizeof({stem}_Span)  == sizeof(Span),  \"Span layout mismatch\");"
    )
    .unwrap();
    writeln!(
        c,
        "_Static_assert(sizeof({stem}_Token) == sizeof(Token), \"Token layout mismatch\");"
    )
    .unwrap();
    writeln!(
        c,
        "_Static_assert(sizeof({stem}_Error) == sizeof(Error), \"Error layout mismatch\");"
    )
    .unwrap();
    writeln!(
        c,
        "_Static_assert(sizeof({stem}_Event) == sizeof(Event), \"Event layout mismatch\");"
    )
    .unwrap();
    writeln!(c).unwrap();

    emit_name_tables(c, st, stem, upper);
    emit_dfa(c, st, upper);
    emit_tables(c, st, upper);
    emit_skip(c, st, upper);
    emit_apply_actions(c, st, upper);
    emit_step(c, st, stem, upper);
    emit_public_api(c, st, stem, upper);
}

fn emit_name_tables(c: &mut String, st: &StateTable, stem: &str, upper: &str) {
    writeln!(c, "const char *{stem}_token_kind_name(int k) {{").unwrap();
    writeln!(c, "  switch (k) {{").unwrap();
    for t in &st.tokens {
        writeln!(c, "    case {upper}_TK_{}: return \"{}\";", t.name, t.name).unwrap();
    }
    writeln!(c, "    case {upper}_LEX_ERROR: return \"ERROR\";").unwrap();
    writeln!(c, "    case {upper}_TK_EOF: return \"EOF\";").unwrap();
    writeln!(c, "    default: return \"?\";").unwrap();
    writeln!(c, "  }}").unwrap();
    writeln!(c, "}}").unwrap();
    writeln!(c).unwrap();

    writeln!(c, "const char *{stem}_rule_kind_name(int k) {{").unwrap();
    writeln!(c, "  switch (k) {{").unwrap();
    for n in &st.rule_kinds {
        writeln!(
            c,
            "    case {upper}_RK_{}: return \"{n}\";",
            screaming_snake(n)
        )
        .unwrap();
    }
    writeln!(c, "    default: return \"?\";").unwrap();
    writeln!(c, "  }}").unwrap();
    writeln!(c, "}}").unwrap();
    writeln!(c).unwrap();
}

fn emit_dfa(c: &mut String, st: &StateTable, upper: &str) {
    writeln!(
        c,
        "/* Compiled lexer DFA: one helper per declared lexer mode. */"
    )
    .unwrap();
    for m in &st.modes {
        writeln!(
            c,
            "/* Longest-match helper for lexer mode `{}` (id {}). */",
            m.name, m.id
        )
        .unwrap();
        writeln!(
            c,
            "static void longest_match_mode{}_impl(const char *buf, size_t buf_len, size_t start,",
            m.id
        )
        .unwrap();
        writeln!(
            c,
            "                               uint16_t *best_kind, size_t *best_len, size_t *scanned) {{"
        )
        .unwrap();
        writeln!(c, "  size_t pos = start;").unwrap();
        writeln!(c, "  size_t bl = 0;").unwrap();
        writeln!(c, "  uint16_t bk = {}_LEX_ERROR;", upper).unwrap();
        writeln!(c, "  uint32_t state = {}u;", START).unwrap();
        writeln!(c, "  for (;;) {{").unwrap();
        writeln!(c, "    switch (state) {{").unwrap();
        for ds in &m.dfa {
            emit_dfa_state_arm(c, st, ds, upper);
        }
        writeln!(c, "      default: goto done;").unwrap();
        writeln!(c, "    }}").unwrap();
        writeln!(c, "  }}").unwrap();
        writeln!(c, "done:").unwrap();
        writeln!(c, "  *best_kind = bk;").unwrap();
        writeln!(c, "  *best_len = bl;").unwrap();
        writeln!(c, "  *scanned = pos - start;").unwrap();
        writeln!(c, "}}").unwrap();
        writeln!(c).unwrap();
    }

    /* Mode-dispatch entry point. Single-mode grammars collapse to a direct
     * call so the dispatcher inlines away. */
    writeln!(
        c,
        "static void longest_match_impl(const char *buf, size_t buf_len, size_t start,"
    )
    .unwrap();
    writeln!(
        c,
        "                               uint32_t mode, uint16_t *best_kind, size_t *best_len, size_t *scanned) {{"
    )
    .unwrap();
    if st.modes.len() == 1 {
        writeln!(c, "  (void)mode;").unwrap();
        writeln!(
            c,
            "  longest_match_mode0_impl(buf, buf_len, start, best_kind, best_len, scanned);"
        )
        .unwrap();
    } else {
        writeln!(c, "  switch (mode) {{").unwrap();
        for m in &st.modes {
            writeln!(
                c,
                "    case {}: longest_match_mode{}_impl(buf, buf_len, start, best_kind, best_len, scanned); return;",
                m.id, m.id
            )
            .unwrap();
        }
        writeln!(
            c,
            "    default: *best_kind = {}_LEX_ERROR; *best_len = 0; *scanned = 0; return;",
            upper
        )
        .unwrap();
        writeln!(c, "  }}").unwrap();
    }
    writeln!(c, "}}").unwrap();
    writeln!(c).unwrap();
}

fn emit_dfa_state_arm(c: &mut String, st: &StateTable, ds: &DfaState, upper: &str) {
    if ds.arms.is_empty() {
        writeln!(c, "      case {}: goto done;", ds.id).unwrap();
        return;
    }
    writeln!(c, "      case {}: {{", ds.id).unwrap();
    let self_loop = ds.self_loop_ranges();
    if !self_loop.is_empty() {
        // Self-loop scan-skip prologue. clang/gcc autovectorise tight
        // byte-test loops with -O2; we keep the body simple and let
        // the optimiser lift it into SIMD on platforms that support it.
        writeln!(c, "        while (pos < buf_len) {{").unwrap();
        writeln!(c, "          unsigned char b = (unsigned char)buf[pos];").unwrap();
        writeln!(c, "          if (!({})) break;", byte_cond(self_loop)).unwrap();
        writeln!(c, "          pos++;").unwrap();
        writeln!(c, "        }}").unwrap();
        if let Some(kind) = ds.accept {
            writeln!(c, "        bl = pos - start;").unwrap();
            writeln!(
                c,
                "        bk = (uint16_t){};",
                c_token_name(st, upper, kind)
            )
            .unwrap();
        }
    }
    writeln!(c, "        if (pos >= buf_len) goto done;").unwrap();
    writeln!(c, "        unsigned char b = (unsigned char)buf[pos];").unwrap();
    let mut first = true;
    for arm in &ds.arms {
        let cond = byte_cond(&arm.ranges);
        let kw = if first { "if" } else { "else if" };
        first = false;
        write!(
            c,
            "        {} ({}) {{ pos++; state = {}u;",
            kw, cond, arm.target
        )
        .unwrap();
        if let Some(kind) = arm.target_accept {
            write!(
                c,
                " bl = pos - start; bk = (uint16_t){};",
                c_token_name(st, upper, kind)
            )
            .unwrap();
        }
        writeln!(c, " }}").unwrap();
    }
    writeln!(c, "        else goto done;").unwrap();
    writeln!(c, "        break;").unwrap();
    writeln!(c, "      }}").unwrap();
}

fn byte_cond(ranges: &[(u8, u8)]) -> String {
    ranges
        .iter()
        .map(|(lo, hi)| {
            if lo == hi {
                format!("b == {}", byte_literal(*lo))
            } else {
                format!("(b >= {} && b <= {})", byte_literal(*lo), byte_literal(*hi))
            }
        })
        .collect::<Vec<_>>()
        .join(" || ")
}

fn byte_literal(b: u8) -> String {
    match b {
        b'\\' => "'\\\\'".to_string(),
        b'\'' => "'\\''".to_string(),
        b'\n' => "'\\n'".to_string(),
        b'\r' => "'\\r'".to_string(),
        b'\t' => "'\\t'".to_string(),
        0x20..=0x7E => format!("'{}'", b as char),
        _ => format!("0x{:02x}", b),
    }
}

fn emit_tables(c: &mut String, st: &StateTable, upper: &str) {
    /* Lookahead width is baked in via PARSUNA_K at the top of the file. */

    for f in &st.first_sets {
        /* The Rust backend gates emission on `has_references` because its
         * K==1 lookahead uses an inline `match`/`kind_pattern` instead of
         * a FIRST table. The C backend's emit_op always calls
         * matches_first(p, FIRST_N) for Op::Star/Opt regardless of K, so
         * we emit every FIRST set unconditionally — the lowering layer
         * leaves `has_references` false at K==1 and would otherwise
         * produce dangling references here. */
        let i = f.id;
        for (j, seq) in f.seqs.iter().enumerate() {
            let parts: Vec<String> = seq.iter().map(|t| c_token_name(st, upper, *t)).collect();
            let joined = parts.join(", ");
            let sep = if parts.is_empty() { "" } else { ", " };
            writeln!(
                c,
                "static const uint16_t FIRST_{i}_{j}[] = {{ {joined}{sep}SENTINEL }};"
            )
            .unwrap();
        }
        write!(c, "static const uint16_t *const FIRST_{i}[] = {{").unwrap();
        for j in 0..f.seqs.len() {
            write!(c, " FIRST_{i}_{j},").unwrap();
        }
        writeln!(c, " NULL }};").unwrap();
    }
    for f in &st.sync_sets {
        let i = f.id;
        let s: Vec<String> = f
            .kinds
            .iter()
            .map(|t| c_token_name(st, upper, *t))
            .collect();
        let joined = s.join(", ");
        let sep = if s.is_empty() { "" } else { ", " };
        writeln!(
            c,
            "static const uint16_t SYNC_{i}[] = {{ {joined}{sep}SENTINEL }};"
        )
        .unwrap();
    }
    writeln!(c).unwrap();
}

fn emit_skip(c: &mut String, st: &StateTable, upper: &str) {
    writeln!(c, "static int is_skip(uint16_t kind) {{").unwrap();
    let skips: Vec<String> = st
        .tokens
        .iter()
        .filter(|t| t.skip)
        .map(|t| format!("kind == {}", c_token_name(st, upper, t.kind)))
        .collect();
    if skips.is_empty() {
        writeln!(c, "  (void)kind; return 0;").unwrap();
    } else {
        writeln!(c, "  return {};", skips.join(" || ")).unwrap();
    }
    writeln!(c, "}}").unwrap();
    writeln!(c).unwrap();
}

fn emit_apply_actions(c: &mut String, st: &StateTable, upper: &str) {
    use crate::lowering::ModeActionInfo;

    let action_tokens: Vec<&crate::lowering::TokenInfo> = st
        .tokens
        .iter()
        .filter(|t| !t.mode_actions.is_empty())
        .collect();

    writeln!(
        c,
        "/* Apply per-token mode-stack actions to `p`. Generated as a switch"
    )
    .unwrap();
    writeln!(
        c,
        " * over token kinds; tokens without `-> push/pop` fall through. */"
    )
    .unwrap();
    writeln!(c, "static void apply_actions(uint16_t kind, Parser *p) {{").unwrap();
    if action_tokens.is_empty() {
        writeln!(c, "  (void)kind; (void)p;").unwrap();
    } else {
        writeln!(c, "  switch (kind) {{").unwrap();
        for t in &action_tokens {
            writeln!(c, "    case {}: {{", c_token_name(st, upper, t.kind)).unwrap();
            for action in &t.mode_actions {
                match action {
                    ModeActionInfo::Push(id) => {
                        writeln!(c, "      parser_push_mode(p, {}u);", id).unwrap();
                    }
                    ModeActionInfo::Pop => {
                        writeln!(c, "      parser_pop_mode(p);").unwrap();
                    }
                }
            }
            writeln!(c, "      break;").unwrap();
            writeln!(c, "    }}").unwrap();
        }
        writeln!(c, "    default: (void)p; break;").unwrap();
        writeln!(c, "  }}").unwrap();
    }
    writeln!(c, "}}").unwrap();
    writeln!(c).unwrap();
}

fn emit_step(c: &mut String, st: &StateTable, _stem: &str, upper: &str) {
    writeln!(c, "static int step(Parser *p, Event *out) {{").unwrap();
    writeln!(c, "  int cur = get_state(p);").unwrap();
    writeln!(c, "  int emitted = 0;").unwrap();
    writeln!(c, "  switch (cur) {{").unwrap();
    for state in st.states.values() {
        writeln!(c, "    case {}: {{ /* {} */", state.id, state.label).unwrap();
        emit_body(c, st, upper, &state.body, "      ");
        writeln!(c, "      break;").unwrap();
        writeln!(c, "    }}").unwrap();
    }
    writeln!(c, "  }}").unwrap();
    writeln!(c, "  set_state(p, cur);").unwrap();
    writeln!(c, "  return emitted;").unwrap();
    writeln!(c, "}}").unwrap();
    writeln!(c).unwrap();
}

fn c_token_name(st: &StateTable, upper: &str, kind: u16) -> String {
    if kind == 0 {
        return format!("{upper}_TK_EOF");
    }
    match st.tokens.iter().find(|t| t.kind == kind) {
        Some(t) => format!("{upper}_TK_{}", t.name),
        None => panic!("unknown token id {} while emitting C backend", kind),
    }
}

fn emit_instr(c: &mut String, st: &StateTable, upper: &str, op: &Instr, ind: &str) {
    match op {
        Instr::Enter(k) => {
            let name = st
                .rule_kinds
                .get(*k as usize)
                .unwrap_or_else(|| panic!("unknown rule kind id {} while emitting C backend", k));
            writeln!(
                c,
                "{ind}*out = ev_enter(p, {upper}_RK_{}); emitted = 1;",
                screaming_snake(name)
            )
            .unwrap()
        }
        Instr::Exit(k) => {
            let name = st
                .rule_kinds
                .get(*k as usize)
                .unwrap_or_else(|| panic!("unknown rule kind id {} while emitting C backend", k));
            writeln!(
                c,
                "{ind}*out = ev_exit(p, {upper}_RK_{}); emitted = 1;",
                screaming_snake(name)
            )
            .unwrap()
        }
        Instr::Expect { kind, sync, label } => {
            let name = c_token_name(st, upper, *kind);
            let display = crate::codegen::common::token_display_name_for_kind(st, *kind);
            let label_arg = match label {
                Some(id) => format!(
                    "{upper}_LK_{}",
                    screaming_snake(&st.labels[(*id as usize) - 1])
                ),
                None => "0".to_string(),
            };
            writeln!(
                c,
                "{ind}*out = try_consume_labeled(p, {name}, SYNC_{sync}, \"{display}\", {label_arg}); emitted = 1;"
            )
            .unwrap()
        }
        Instr::PushRet(r) => writeln!(c, "{ind}push_ret(p, {r});").unwrap(),
    }
}

fn emit_tail(c: &mut String, st: &StateTable, upper: &str, tail: &Tail, ind: &str) {
    match tail {
        Tail::Jump(n) => writeln!(c, "{ind}cur = {n};").unwrap(),
        Tail::Ret => {
            writeln!(c, "{ind}cur = pop_ret(p);").unwrap();
        }
        Tail::Star {
            first,
            body,
            cont,
            head,
        } => {
            let inner = format!("{ind}  ");
            let miss = match cont {
                Some(n) => format!("cur = {n};"),
                None => "cur = pop_ret(p);".to_string(),
            };
            writeln!(c, "{ind}if (matches_first(p, FIRST_{first})) {{").unwrap();
            writeln!(c, "{inner}push_ret(p, {head});").unwrap();
            emit_body(c, st, upper, body, &inner);
            writeln!(c, "{ind}}} else {{ {miss} }}").unwrap();
        }
        Tail::Opt { first, body, cont } => {
            let inner = format!("{ind}  ");
            let miss = match cont {
                Some(n) => format!("cur = {n};"),
                None => "cur = pop_ret(p);".to_string(),
            };
            writeln!(c, "{ind}if (matches_first(p, FIRST_{first})) {{").unwrap();
            if let Some(n) = cont {
                writeln!(c, "{inner}push_ret(p, {n});").unwrap();
            }
            emit_body(c, st, upper, body, &inner);
            writeln!(c, "{ind}}} else {{ {miss} }}").unwrap();
        }
        Tail::Dispatch {
            tree,
            sync,
            cont,
            insertions,
        } => {
            emit_dispatch_tree(c, st, upper, tree, *sync, *cont, insertions, ind);
        }
    }
}

/// Emit each op of `body` at the current indent. The body's tail op
/// is its own terminator (`Ret`, `Jump`, another branchy op …) so
/// the linear emission settles the post-body transition with no
/// extra glue.
fn emit_body(c: &mut String, st: &StateTable, upper: &str, body: &Body, ind: &str) {
    for op in &body.instrs {
        emit_instr(c, st, upper, op, ind);
    }
    emit_tail(c, st, upper, &body.tail, ind);
}

fn emit_dispatch_tree(
    c: &mut String,
    st: &StateTable,
    upper: &str,
    tree: &DispatchTree,
    sync: u32,
    cont: Option<u32>,
    insertions: &[Insertion],
    ind: &str,
) {
    match tree {
        DispatchTree::Leaf(leaf) => {
            writeln!(c, "{}{{", ind).unwrap();
            emit_dispatch_leaf_block(c, st, upper, leaf, sync, cont, &[], &format!("{}  ", ind));
            writeln!(c, "{}}}", ind).unwrap();
        }
        DispatchTree::Switch {
            depth,
            arms,
            default,
        } => {
            // Insertion arms only flow at depth 0; nested sub-trees
            // can't contribute new look[0] candidates.
            let inner_inserts: &[Insertion] = if *depth == 0 { insertions } else { &[] };

            writeln!(c, "{}switch (look(p, {}).kind) {{", ind, depth).unwrap();
            let inner = format!("{}  ", ind);
            for (kind, sub) in arms {
                let name = c_token_name(st, upper, *kind);
                writeln!(c, "{}case {}: {{", inner, name).unwrap();
                emit_dispatch_tree(c, st, upper, sub, sync, cont, &[], &format!("{}  ", inner));
                writeln!(c, "{}}} break;", inner).unwrap();
            }
            writeln!(c, "{}default: {{", inner).unwrap();
            emit_dispatch_leaf_block(
                c,
                st,
                upper,
                default,
                sync,
                cont,
                inner_inserts,
                &format!("{}  ", inner),
            );
            writeln!(c, "{}}} break;", inner).unwrap();
            writeln!(c, "{}}}", ind).unwrap();
        }
    }
}

fn emit_insertion(c: &mut String, st: &StateTable, upper: &str, ins: &Insertion, ind: &str) {
    let cond = ins
        .kinds_to_match
        .iter()
        .map(|k| format!("look0 == {}", c_token_name(st, upper, *k)))
        .collect::<Vec<_>>()
        .join(" || ");
    writeln!(c, "{ind}if ({cond}) {{").unwrap();
    let inner = format!("{ind}  ");
    match &ins.post_first {
        PostFirst::Jump(n) => {
            writeln!(c, "{inner}cur = {n};").unwrap();
        }
        PostFirst::PushRetAndJump { push, jump } => {
            writeln!(c, "{inner}push_ret(p, {push});").unwrap();
            writeln!(c, "{inner}cur = {jump};").unwrap();
        }
        PostFirst::Ret => {
            writeln!(c, "{inner}cur = pop_ret(p);").unwrap();
        }
    }
    writeln!(
        c,
        "{inner}*out = ev_error_here(p, \"{}\"); emitted = 1;",
        crate::codegen::common::expected_message(st, &ins.candidate_kinds)
    )
    .unwrap();
    writeln!(c, "{ind}}} else").unwrap();
}

fn emit_dispatch_leaf_block(
    c: &mut String,
    st: &StateTable,
    upper: &str,
    leaf: &DispatchLeaf,
    sync: u32,
    cont: Option<u32>,
    insertions: &[Insertion],
    ind: &str,
) {
    match (leaf, cont) {
        (DispatchLeaf::Arm(b), Some(n)) => {
            writeln!(c, "{ind}push_ret(p, {n});").unwrap();
            emit_body(c, st, upper, b, ind);
        }
        (DispatchLeaf::Arm(b), None) => {
            emit_body(c, st, upper, b, ind);
        }
        (DispatchLeaf::Fallthrough, Some(n)) => writeln!(c, "{ind}cur = {n};").unwrap(),
        (DispatchLeaf::Fallthrough, None) => writeln!(c, "{ind}cur = pop_ret(p);").unwrap(),
        (DispatchLeaf::Error, _) => {
            // Insertion-recovery first: each candidate is a missing-
            // first-token that would let the arm body continue.
            // Primary kinds already matched in the outer switch, so
            // any look[0] reaching this branch is by construction
            // *not* a primary kind.
            if !insertions.is_empty() {
                writeln!(c, "{ind}uint16_t look0 = look(p, 0).kind;").unwrap();
                for ins in insertions {
                    emit_insertion(c, st, upper, ins, ind);
                }
            }
            writeln!(c, "{ind}{{").unwrap();
            let inner = format!("{ind}  ");
            match cont {
                Some(n) => {
                    writeln!(c, "{inner}cur = {n};").unwrap();
                    writeln!(
                        c,
                        "{inner}*out = ev_error_here(p, \"unexpected token\"); emitted = 1;"
                    )
                    .unwrap();
                    writeln!(c, "{inner}recover_to(p, SYNC_{sync});").unwrap();
                }
                None => {
                    writeln!(
                        c,
                        "{inner}*out = ev_error_here(p, \"unexpected token\"); emitted = 1;"
                    )
                    .unwrap();
                    writeln!(c, "{inner}recover_to(p, SYNC_{sync});").unwrap();
                    writeln!(c, "{inner}cur = pop_ret(p);").unwrap();
                }
            }
            writeln!(c, "{ind}}}").unwrap();
        }
    }
}

fn emit_public_api(c: &mut String, st: &StateTable, stem: &str, upper: &str) {
    let _ = upper;
    /* Constructors allocate the Parser on the heap and return it
     * cast to the opaque public handle. */
    for (name, id) in &st.entry_states {
        writeln!(c, "{stem}_Parser *{stem}_parser_new_{name}_from_read_fn({stem}_ReadFn read_fn, void *ctx) {{").unwrap();
        writeln!(c, "  Parser *p = (Parser*)malloc(sizeof *p);").unwrap();
        writeln!(c, "  parser_init_from_read_fn(p, {id}, read_fn, ctx);").unwrap();
        writeln!(c, "  return ({stem}_Parser*)p;").unwrap();
        writeln!(c, "}}").unwrap();
        writeln!(
            c,
            "{stem}_Parser *{stem}_parser_new_{name}_from_string(const char *src, size_t len) {{"
        )
        .unwrap();
        writeln!(c, "  Parser *p = (Parser*)malloc(sizeof *p);").unwrap();
        writeln!(c, "  parser_init_from_string(p, {id}, src, len);").unwrap();
        writeln!(c, "  return ({stem}_Parser*)p;").unwrap();
        writeln!(c, "}}").unwrap();
        /* With-options variants: same construction, then copy the
         * caller's flags into the runtime parser struct. */
        writeln!(c, "{stem}_Parser *{stem}_parser_new_{name}_from_read_fn_with_options({stem}_ReadFn read_fn, void *ctx, {stem}_Options opts) {{").unwrap();
        writeln!(c, "  Parser *p = (Parser*)malloc(sizeof *p);").unwrap();
        writeln!(c, "  parser_init_from_read_fn(p, {id}, read_fn, ctx);").unwrap();
        writeln!(c, "  p->drop_skips = opts.drop_skips;").unwrap();
        writeln!(
            c,
            "  p->drop_unlabeled_tokens = opts.drop_unlabeled_tokens;"
        )
        .unwrap();
        writeln!(c, "  return ({stem}_Parser*)p;").unwrap();
        writeln!(c, "}}").unwrap();
        writeln!(c, "{stem}_Parser *{stem}_parser_new_{name}_from_string_with_options(const char *src, size_t len, {stem}_Options opts) {{").unwrap();
        writeln!(c, "  Parser *p = (Parser*)malloc(sizeof *p);").unwrap();
        writeln!(c, "  parser_init_from_string(p, {id}, src, len);").unwrap();
        writeln!(c, "  p->drop_skips = opts.drop_skips;").unwrap();
        writeln!(
            c,
            "  p->drop_unlabeled_tokens = opts.drop_unlabeled_tokens;"
        )
        .unwrap();
        writeln!(c, "  return ({stem}_Parser*)p;").unwrap();
        writeln!(c, "}}").unwrap();
    }
    writeln!(c).unwrap();

    writeln!(c, "int {stem}_next({stem}_Parser *p, {stem}_Event *out) {{").unwrap();
    writeln!(c, "  return parser_next((Parser*)p, (Event*)out);").unwrap();
    writeln!(c, "}}").unwrap();
    writeln!(c).unwrap();

    writeln!(c, "void {stem}_parser_free({stem}_Parser *p) {{").unwrap();
    writeln!(c, "  if (!p) return;").unwrap();
    writeln!(c, "  parser_destroy((Parser*)p);").unwrap();
    writeln!(c, "  free(p);").unwrap();
    writeln!(c, "}}").unwrap();
}
