use std::fmt::Write;
use std::path::PathBuf;

use crate::lowering::lexer_dfa::{DfaState, START};

use crate::codegen::EmittedFile;
use crate::lowering::{Body, DispatchLeaf, DispatchTree, Op, StateTable};

/// Per-backend arguments for the C# target.
#[derive(clap::Args, Clone, Debug, Default)]
pub struct Args {
    /// Namespace the generated `Grammar` class lives in. Used verbatim for
    /// the `namespace` declaration and as the on-disk directory name.
    /// Defaults to a PascalCase-d grammar name when `None`.
    #[arg(long = "namespace")]
    pub namespace: Option<String>,
}

pub fn emit(st: &StateTable, args: &Args) -> Vec<EmittedFile> {
    let ns = args
        .namespace
        .clone()
        .filter(|n| !n.is_empty())
        .unwrap_or_else(|| {
            if st.grammar_name.is_empty() {
                "Parser".to_string()
            } else {
                pascal_case(&st.grammar_name)
            }
        });
    let mut s = String::new();

    writeln!(&mut s, "// Generated by parsuna — do not edit by hand.").unwrap();
    writeln!(&mut s, "//").unwrap();
    writeln!(
        &mut s,
        "// Pull-based, recoverable parser. Call one of the static Grammar.ParseXxx"
    )
    .unwrap();
    writeln!(
        &mut s,
        "// entry points and iterate the returned Parser (or call NextEvent) to"
    )
    .unwrap();
    writeln!(
        &mut s,
        "// walk the parse as a flat Event stream. Requires the Parsuna.Runtime library."
    )
    .unwrap();
    writeln!(&mut s, "#nullable enable").unwrap();
    writeln!(&mut s, "using System;").unwrap();
    writeln!(&mut s, "using System.IO;").unwrap();
    writeln!(&mut s, "using System.Text;").unwrap();
    writeln!(&mut s, "using Parsuna.Runtime;").unwrap();
    writeln!(&mut s).unwrap();
    writeln!(&mut s, "namespace {};", ns).unwrap();
    writeln!(&mut s).unwrap();

    emit_constants(&mut s, st);
    emit_dfa(&mut s, st);
    emit_tables(&mut s, st);
    emit_grammar(&mut s, st);

    let file = PathBuf::from(format!("{}/Grammar.cs", ns));
    vec![EmittedFile {
        path: file,
        contents: s,
    }]
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn emit_constants(s: &mut String, st: &StateTable) {
    writeln!(
        s,
        "/// <summary>Token kinds this grammar can emit. <c>Eof</c> is the runtime"
    )
    .unwrap();
    writeln!(
        s,
        "/// end-of-input sentinel; the rest come from the grammar's <c>token</c>"
    )
    .unwrap();
    writeln!(
        s,
        "/// declarations. Lex failures (no DFA pattern matched) come through as"
    )
    .unwrap();
    writeln!(
        s,
        "/// <c>Token</c> instances with <c>Kind == Lexer.ErrorKind</c> (0xFFFF).</summary>"
    )
    .unwrap();
    writeln!(s, "public enum TokenKind : ushort {{").unwrap();
    writeln!(s, "    Eof = 0,").unwrap();
    for t in &st.tokens {
        writeln!(
            s,
            "    {} = {},",
            pascal_case(&t.name.to_lowercase()),
            t.kind
        )
        .unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "public static class TokenKindEx {{").unwrap();
    writeln!(
        s,
        "    public static string DisplayName(this TokenKind k) => k switch {{"
    )
    .unwrap();
    writeln!(s, "        TokenKind.Eof => \"EOF\",").unwrap();
    for t in &st.tokens {
        writeln!(
            s,
            "        TokenKind.{} => \"{}\",",
            pascal_case(&t.name.to_lowercase()),
            t.name
        )
        .unwrap();
    }
    writeln!(s, "        _ => \"?\",").unwrap();
    writeln!(s, "    }};").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    writeln!(
        s,
        "/// <summary>One variant per non-fragment grammar rule. Attached to enter/exit"
    )
    .unwrap();
    writeln!(
        s,
        "/// events so consumers can identify the subtree each pair delimits.</summary>"
    )
    .unwrap();
    writeln!(s, "public enum RuleKind : ushort {{").unwrap();
    for (i, n) in st.rule_kinds.iter().enumerate() {
        writeln!(s, "    {} = {},", pascal_case(n), i).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "public static class RuleKindEx {{").unwrap();
    writeln!(
        s,
        "    public static string DisplayName(this RuleKind k) => k switch {{"
    )
    .unwrap();
    for n in &st.rule_kinds {
        writeln!(s, "        RuleKind.{} => \"{}\",", pascal_case(n), n).unwrap();
    }
    writeln!(s, "        _ => \"?\",").unwrap();
    writeln!(s, "    }};").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn token_ushort(st: &StateTable, kind: u16) -> String {
    if kind == 0 {
        return "(ushort)TokenKind.Eof".to_string();
    }
    match st.tokens.iter().find(|t| t.kind == kind) {
        Some(t) => format!(
            "(ushort)TokenKind.{}",
            pascal_case(&t.name.to_lowercase())
        ),
        None => panic!("unknown token id {} while emitting C# backend", kind),
    }
}

fn rule_id(st: &StateTable, kind: u16) -> String {
    let name = st
        .rule_kinds
        .get(kind as usize)
        .unwrap_or_else(|| panic!("unknown rule kind id {} while emitting C# backend", kind));
    format!("(int)RuleKind.{}", pascal_case(name))
}

fn emit_dfa(s: &mut String, st: &StateTable) {
    let dfa = &st.lexer_dfa;

    writeln!(
        s,
        "/// <summary>Compiled lexer DFA: one switch arm per DFA state.</summary>"
    )
    .unwrap();
    writeln!(s, "internal static class DfaImpl {{").unwrap();
    writeln!(
        s,
        "    public static void LongestMatch(byte[] buf, int start, int bufLen, int[] output) {{"
    )
    .unwrap();
    writeln!(s, "        int pos = start;").unwrap();
    writeln!(s, "        int bestLen = 0;").unwrap();
    writeln!(s, "        int bestKind = Lexer.ErrorKind;").unwrap();
    writeln!(s, "        int state = {};", START).unwrap();
    writeln!(s, "        while (true) {{").unwrap();
    writeln!(s, "            switch (state) {{").unwrap();
    for ds in dfa { emit_dfa_state_arm(s, st, ds); }
    writeln!(s, "                default: goto done;").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "        done:").unwrap();
    writeln!(s, "        output[0] = bestLen;").unwrap();
    writeln!(s, "        output[1] = bestKind;").unwrap();
    writeln!(s, "        output[2] = pos - start;").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(
        s,
        "    public static readonly DfaMatcher Matcher = LongestMatch;"
    )
    .unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_dfa_state_arm(
    s: &mut String,
    st: &StateTable,
        ds: &DfaState,
) {
    if ds.arms.is_empty() {
        writeln!(s, "                case {}: goto done;", ds.id).unwrap();
        return;
    }
    writeln!(s, "                case {}: {{", ds.id).unwrap();
    if !ds.self_loop.is_empty() {
        // Self-loop scan-skip prologue. RyuJIT recognises this loop
        // shape and lifts it to vectorised byte tests on x86/Arm.
        writeln!(s, "                    while (pos < bufLen) {{").unwrap();
        writeln!(s, "                        int b = buf[pos];").unwrap();
        writeln!(
            s,
            "                        if (!({})) break;",
            byte_cond(&ds.self_loop)
        )
        .unwrap();
        writeln!(s, "                        pos++;").unwrap();
        writeln!(s, "                    }}").unwrap();
        if let Some(kind) = ds.accept {
            writeln!(s, "                    bestLen = pos - start;").unwrap();
            writeln!(
                s,
                "                    bestKind = {};",
                token_ushort(st, kind)
            )
            .unwrap();
        }
    }
    writeln!(s, "                    if (pos >= bufLen) goto done;").unwrap();
    writeln!(s, "                    int b = buf[pos];").unwrap();
    let mut first = true;
    for arm in &ds.arms {
        let cond = byte_cond(&arm.ranges);
        let kw = if first { "if" } else { "else if" };
        first = false;
        write!(
            s,
            "                    {} ({}) {{ pos++; state = {};",
            kw, cond, arm.target
        )
        .unwrap();
        if let Some(kind) = arm.target_accept {
            write!(
                s,
                " bestLen = pos - start; bestKind = {};",
                token_ushort(st, kind)
            )
            .unwrap();
        }
        writeln!(s, " }}").unwrap();
    }
    writeln!(s, "                    else goto done;").unwrap();
    writeln!(s, "                    break;").unwrap();
    writeln!(s, "                }}").unwrap();
}


fn byte_cond(ranges: &[(u8, u8)]) -> String {
    ranges
        .iter()
        .map(|(lo, hi)| {
            if lo == hi {
                format!("b == 0x{:02x}", lo)
            } else {
                format!("(b >= 0x{:02x} && b <= 0x{:02x})", lo, hi)
            }
        })
        .collect::<Vec<_>>()
        .join(" || ")
}

fn emit_tables(s: &mut String, st: &StateTable) {
    writeln!(s, "internal static class Tables {{").unwrap();
    writeln!(s, "    public const int K = {};", st.k).unwrap();

    for f in &st.first_sets {
        if !f.has_references {
            continue;
        }
        let seqs: Vec<String> = f
            .seqs
            .iter()
            .map(|seq| {
                format!(
                    "new ushort[] {{ {} }}",
                    seq.iter()
                        .map(|t| token_ushort(st, *t))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            })
            .collect();
        writeln!(
            s,
            "    public static readonly ushort[][] First{} = new ushort[][] {{ {} }};",
            f.id,
            seqs.join(", ")
        )
        .unwrap();
    }
    for f in &st.sync_sets {
        writeln!(
            s,
            "    public static readonly ushort[] Sync{} = new ushort[] {{ {} }};",
            f.id,
            f.kinds
                .iter()
                .map(|t| token_ushort(st, *t))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }

    let skips: Vec<String> = st
        .tokens
        .iter()
        .filter(|t| t.skip)
        .map(|t| format!("k == {}", token_ushort(st, t.kind)))
        .collect();
    let skip_body = if skips.is_empty() {
        "false".to_string()
    } else {
        skips.join(" || ")
    };
    writeln!(
        s,
        "    public static bool IsSkip(ushort k) => {};",
        skip_body
    )
    .unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_grammar(s: &mut String, st: &StateTable) {
    writeln!(s, "/// <summary>Grammar-specific entry points. Thin wrapper around Parsuna.Runtime.Parser.</summary>").unwrap();
    writeln!(s, "public static class Grammar {{").unwrap();

    for (name, id) in &st.entry_states {
        writeln!(
            s,
            "    private const int Entry{} = {};",
            pascal_case(name),
            id
        )
        .unwrap();
    }
    writeln!(s).unwrap();
    writeln!(
        s,
        "    private static readonly ParserConfig Config = new ParserConfig("
    )
    .unwrap();
    writeln!(s, "        Tables.K,").unwrap();
    writeln!(s, "        Tables.IsSkip,").unwrap();
    writeln!(s, "        Drive);").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "    private static Parser FromStream(Stream stream, int entry) =>").unwrap();
    writeln!(
        s,
        "        new Parser(new Lexer(stream, DfaImpl.Matcher), entry, Config);"
    )
    .unwrap();
    writeln!(s).unwrap();

    for (name, _) in &st.entry_states {
        writeln!(
            s,
            "    /// <summary>Parse the <c>{name}</c> rule from a byte <c>Stream</c>.</summary>",
        )
        .unwrap();
        writeln!(
            s,
            "    public static Parser Parse{cap}(Stream stream) => FromStream(stream, Entry{cap});",
            cap = pascal_case(name)
        )
        .unwrap();
        writeln!(
            s,
            "    /// <summary>Parse the <c>{name}</c> rule from a UTF-8 string.</summary>",
        )
        .unwrap();
        writeln!(
            s,
            "    public static Parser Parse{cap}(string src) => Parse{cap}(new MemoryStream(Encoding.UTF8.GetBytes(src)));",
            cap = pascal_case(name)
        ).unwrap();
        writeln!(s).unwrap();
    }

    emit_drive(s, st);

    writeln!(s, "}}").unwrap();
}

fn emit_drive(s: &mut String, st: &StateTable) {
    writeln!(s, "    private static void Drive(Parser p) {{").unwrap();
    writeln!(s, "        int cur = p.State();").unwrap();
    writeln!(
        s,
        "        while (p.QueueIsEmpty() && cur != Parser.Terminated) {{"
    )
    .unwrap();
    writeln!(s, "            switch (cur) {{").unwrap();
    for state in st.states.values() {
        writeln!(
            s,
            "                case {}: {{ // {}",
            state.id, state.label
        )
        .unwrap();
        for op in &state.ops {
            emit_op(s, st, op);
        }
        writeln!(s, "                    break;").unwrap();
        writeln!(s, "                }}").unwrap();
    }
    writeln!(
        s,
        "                default: throw new InvalidOperationException($\"unknown state {{cur}}\");"
    )
    .unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "        p.SetState(cur);").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s).unwrap();
}

fn emit_op(s: &mut String, st: &StateTable, op: &Op) {
    match op {
        Op::Enter(k) => {
            writeln!(s, "                    p.Enter({});", rule_id(st, *k)).unwrap();
        }
        Op::Exit(k) => {
            writeln!(s, "                    p.Exit({});", rule_id(st, *k)).unwrap();
        }
        Op::Expect {
            kind,
            token_name,
            sync,
        } => {
            writeln!(
                s,
                "                    p.TryConsume({}, Tables.Sync{}, \"{}\");",
                token_ushort(st, *kind),
                sync,
                token_name
            )
            .unwrap();
        }
        Op::PushRet(r) => {
            writeln!(s, "                    p.PushRet({});", r).unwrap();
        }
        Op::Jump(n) => {
            writeln!(s, "                    cur = {};", n).unwrap();
        }
        Op::Ret => {
            writeln!(s, "                    cur = p.PopRet();").unwrap();
        }
        Op::Star { first, body, cont, head } => {
            writeln!(s, "                    if (p.MatchesFirst(Tables.First{})) {{", first).unwrap();
            writeln!(s, "                        p.PushRet({});", head).unwrap();
            emit_body(s, st, body, "                        ");
            writeln!(s, "                    }}").unwrap();
            match cont {
                Some(n) => writeln!(s, "                    else cur = {};", n).unwrap(),
                None => writeln!(s, "                    else cur = p.PopRet();").unwrap(),
            }
        }
        Op::Opt { first, body, cont } => {
            writeln!(s, "                    if (p.MatchesFirst(Tables.First{})) {{", first).unwrap();
            if let Some(n) = cont {
                writeln!(s, "                        p.PushRet({});", n).unwrap();
            }
            emit_body(s, st, body, "                        ");
            writeln!(s, "                    }}").unwrap();
            match cont {
                Some(n) => writeln!(s, "                    else cur = {};", n).unwrap(),
                None => writeln!(s, "                    else cur = p.PopRet();").unwrap(),
            }
        }
        Op::Dispatch { tree, sync, cont } => {
            emit_dispatch_tree(s, st, tree, *sync, *cont, "                    ");
        }
    }
}

fn emit_body(s: &mut String, st: &StateTable, body: &Body, ind: &str) {
    match body {
        Body::State(t) => writeln!(s, "{}cur = {};", ind, t).unwrap(),
        Body::Inline(ops) => {
            for op in ops {
                emit_op(s, st, op);
            }
        }
    }
}

fn emit_dispatch_tree(
    s: &mut String,
    st: &StateTable,
    tree: &DispatchTree,
    sync: u32,
    cont: Option<u32>,
    ind: &str,
) {
    match tree {
        DispatchTree::Leaf(leaf) => {
            if leaf_target_inlined(leaf) {
                writeln!(s, "{}{{", ind).unwrap();
                emit_dispatch_leaf_block(s, st, leaf, sync, cont, &format!("{}  ", ind));
                writeln!(s, "{}}}", ind).unwrap();
            } else {
                write!(s, "{}{{ ", ind).unwrap();
                emit_leaf_inline(s, leaf, sync, cont);
                writeln!(s, "}}").unwrap();
            }
        }
        DispatchTree::Switch {
            depth,
            arms,
            default,
        } => {
            writeln!(s, "{}switch (p.Look({}).Kind) {{", ind, depth).unwrap();
            let inner = format!("{}  ", ind);
            for (kind, sub) in arms {
                let lit = format!("(ushort){}", *kind);
                match sub {
                    DispatchTree::Leaf(leaf) if !leaf_target_inlined(leaf) => {
                        write!(s, "{}case {}: {{ ", inner, lit).unwrap();
                        emit_leaf_inline(s, leaf, sync, cont);
                        writeln!(s, "break; }}").unwrap();
                    }
                    _ => {
                        writeln!(s, "{}case {}: {{", inner, lit).unwrap();
                        emit_dispatch_tree(s, st, sub, sync, cont, &format!("{}  ", inner));
                        writeln!(s, "{}  break;", inner).unwrap();
                        writeln!(s, "{}}}", inner).unwrap();
                    }
                }
            }
            if leaf_target_inlined(default) {
                writeln!(s, "{}default: {{", inner).unwrap();
                emit_dispatch_leaf_block(s, st, default, sync, cont, &format!("{}  ", inner));
                writeln!(s, "{}  break;", inner).unwrap();
                writeln!(s, "{}}}", inner).unwrap();
            } else {
                write!(s, "{}default: {{ ", inner).unwrap();
                emit_leaf_inline(s, default, sync, cont);
                writeln!(s, "break; }}").unwrap();
            }
            writeln!(s, "{}}}", ind).unwrap();
        }
    }
}

fn leaf_target_inlined(leaf: &DispatchLeaf) -> bool {
    matches!(leaf, DispatchLeaf::Arm(Body::Inline(_)))
}

fn emit_dispatch_leaf_block(
    s: &mut String,
    st: &StateTable,
    leaf: &DispatchLeaf,
    sync: u32,
    cont: Option<u32>,
    ind: &str,
) {
    match (leaf, cont) {
        (DispatchLeaf::Arm(b), Some(n)) => {
            writeln!(s, "{}p.PushRet({});", ind, n).unwrap();
            emit_body(s, st, b, ind);
        }
        (DispatchLeaf::Arm(b), None) => emit_body(s, st, b, ind),
        (DispatchLeaf::Fallthrough, Some(n)) => writeln!(s, "{}cur = {};", ind, n).unwrap(),
        (DispatchLeaf::Fallthrough, None) => writeln!(s, "{}cur = p.PopRet();", ind).unwrap(),
        (DispatchLeaf::Error, Some(n)) => {
            writeln!(s, "{}cur = {};", ind, n).unwrap();
            writeln!(s, "{}p.ErrorHere(\"unexpected token\");", ind).unwrap();
            writeln!(s, "{}p.RecoverTo(Tables.Sync{});", ind, sync).unwrap();
        }
        (DispatchLeaf::Error, None) => {
            writeln!(s, "{}p.ErrorHere(\"unexpected token\");", ind).unwrap();
            writeln!(s, "{}p.RecoverTo(Tables.Sync{});", ind, sync).unwrap();
            writeln!(s, "{}cur = p.PopRet();", ind).unwrap();
        }
    }
}

fn emit_leaf_inline(s: &mut String, leaf: &DispatchLeaf, sync: u32, cont: Option<u32>) {
    match (leaf, cont) {
        (DispatchLeaf::Arm(Body::State(t)), Some(n)) => write!(s, "p.PushRet({}); cur = {}; ", n, t).unwrap(),
        (DispatchLeaf::Arm(Body::State(t)), None) => write!(s, "cur = {}; ", t).unwrap(),
        (DispatchLeaf::Arm(Body::Inline(_)), _) => unreachable!("inlined arm in inline-emit path"),
        (DispatchLeaf::Fallthrough, Some(n)) => write!(s, "cur = {}; ", n).unwrap(),
        (DispatchLeaf::Fallthrough, None) => write!(s, "cur = p.PopRet(); ").unwrap(),
        (DispatchLeaf::Error, Some(n)) => write!(
            s,
            "cur = {}; p.ErrorHere(\"unexpected token\"); p.RecoverTo(Tables.Sync{}); ",
            n, sync
        )
        .unwrap(),
        (DispatchLeaf::Error, None) => write!(
            s,
            "p.ErrorHere(\"unexpected token\"); p.RecoverTo(Tables.Sync{}); cur = p.PopRet(); ",
            sync
        )
        .unwrap(),
    }
}
