use std::fmt::Write;
use std::path::PathBuf;

use crate::lowering::lexer_dfa::{DfaState, START};

use crate::codegen::EmittedFile;
use crate::lowering::{Body, DispatchLeaf, DispatchTree, Instr, StateTable, Tail};

/// Per-backend arguments for the C# target.
#[derive(clap::Args, Clone, Debug, Default)]
pub struct Args {
    /// Namespace the generated `Grammar` class lives in. Used verbatim for
    /// the `namespace` declaration and as the on-disk directory name.
    /// Defaults to a PascalCase-d grammar name when `None`.
    #[arg(long = "namespace")]
    pub namespace: Option<String>,
}

pub fn emit(st: &StateTable, args: &Args) -> Vec<EmittedFile> {
    let ns = args
        .namespace
        .clone()
        .filter(|n| !n.is_empty())
        .unwrap_or_else(|| {
            if st.grammar_name.is_empty() {
                "Parser".to_string()
            } else {
                pascal_case(&st.grammar_name)
            }
        });
    let mut s = String::new();

    writeln!(&mut s, "// Generated by parsuna — do not edit by hand.").unwrap();
    writeln!(&mut s, "//").unwrap();
    writeln!(
        &mut s,
        "// Pull-based, recoverable parser. Call one of the static Grammar.ParseXxx"
    )
    .unwrap();
    writeln!(
        &mut s,
        "// entry points and iterate the returned Parser (or call NextEvent) to"
    )
    .unwrap();
    writeln!(
        &mut s,
        "// walk the parse as a flat Event stream. Requires the Parsuna.Runtime library."
    )
    .unwrap();
    writeln!(&mut s, "#nullable enable").unwrap();
    writeln!(&mut s, "using System;").unwrap();
    writeln!(&mut s, "using System.IO;").unwrap();
    writeln!(&mut s, "using System.Text;").unwrap();
    writeln!(&mut s, "using Parsuna.Runtime;").unwrap();
    writeln!(&mut s).unwrap();
    writeln!(&mut s, "namespace {};", ns).unwrap();
    writeln!(&mut s).unwrap();

    emit_constants(&mut s, st);
    emit_dfa(&mut s, st);
    emit_tables(&mut s, st);
    emit_grammar(&mut s, st);

    let file = PathBuf::from(format!("{}/Grammar.cs", ns));
    vec![EmittedFile {
        path: file,
        contents: s,
    }]
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn emit_constants(s: &mut String, st: &StateTable) {
    writeln!(
        s,
        "/// <summary>Token kinds this grammar can emit. <c>Eof</c> is the runtime"
    )
    .unwrap();
    writeln!(
        s,
        "/// end-of-input sentinel; the rest come from the grammar's <c>token</c>"
    )
    .unwrap();
    writeln!(
        s,
        "/// declarations. Lex failures (no DFA pattern matched) come through as"
    )
    .unwrap();
    writeln!(
        s,
        "/// <c>Token</c> instances with <c>Kind == Lexer.ErrorKind</c> (0xFFFF).</summary>"
    )
    .unwrap();
    writeln!(s, "public enum TokenKind : ushort {{").unwrap();
    writeln!(s, "    Eof = 0,").unwrap();
    for t in &st.tokens {
        writeln!(
            s,
            "    {} = {},",
            pascal_case(&t.name.to_lowercase()),
            t.kind
        )
        .unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "public static class TokenKindEx {{").unwrap();
    writeln!(
        s,
        "    public static string DisplayName(this TokenKind k) => k switch {{"
    )
    .unwrap();
    writeln!(s, "        TokenKind.Eof => \"EOF\",").unwrap();
    for t in &st.tokens {
        writeln!(
            s,
            "        TokenKind.{} => \"{}\",",
            pascal_case(&t.name.to_lowercase()),
            t.name
        )
        .unwrap();
    }
    writeln!(s, "        _ => \"?\",").unwrap();
    writeln!(s, "    }};").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    writeln!(
        s,
        "/// <summary>One variant per non-fragment grammar rule. Attached to enter/exit"
    )
    .unwrap();
    writeln!(
        s,
        "/// events so consumers can identify the subtree each pair delimits.</summary>"
    )
    .unwrap();
    writeln!(s, "public enum RuleKind : ushort {{").unwrap();
    for (i, n) in st.rule_kinds.iter().enumerate() {
        writeln!(s, "    {} = {},", pascal_case(n), i).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "public static class RuleKindEx {{").unwrap();
    writeln!(
        s,
        "    public static string DisplayName(this RuleKind k) => k switch {{"
    )
    .unwrap();
    for n in &st.rule_kinds {
        writeln!(s, "        RuleKind.{} => \"{}\",", pascal_case(n), n).unwrap();
    }
    writeln!(s, "        _ => \"?\",").unwrap();
    writeln!(s, "    }};").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    // ---- LabelKind ------------------------------------------------------
    writeln!(
        s,
        "/// <summary>One variant per distinct grammar label (<c>name:NAME</c> form)."
    )
    .unwrap();
    writeln!(s, "/// <c>Token.Label</c> stores the matching variant's underlying").unwrap();
    writeln!(
        s,
        "/// <c>ushort</c> id (or <c>0</c> for unlabeled positions); compare with"
    )
    .unwrap();
    writeln!(
        s,
        "/// <c>tok.Label == (ushort)LabelKind.Foo</c> to dispatch on the position"
    )
    .unwrap();
    writeln!(s, "/// name without strings.</summary>").unwrap();
    writeln!(s, "public enum LabelKind : ushort {{").unwrap();
    if st.labels.is_empty() {
        writeln!(s, "    None = 0,").unwrap();
    } else {
        for (i, n) in st.labels.iter().enumerate() {
            writeln!(s, "    {} = {},", pascal_case(n), i + 1).unwrap();
        }
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "public static class LabelKindEx {{").unwrap();
    writeln!(
        s,
        "    public static string DisplayName(this LabelKind k) => k switch {{"
    )
    .unwrap();
    for n in &st.labels {
        writeln!(s, "        LabelKind.{} => \"{}\",", pascal_case(n), n).unwrap();
    }
    writeln!(s, "        _ => \"?\",").unwrap();
    writeln!(s, "    }};").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn token_ushort(st: &StateTable, kind: u16) -> String {
    if kind == 0 {
        return "(ushort)TokenKind.Eof".to_string();
    }
    match st.tokens.iter().find(|t| t.kind == kind) {
        Some(t) => format!(
            "(ushort)TokenKind.{}",
            pascal_case(&t.name.to_lowercase())
        ),
        None => panic!("unknown token id {} while emitting C# backend", kind),
    }
}

fn rule_id(st: &StateTable, kind: u16) -> String {
    let name = st
        .rule_kinds
        .get(kind as usize)
        .unwrap_or_else(|| panic!("unknown rule kind id {} while emitting C# backend", kind));
    format!("(int)RuleKind.{}", pascal_case(name))
}

fn emit_dfa(s: &mut String, st: &StateTable) {
    writeln!(
        s,
        "/// <summary>Compiled lexer DFA: one helper per declared lexer mode.</summary>"
    )
    .unwrap();
    writeln!(s, "internal static class DfaImpl {{").unwrap();

    /* Mode-dispatch entry point. Single-mode grammars collapse to a
     * direct call so the dispatcher inlines away. */
    writeln!(
        s,
        "    public static void LongestMatch(byte[] buf, int start, int bufLen, int mode, int[] output) {{"
    )
    .unwrap();
    if st.modes.len() == 1 {
        writeln!(s, "        _ = mode;").unwrap();
        writeln!(s, "        LongestMatchMode0(buf, start, bufLen, output);").unwrap();
    } else {
        writeln!(s, "        switch (mode) {{").unwrap();
        for m in &st.modes {
            writeln!(
                s,
                "            case {}: LongestMatchMode{}(buf, start, bufLen, output); return;",
                m.id, m.id
            )
            .unwrap();
        }
        writeln!(
            s,
            "            default: output[0] = 0; output[1] = Lexer.ErrorKind; output[2] = 0; return;"
        )
        .unwrap();
        writeln!(s, "        }}").unwrap();
    }
    writeln!(s, "    }}").unwrap();
    writeln!(s).unwrap();

    for m in &st.modes {
        writeln!(
            s,
            "    /// <summary>Longest-match helper for lexer mode `{}` (id {}).</summary>",
            m.name, m.id
        )
        .unwrap();
        writeln!(
            s,
            "    private static void LongestMatchMode{}(byte[] buf, int start, int bufLen, int[] output) {{",
            m.id
        )
        .unwrap();
        writeln!(s, "        int pos = start;").unwrap();
        writeln!(s, "        int bestLen = 0;").unwrap();
        writeln!(s, "        int bestKind = Lexer.ErrorKind;").unwrap();
        writeln!(s, "        int state = {};", START).unwrap();
        writeln!(s, "        while (true) {{").unwrap();
        writeln!(s, "            switch (state) {{").unwrap();
        for ds in &m.dfa { emit_dfa_state_arm(s, st, ds); }
        writeln!(s, "                default: goto done;").unwrap();
        writeln!(s, "            }}").unwrap();
        writeln!(s, "        }}").unwrap();
        writeln!(s, "        done:").unwrap();
        writeln!(s, "        output[0] = bestLen;").unwrap();
        writeln!(s, "        output[1] = bestKind;").unwrap();
        writeln!(s, "        output[2] = pos - start;").unwrap();
        writeln!(s, "    }}").unwrap();
        writeln!(s).unwrap();
    }

    writeln!(
        s,
        "    public static readonly DfaMatcher Matcher = LongestMatch;"
    )
    .unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_dfa_state_arm(
    s: &mut String,
    st: &StateTable,
        ds: &DfaState,
) {
    if ds.arms.is_empty() {
        writeln!(s, "                case {}: goto done;", ds.id).unwrap();
        return;
    }
    writeln!(s, "                case {}: {{", ds.id).unwrap();
    let self_loop = ds.self_loop_ranges();
    if !self_loop.is_empty() {
        // Self-loop scan-skip prologue. RyuJIT recognizes this loop
        // shape and lifts it to vectorized byte tests on x86/Arm.
        writeln!(s, "                    while (pos < bufLen) {{").unwrap();
        writeln!(s, "                        int b = buf[pos];").unwrap();
        writeln!(
            s,
            "                        if (!({})) break;",
            byte_cond(self_loop)
        )
        .unwrap();
        writeln!(s, "                        pos++;").unwrap();
        writeln!(s, "                    }}").unwrap();
        if let Some(kind) = ds.accept {
            writeln!(s, "                    bestLen = pos - start;").unwrap();
            writeln!(
                s,
                "                    bestKind = {};",
                token_ushort(st, kind)
            )
            .unwrap();
        }
    }
    writeln!(s, "                    if (pos >= bufLen) goto done;").unwrap();
    writeln!(s, "                    int b = buf[pos];").unwrap();
    let mut first = true;
    for arm in &ds.arms {
        let cond = byte_cond(&arm.ranges);
        let kw = if first { "if" } else { "else if" };
        first = false;
        write!(
            s,
            "                    {} ({}) {{ pos++; state = {};",
            kw, cond, arm.target
        )
        .unwrap();
        if let Some(kind) = arm.target_accept {
            write!(
                s,
                " bestLen = pos - start; bestKind = {};",
                token_ushort(st, kind)
            )
            .unwrap();
        }
        writeln!(s, " }}").unwrap();
    }
    writeln!(s, "                    else goto done;").unwrap();
    writeln!(s, "                    break;").unwrap();
    writeln!(s, "                }}").unwrap();
}


fn byte_cond(ranges: &[(u8, u8)]) -> String {
    ranges
        .iter()
        .map(|(lo, hi)| {
            if lo == hi {
                format!("b == 0x{:02x}", lo)
            } else {
                format!("(b >= 0x{:02x} && b <= 0x{:02x})", lo, hi)
            }
        })
        .collect::<Vec<_>>()
        .join(" || ")
}

fn emit_tables(s: &mut String, st: &StateTable) {
    writeln!(s, "internal static class Tables {{").unwrap();
    writeln!(s, "    public const int K = {};", st.k).unwrap();

    for f in &st.first_sets {
        if !f.has_references {
            continue;
        }
        let seqs: Vec<String> = f
            .seqs
            .iter()
            .map(|seq| {
                format!(
                    "new ushort[] {{ {} }}",
                    seq.iter()
                        .map(|t| token_ushort(st, *t))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            })
            .collect();
        writeln!(
            s,
            "    public static readonly ushort[][] First{} = new ushort[][] {{ {} }};",
            f.id,
            seqs.join(", ")
        )
        .unwrap();
    }
    for f in &st.sync_sets {
        writeln!(
            s,
            "    public static readonly ushort[] Sync{} = new ushort[] {{ {} }};",
            f.id,
            f.kinds
                .iter()
                .map(|t| token_ushort(st, *t))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }

    let skips: Vec<String> = st
        .tokens
        .iter()
        .filter(|t| t.skip)
        .map(|t| format!("k == {}", token_ushort(st, t.kind)))
        .collect();
    let has_skips = !skips.is_empty();
    let skip_body = if skips.is_empty() {
        "false".to_string()
    } else {
        skips.join(" || ")
    };
    writeln!(
        s,
        "    /// <summary>True iff this grammar declares any tokens with a `-> skip` action.</summary>"
    )
    .unwrap();
    writeln!(s, "    public const bool HasSkips = {};", has_skips).unwrap();
    writeln!(
        s,
        "    public static bool IsSkip(ushort k) => {};",
        skip_body
    )
    .unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_apply_actions(s: &mut String, st: &StateTable) {
    use crate::lowering::ModeActionInfo;

    let action_tokens: Vec<&crate::lowering::TokenInfo> = st
        .tokens
        .iter()
        .filter(|t| !t.mode_actions.is_empty())
        .collect();

    writeln!(s, "    /// <summary>Apply per-token mode-stack actions to <paramref name=\"lex\"/>. Generated as a switch over token kinds; tokens without `-> push/pop` fall through.</summary>").unwrap();
    writeln!(
        s,
        "    private static void ApplyActions(ushort kind, Lexer lex) {{"
    )
    .unwrap();
    if action_tokens.is_empty() {
        writeln!(s, "        _ = kind; _ = lex;").unwrap();
    } else {
        writeln!(s, "        switch (kind) {{").unwrap();
        for t in &action_tokens {
            writeln!(s, "            case {}:", token_ushort(st, t.kind)).unwrap();
            for action in &t.mode_actions {
                match action {
                    ModeActionInfo::Push(id) => {
                        writeln!(s, "                lex.PushMode({});", id).unwrap();
                    }
                    ModeActionInfo::Pop => {
                        writeln!(s, "                lex.PopMode();").unwrap();
                    }
                }
            }
            writeln!(s, "                break;").unwrap();
        }
        writeln!(s, "            default: break;").unwrap();
        writeln!(s, "        }}").unwrap();
    }
    writeln!(s, "    }}").unwrap();
    writeln!(s).unwrap();
}

fn emit_grammar(s: &mut String, st: &StateTable) {
    writeln!(s, "/// <summary>Grammar-specific entry points. Thin wrapper around Parsuna.Runtime.Parser.</summary>").unwrap();
    writeln!(s, "public static class Grammar {{").unwrap();

    for (name, id) in &st.entry_states {
        writeln!(
            s,
            "    private const int Entry{} = {};",
            pascal_case(name),
            id
        )
        .unwrap();
    }
    writeln!(s).unwrap();
    emit_apply_actions(s, st);
    writeln!(
        s,
        "    private static readonly ParserConfig Config = new ParserConfig("
    )
    .unwrap();
    writeln!(s, "        Tables.K,").unwrap();
    writeln!(s, "        Tables.IsSkip,").unwrap();
    writeln!(s, "        Tables.HasSkips,").unwrap();
    writeln!(s, "        Step,").unwrap();
    writeln!(s, "        ApplyActions);").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "    private static Parser FromStream(Stream stream, int entry, ParserOptions? options = null) =>").unwrap();
    writeln!(
        s,
        "        new Parser(new Lexer(stream, DfaImpl.Matcher), entry, Config, options ?? new ParserOptions());"
    )
    .unwrap();
    writeln!(s).unwrap();

    for (name, _) in &st.entry_states {
        let cap = pascal_case(name);

        writeln!(
            s,
            "    /// <summary>Parse the <c>{name}</c> rule from a byte <c>Stream</c>. Pass a <see cref=\"ParserOptions\"/> to silently consume skip tokens (<c>DropSkips</c>) or unlabeled tokens (<c>DropUnlabeledTokens</c>).</summary>",
        )
        .unwrap();
        writeln!(
            s,
            "    public static Parser Parse{cap}(Stream stream, ParserOptions? options = null) => FromStream(stream, Entry{cap}, options);"
        )
        .unwrap();
        writeln!(
            s,
            "    /// <summary>Parse the <c>{name}</c> rule from a UTF-8 string.</summary>",
        )
        .unwrap();
        writeln!(
            s,
            "    public static Parser Parse{cap}(string src, ParserOptions? options = null) => Parse{cap}(new MemoryStream(Encoding.UTF8.GetBytes(src)), options);"
        )
        .unwrap();
        writeln!(s).unwrap();
    }

    emit_drive(s, st);

    writeln!(s, "}}").unwrap();
}

fn emit_drive(s: &mut String, st: &StateTable) {
    writeln!(s, "    private static Event? Step(Cursor p) {{").unwrap();
    writeln!(s, "        int cur = p.State();").unwrap();
    writeln!(s, "        Event? @event = null;").unwrap();
    writeln!(s, "        switch (cur) {{").unwrap();
    for state in st.states.values() {
        writeln!(
            s,
            "            case {}: {{ // {}",
            state.id, state.label
        )
        .unwrap();
        emit_body(s, st, &state.body, "                ");
        writeln!(s, "                break;").unwrap();
        writeln!(s, "            }}").unwrap();
    }
    writeln!(
        s,
        "            default: throw new InvalidOperationException($\"unknown state {{cur}}\");"
    )
    .unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "        p.SetState(cur);").unwrap();
    writeln!(s, "        return @event;").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s).unwrap();
}

fn emit_instr(s: &mut String, st: &StateTable, op: &Instr, ind: &str) {
    match op {
        Instr::Enter(k) => {
            writeln!(s, "{}@event = p.Enter({});", ind, rule_id(st, *k)).unwrap();
        }
        Instr::Exit(k) => {
            writeln!(s, "{}@event = p.Exit({});", ind, rule_id(st, *k)).unwrap();
        }
        Instr::Expect {
            kind,
            token_name,
            sync,
            label,
        } => {
            let label_arg = match label {
                Some(id) => format!(
                    "(ushort)LabelKind.{}",
                    pascal_case(&st.labels[(*id as usize) - 1])
                ),
                None => "0".to_string(),
            };
            writeln!(
                s,
                "{}@event = p.TryConsumeLabeled({}, Tables.Sync{}, \"{}\", {});",
                ind,
                token_ushort(st, *kind),
                sync,
                token_name,
                label_arg,
            )
            .unwrap();
        }
        Instr::PushRet(r) => {
            writeln!(s, "{}p.PushRet({});", ind, r).unwrap();
        }
    }
}

fn emit_tail(s: &mut String, st: &StateTable, tail: &Tail, ind: &str) {
    match tail {
        Tail::Jump(n) => {
            writeln!(s, "{}cur = {};", ind, n).unwrap();
        }
        Tail::Ret => {
            writeln!(s, "{}cur = p.PopRet();", ind).unwrap();
        }
        Tail::Star { first, body, cont, head } => {
            let inner = format!("{}    ", ind);
            writeln!(s, "{}if (p.MatchesFirst(Tables.First{})) {{", ind, first).unwrap();
            writeln!(s, "{}p.PushRet({});", inner, head).unwrap();
            emit_body(s, st, body, &inner);
            writeln!(s, "{}}}", ind).unwrap();
            match cont {
                Some(n) => writeln!(s, "{}else cur = {};", ind, n).unwrap(),
                None => writeln!(s, "{}else cur = p.PopRet();", ind).unwrap(),
            }
        }
        Tail::Opt { first, body, cont } => {
            let inner = format!("{}    ", ind);
            writeln!(s, "{}if (p.MatchesFirst(Tables.First{})) {{", ind, first).unwrap();
            if let Some(n) = cont {
                writeln!(s, "{}p.PushRet({});", inner, n).unwrap();
            }
            emit_body(s, st, body, &inner);
            writeln!(s, "{}}}", ind).unwrap();
            match cont {
                Some(n) => writeln!(s, "{}else cur = {};", ind, n).unwrap(),
                None => writeln!(s, "{}else cur = p.PopRet();", ind).unwrap(),
            }
        }
        Tail::Dispatch { tree, sync, cont } => {
            emit_dispatch_tree(s, st, tree, *sync, *cont, ind);
        }
    }
}

fn emit_body(s: &mut String, st: &StateTable, body: &Body, ind: &str) {
    for op in &body.instrs {
        emit_instr(s, st, op, ind);
    }
    emit_tail(s, st, &body.tail, ind);
}

fn emit_dispatch_tree(
    s: &mut String,
    st: &StateTable,
    tree: &DispatchTree,
    sync: u32,
    cont: Option<u32>,
    ind: &str,
) {
    match tree {
        DispatchTree::Leaf(leaf) => {
            writeln!(s, "{}{{", ind).unwrap();
            emit_dispatch_leaf_block(s, st, leaf, sync, cont, &format!("{}  ", ind));
            writeln!(s, "{}}}", ind).unwrap();
        }
        DispatchTree::Switch {
            depth,
            arms,
            default,
        } => {
            writeln!(s, "{}switch (p.Look({}).Kind) {{", ind, depth).unwrap();
            let inner = format!("{}  ", ind);
            for (kind, sub) in arms {
                let lit = format!("(ushort){}", *kind);
                writeln!(s, "{}case {}: {{", inner, lit).unwrap();
                emit_dispatch_tree(s, st, sub, sync, cont, &format!("{}  ", inner));
                writeln!(s, "{}  break;", inner).unwrap();
                writeln!(s, "{}}}", inner).unwrap();
            }
            writeln!(s, "{}default: {{", inner).unwrap();
            emit_dispatch_leaf_block(s, st, default, sync, cont, &format!("{}  ", inner));
            writeln!(s, "{}  break;", inner).unwrap();
            writeln!(s, "{}}}", inner).unwrap();
            writeln!(s, "{}}}", ind).unwrap();
        }
    }
}

fn emit_dispatch_leaf_block(
    s: &mut String,
    st: &StateTable,
    leaf: &DispatchLeaf,
    sync: u32,
    cont: Option<u32>,
    ind: &str,
) {
    match (leaf, cont) {
        (DispatchLeaf::Arm(b), Some(n)) => {
            writeln!(s, "{}p.PushRet({});", ind, n).unwrap();
            emit_body(s, st, b, ind);
        }
        (DispatchLeaf::Arm(b), None) => emit_body(s, st, b, ind),
        (DispatchLeaf::Fallthrough, Some(n)) => writeln!(s, "{}cur = {};", ind, n).unwrap(),
        (DispatchLeaf::Fallthrough, None) => writeln!(s, "{}cur = p.PopRet();", ind).unwrap(),
        (DispatchLeaf::Error, Some(n)) => {
            writeln!(s, "{}cur = {};", ind, n).unwrap();
            writeln!(s, "{}@event = p.ErrorHere(\"unexpected token\");", ind).unwrap();
            writeln!(s, "{}p.RecoverTo(Tables.Sync{});", ind, sync).unwrap();
        }
        (DispatchLeaf::Error, None) => {
            writeln!(s, "{}@event = p.ErrorHere(\"unexpected token\");", ind).unwrap();
            writeln!(s, "{}p.RecoverTo(Tables.Sync{});", ind, sync).unwrap();
            writeln!(s, "{}cur = p.PopRet();", ind).unwrap();
        }
    }
}
