use std::fmt::Write;
use std::path::PathBuf;

use crate::codegen::common::pascal;
use crate::codegen::EmittedFile;
use crate::lowering::lexer_dfa::{DfaState, START};
use crate::lowering::{Body, DispatchLeaf, DispatchTree, Instr, StateTable, Tail};

/// Per-backend arguments. Currently empty — kept as a struct (deriving
/// [`clap::Args`]) so the CLI can flatten any future flags in directly
/// and the [`emit`] signature stays stable.
#[derive(clap::Args, Clone, Debug, Default)]
pub struct Args {}

pub fn emit(st: &StateTable, _args: &Args) -> Vec<EmittedFile> {
    let mut s = String::new();

    emit_header(&mut s, st);
    emit_constants(&mut s, st);
    emit_dfa(&mut s, st);
    emit_tables(&mut s, st);
    emit_drive(&mut s, st);
    emit_public_api(&mut s, st);

    let stem = if st.grammar_name.is_empty() {
        "parser".to_string()
    } else {
        st.grammar_name.clone()
    };
    vec![EmittedFile {
        path: PathBuf::from(format!("{}.go", stem)),
        contents: s,
    }]
}

fn emit_header(s: &mut String, st: &StateTable) {
    let name = if st.grammar_name.is_empty() {
        "parser"
    } else {
        st.grammar_name.as_str()
    };

    writeln!(s, "// Code generated by parsuna; DO NOT EDIT.").unwrap();
    writeln!(s, "//").unwrap();
    writeln!(
        s,
        "// Pull-based, recoverable parser. Call one of the ParseXxx entry points"
    )
    .unwrap();
    writeln!(
        s,
        "// and repeatedly call Next on the returned *parsunart.Parser to walk"
    )
    .unwrap();
    writeln!(s, "// the parse as a flat Event stream.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "package {}", name).unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import (").unwrap();
    writeln!(s, "\t\"io\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "\trt \"parsuna.dev/parsuna-rt-go\"").unwrap();
    writeln!(s, ")").unwrap();
    writeln!(s).unwrap();
    // Re-export commonly used runtime types so callers don't need to
    // import parsuna-rt directly for the basic event-stream API.
    writeln!(s, "// Event types re-exported from the runtime.").unwrap();
    writeln!(s, "type Pos = rt.Pos").unwrap();
    writeln!(s, "type Span = rt.Span").unwrap();
    writeln!(s, "type Token = rt.Token").unwrap();
    writeln!(s, "type ParseError = rt.ParseError").unwrap();
    writeln!(s, "type Event = rt.Event").unwrap();
    writeln!(s, "type EventTag = rt.EventTag").unwrap();
    writeln!(s, "const (").unwrap();
    writeln!(s, "\tEvEnter = rt.EvEnter").unwrap();
    writeln!(s, "\tEvExit  = rt.EvExit").unwrap();
    writeln!(s, "\tEvToken = rt.EvToken").unwrap();
    writeln!(s, "\tEvError = rt.EvError").unwrap();
    writeln!(s, ")").unwrap();
    writeln!(s).unwrap();
}

fn emit_constants(s: &mut String, st: &StateTable) {
    writeln!(s, "// TokenKind enumerates every token this grammar can emit.").unwrap();
    writeln!(
        s,
        "// TkEof marks end-of-input. Lex failures (no DFA pattern matched) come"
    )
    .unwrap();
    writeln!(
        s,
        "// through as Tokens with Kind == rt.ErrorKind (0xFFFF) — distinct from"
    )
    .unwrap();
    writeln!(s, "// every grammar token id, so dispatch falls through to recovery.").unwrap();
    writeln!(s, "type TokenKind uint16").unwrap();
    writeln!(s, "const (").unwrap();
    writeln!(s, "\tTkEof TokenKind = 0").unwrap();
    for t in &st.tokens {
        writeln!(s, "\tTk{} TokenKind = {}", pascal(&t.name), t.kind).unwrap();
    }
    writeln!(s, ")").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "// TokenKindName returns the grammar-declared name of a token kind,"
    )
    .unwrap();
    writeln!(s, "// \"ERROR\" for the lex-failure sentinel, or \"?\" if unknown.").unwrap();
    writeln!(s, "func TokenKindName(k uint16) string {{").unwrap();
    writeln!(s, "\tif k == rt.ErrorKind {{ return \"ERROR\" }}").unwrap();
    writeln!(s, "\tswitch TokenKind(k) {{").unwrap();
    writeln!(s, "\tcase TkEof: return \"EOF\"").unwrap();
    for t in &st.tokens {
        writeln!(s, "\tcase Tk{}: return \"{}\"", pascal(&t.name), t.name).unwrap();
    }
    writeln!(s, "\t}}").unwrap();
    writeln!(s, "\treturn \"?\"").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "// RuleKind enumerates this grammar's non-fragment rules."
    )
    .unwrap();
    writeln!(s, "type RuleKind uint16").unwrap();
    writeln!(s, "const (").unwrap();
    for (i, n) in st.rule_kinds.iter().enumerate() {
        writeln!(s, "\tRk{} RuleKind = {}", pascal(n), i).unwrap();
    }
    writeln!(s, ")").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "// RuleKindName returns the grammar-declared name of a rule kind,"
    )
    .unwrap();
    writeln!(s, "// or \"?\" if the kind is not recognised.").unwrap();
    writeln!(s, "func RuleKindName(k RuleKind) string {{").unwrap();
    writeln!(s, "\tswitch k {{").unwrap();
    for n in &st.rule_kinds {
        writeln!(s, "\tcase Rk{}: return \"{}\"", pascal(n), n).unwrap();
    }
    writeln!(s, "\t}}").unwrap();
    writeln!(s, "\treturn \"?\"").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn token_const(st: &StateTable, kind: u16) -> String {
    if kind == 0 {
        return "TkEof".to_string();
    }
    match st.tokens.iter().find(|t| t.kind == kind) {
        Some(t) => format!("Tk{}", pascal(&t.name)),
        None => panic!("unknown token id {} while emitting Go backend", kind),
    }
}

fn rule_const(st: &StateTable, kind: u16) -> String {
    let name = st
        .rule_kinds
        .get(kind as usize)
        .unwrap_or_else(|| panic!("unknown rule kind id {} while emitting Go backend", kind));
    format!("Rk{}", pascal(name))
}

fn emit_dfa(s: &mut String, st: &StateTable) {
    let dfa = &st.lexer_dfa;

    writeln!(
        s,
        "// longestMatch scans buf[start:] for the longest accepted token."
    )
    .unwrap();
    writeln!(
        s,
        "// Returns (bestLen, bestKind, scanned). bestLen == 0 means no accept;"
    )
    .unwrap();
    writeln!(
        s,
        "// scanned is total bytes walked past start, used to detect buffer exhaustion."
    )
    .unwrap();
    writeln!(
        s,
        "func longestMatch(buf []byte, start int) (int, uint16, int) {{"
    )
    .unwrap();
    writeln!(s, "\tpos := start").unwrap();
    writeln!(s, "\tbestLen := 0").unwrap();
    writeln!(s, "\tbestKind := rt.ErrorKind").unwrap();
    writeln!(s, "\tstate := uint32({})", START).unwrap();
    writeln!(s, "\tfor {{").unwrap();
    writeln!(s, "\t\tswitch state {{").unwrap();
    for ds in dfa { emit_dfa_state_arm(s, st, ds); }
    writeln!(
        s,
        "\t\tdefault:\n\t\t\treturn bestLen, bestKind, pos - start"
    )
    .unwrap();
    writeln!(s, "\t\t}}").unwrap();
    writeln!(s, "\t}}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    write!(s, "var skipKinds = map[uint16]struct{{}}{{").unwrap();
    let skips: Vec<String> = st
        .tokens
        .iter()
        .filter(|t| t.skip)
        .map(|t| format!("uint16({}): {{}}", token_const(st, t.kind)))
        .collect();
    s.push_str(&skips.join(", "));
    writeln!(s, "}}").unwrap();
    writeln!(s, "func isSkip(k uint16) bool {{ _, ok := skipKinds[k]; return ok }}").unwrap();
    writeln!(s).unwrap();
}

fn emit_dfa_state_arm(
    s: &mut String,
    st: &StateTable,
        ds: &DfaState,
) {
    if ds.arms.is_empty() {
        writeln!(
            s,
            "\t\tcase {}:\n\t\t\treturn bestLen, bestKind, pos - start",
            ds.id
        )
        .unwrap();
        return;
    }
    writeln!(s, "\t\tcase {}:", ds.id).unwrap();
    if !ds.self_loop.is_empty() {
        // Self-loop scan-skip prologue. The Go compiler vectorises
        // tight byte-comparison loops on amd64; we keep it inline so
        // it inlines into the per-state case without a closure.
        writeln!(s, "\t\t\tfor pos < len(buf) {{").unwrap();
        writeln!(s, "\t\t\t\tb := buf[pos]").unwrap();
        writeln!(s, "\t\t\t\tif !({}) {{ break }}", byte_cond(&ds.self_loop)).unwrap();
        writeln!(s, "\t\t\t\tpos++").unwrap();
        writeln!(s, "\t\t\t}}").unwrap();
        if let Some(kind) = ds.accept {
            writeln!(s, "\t\t\tbestLen = pos - start").unwrap();
            writeln!(
                s,
                "\t\t\tbestKind = uint16({})",
                token_const(st, kind)
            )
            .unwrap();
        }
    }
    writeln!(
        s,
        "\t\t\tif pos >= len(buf) {{ return bestLen, bestKind, pos - start }}"
    )
    .unwrap();
    writeln!(s, "\t\t\tb := buf[pos]").unwrap();
    writeln!(s, "\t\t\tswitch {{").unwrap();
    for arm in &ds.arms {
        let cond = byte_cond(&arm.ranges);
        write!(
            s,
            "\t\t\tcase {}:\n\t\t\t\tpos++; state = {}",
            cond, arm.target
        )
        .unwrap();
        if let Some(kind) = arm.target_accept {
            write!(
                s,
                "; bestLen = pos - start; bestKind = uint16({})",
                token_const(st, kind)
            )
            .unwrap();
        }
        writeln!(s).unwrap();
    }
    writeln!(
        s,
        "\t\t\tdefault:\n\t\t\t\treturn bestLen, bestKind, pos - start"
    )
    .unwrap();
    writeln!(s, "\t\t\t}}").unwrap();
}


fn byte_cond(ranges: &[(u8, u8)]) -> String {
    ranges
        .iter()
        .map(|(lo, hi)| {
            if lo == hi {
                format!("b == {}", byte_literal(*lo))
            } else {
                format!(
                    "b >= {} && b <= {}",
                    byte_literal(*lo),
                    byte_literal(*hi)
                )
            }
        })
        .map(|term| {
            if ranges.len() == 1 {
                term
            } else {
                format!("({})", term)
            }
        })
        .collect::<Vec<_>>()
        .join(" || ")
}

fn byte_literal(b: u8) -> String {
    match b {
        b'\\' => "'\\\\'".to_string(),
        b'\'' => "'\\''".to_string(),
        b'\n' => "'\\n'".to_string(),
        b'\r' => "'\\r'".to_string(),
        b'\t' => "'\\t'".to_string(),
        0x20..=0x7E => format!("'{}'", b as char),
        _ => format!("0x{:02x}", b),
    }
}

fn emit_tables(s: &mut String, st: &StateTable) {
    writeln!(s, "// K is the lookahead required to disambiguate every alternative (LL(k)).").unwrap();
    writeln!(s, "const K = {}", st.k).unwrap();
    for (name, id) in &st.entry_states {
        writeln!(s, "const entry{} = {}", capitalize(name), id).unwrap();
    }
    writeln!(s).unwrap();

    writeln!(s, "var (").unwrap();
    for f in &st.first_sets {
        // Emit every FIRST set unconditionally. The Rust backend gates
        // on `has_references` because its K==1 codegen uses an inline
        // `match` instead of a FIRST table, but emit_op below always
        // calls MatchesFirst(first_N) for Op::Star/Opt regardless of
        // K — the lowering layer leaves `has_references` false at K==1
        // and would otherwise produce dangling references here.
        let seqs: Vec<String> = f
            .seqs
            .iter()
            .map(|seq| {
                format!(
                    "{{{}}}",
                    seq.iter()
                        .map(|t| format!("uint16({})", token_const(st, *t)))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            })
            .collect();
        writeln!(s, "\tfirst_{} = [][]uint16{{{}}}", f.id, seqs.join(", ")).unwrap();
    }
    for f in &st.sync_sets {
        writeln!(
            s,
            "\tsync_{} = []uint16{{{}}}",
            f.id,
            f.kinds
                .iter()
                .map(|t| format!("uint16({})", token_const(st, *t)))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    writeln!(s, ")").unwrap();
    writeln!(s).unwrap();
}

fn emit_drive(s: &mut String, st: &StateTable) {
    writeln!(s, "func step(p *rt.Cursor) (rt.Event, bool) {{").unwrap();
    writeln!(s, "\tcur := p.State()").unwrap();
    writeln!(s, "\tvar event rt.Event").unwrap();
    writeln!(s, "\tvar emitted bool").unwrap();
    writeln!(s, "\tswitch cur {{").unwrap();
    for state in st.states.values() {
        writeln!(s, "\tcase {}: // {}", state.id, state.label).unwrap();
        emit_body(s, st, &state.body);
    }
    writeln!(s, "\t}}").unwrap();
    writeln!(s, "\tp.SetState(cur)").unwrap();
    writeln!(s, "\treturn event, emitted").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_instr(s: &mut String, st: &StateTable, op: &Instr) {
    match op {
        Instr::Enter(k) => {
            writeln!(
                s,
                "\t\tevent = p.Enter(uint16({})); emitted = true",
                rule_const(st, *k)
            )
            .unwrap();
        }
        Instr::Exit(k) => {
            writeln!(
                s,
                "\t\tevent = p.Exit(uint16({})); emitted = true",
                rule_const(st, *k)
            )
            .unwrap();
        }
        Instr::Expect {
            kind,
            token_name,
            sync,
        } => {
            writeln!(
                s,
                "\t\tevent = p.TryConsume(uint16({}), sync_{}, {:?}); emitted = true",
                token_const(st, *kind),
                sync,
                token_name
            )
            .unwrap();
        }
        Instr::PushRet(r) => {
            writeln!(s, "\t\tp.PushRet({})", r).unwrap();
        }
    }
}

fn emit_tail(s: &mut String, st: &StateTable, tail: &Tail) {
    match tail {
        Tail::Jump(n) => {
            writeln!(s, "\t\tcur = {}", n).unwrap();
        }
        Tail::Ret => {
            writeln!(s, "\t\tcur = p.PopRet()").unwrap();
        }
        Tail::Star { first, body, cont, head } => {
            let miss = match cont {
                Some(n) => format!("cur = {n}"),
                None => "cur = p.PopRet()".to_string(),
            };
            writeln!(s, "\t\tif p.MatchesFirst(first_{}) {{", first).unwrap();
            writeln!(s, "\t\t\tp.PushRet({})", head).unwrap();
            emit_body(s, st, body);
            writeln!(s, "\t\t}} else {{ {miss} }}").unwrap();
        }
        Tail::Opt { first, body, cont } => {
            let miss = match cont {
                Some(n) => format!("cur = {n}"),
                None => "cur = p.PopRet()".to_string(),
            };
            writeln!(s, "\t\tif p.MatchesFirst(first_{}) {{", first).unwrap();
            if let Some(n) = cont {
                writeln!(s, "\t\t\tp.PushRet({})", n).unwrap();
            }
            emit_body(s, st, body);
            writeln!(s, "\t\t}} else {{ {miss} }}").unwrap();
        }
        Tail::Dispatch { tree, sync, cont } => {
            emit_dispatch_tree(s, st, tree, *sync, *cont, "\t\t");
        }
    }
}

fn emit_body(s: &mut String, st: &StateTable, body: &Body) {
    for op in &body.instrs {
        emit_instr(s, st, op);
    }
    emit_tail(s, st, &body.tail);
}

fn emit_dispatch_tree(
    s: &mut String,
    st: &StateTable,
    tree: &DispatchTree,
    sync: u32,
    cont: Option<u32>,
    ind: &str,
) {
    match tree {
        DispatchTree::Leaf(leaf) => emit_dispatch_leaf_block(s, st, leaf, sync, cont, ind),
        DispatchTree::Switch {
            depth,
            arms,
            default,
        } => {
            writeln!(s, "{}switch p.Look({}).Kind {{", ind, depth).unwrap();
            let inner = format!("{}\t", ind);
            let body_ind = format!("{}\t", inner);
            for (kind, sub) in arms {
                writeln!(
                    s,
                    "{}case uint16({}):",
                    inner,
                    token_const(st, *kind)
                )
                .unwrap();
                emit_dispatch_tree(s, st, sub, sync, cont, &body_ind);
            }
            writeln!(s, "{}default:", inner).unwrap();
            emit_dispatch_leaf_block(s, st, default, sync, cont, &body_ind);
            writeln!(s, "{}}}", ind).unwrap();
        }
    }
}

fn emit_dispatch_leaf_block(
    s: &mut String,
    st: &StateTable,
    leaf: &DispatchLeaf,
    sync: u32,
    cont: Option<u32>,
    ind: &str,
) {
    match (leaf, cont) {
        (DispatchLeaf::Arm(b), Some(n)) => {
            writeln!(s, "{}p.PushRet({})", ind, n).unwrap();
            emit_body(s, st, b);
        }
        (DispatchLeaf::Arm(b), None) => emit_body(s, st, b),
        (DispatchLeaf::Fallthrough, Some(n)) => writeln!(s, "{}cur = {}", ind, n).unwrap(),
        (DispatchLeaf::Fallthrough, None) => writeln!(s, "{}cur = p.PopRet()", ind).unwrap(),
        (DispatchLeaf::Error, Some(n)) => {
            writeln!(s, "{}cur = {}", ind, n).unwrap();
            writeln!(s, "{}event = p.ErrorHere(\"unexpected token\"); emitted = true", ind).unwrap();
            writeln!(s, "{}p.RecoverTo(sync_{})", ind, sync).unwrap();
        }
        (DispatchLeaf::Error, None) => {
            writeln!(s, "{}event = p.ErrorHere(\"unexpected token\"); emitted = true", ind).unwrap();
            writeln!(s, "{}p.RecoverTo(sync_{})", ind, sync).unwrap();
            writeln!(s, "{}cur = p.PopRet()", ind).unwrap();
        }
    }
}

fn emit_public_api(s: &mut String, st: &StateTable) {
    writeln!(
        s,
        "var parserConfig = rt.Config{{K: K, IsSkip: isSkip, Step: step}}"
    )
    .unwrap();
    writeln!(s).unwrap();
    for (name, _) in &st.entry_states {
        writeln!(
            s,
            "// Parse{cap} returns a Parser that parses the `{name}` rule from r.",
            cap = capitalize(name),
            name = name,
        )
        .unwrap();
        writeln!(
            s,
            "func Parse{cap}(r io.Reader) *rt.Parser {{",
            cap = capitalize(name)
        )
        .unwrap();
        writeln!(
            s,
            "\tlex := rt.NewLexer(r, longestMatch)"
        )
        .unwrap();
        writeln!(
            s,
            "\treturn rt.NewParser(lex, entry{}, parserConfig)",
            capitalize(name)
        )
        .unwrap();
        writeln!(s, "}}").unwrap();
        writeln!(s).unwrap();
    }
}

fn capitalize(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut first = true;
    for c in s.chars() {
        if first {
            out.extend(c.to_uppercase());
            first = false;
        } else {
            out.push(c);
        }
    }
    out
}
