use std::fmt::Write;
use std::path::PathBuf;

use crate::codegen::rust;
use crate::codegen::EmittedFile;
use crate::lowering::StateTable;

/// Per-backend arguments. Currently empty — kept as a struct (deriving
/// [`clap::Args`]) so the CLI can flatten any future flags in directly
/// and the [`emit`] signature stays stable.
#[derive(clap::Args, Clone, Debug, Default)]
pub struct Args {}

pub fn emit(st: &StateTable, _args: &Args) -> Vec<EmittedFile> {
    let rust_file = rust::emit(st, &rust::Args::default())
        .into_iter()
        .next()
        .unwrap()
        .contents;
    let name = if st.grammar_name.is_empty() {
        "parser".to_string()
    } else {
        st.grammar_name.clone()
    };

    let tokens: Vec<String> = st.tokens.iter().map(|t| t.name.clone()).collect();
    let rules: Vec<String> = st.entry_states.iter().map(|(n, _)| n.clone()).collect();
    let lib = build_lib_rs(&rust_file, &name, &st.rule_kinds, &tokens, &rules, &st.labels);
    let cargo = build_cargo_toml(&name);
    let pyproject = build_pyproject(&name);
    vec![
        EmittedFile {
            path: PathBuf::from("src/lib.rs"),
            contents: lib,
        },
        EmittedFile {
            path: PathBuf::from("Cargo.toml"),
            contents: cargo,
        },
        EmittedFile {
            path: PathBuf::from("pyproject.toml"),
            contents: pyproject,
        },
    ]
}

fn build_lib_rs(
    rust_file: &str,
    name: &str,
    rule_kinds: &[String],
    tokens: &[String],
    rules: &[String],
    labels: &[String],
) -> String {
    let mut out = String::new();

    writeln!(
        &mut out,
        "//! Generated by parsuna — do not edit by hand."
    )
    .unwrap();
    writeln!(&mut out, "//!").unwrap();
    writeln!(
        &mut out,
        "//! This crate compiles to a Python extension module exposing the"
    )
    .unwrap();
    writeln!(
        &mut out,
        "//! grammar's parser. From Python: `import <name>; p = <name>.parse_<rule>(src)`"
    )
    .unwrap();
    writeln!(&mut out, "//! then iterate `p` to receive Event objects.").unwrap();
    writeln!(&mut out).unwrap();

    // Strip the generated Rust file's `#![...]` inner attributes; we emit
    // our own at the crate root below.
    for line in rust_file.lines() {
        if line.starts_with("#![") {
            continue;
        }
        writeln!(&mut out, "{}", line).unwrap();
    }
    writeln!(&mut out).unwrap();

    out.push_str(PY_BINDINGS_CORE);
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "#[pyo3::pyclass(frozen, module = \"{}\", name = \"RuleKind\")]",
        name
    )
    .unwrap();
    writeln!(&mut out, "struct PyRuleKind;").unwrap();
    writeln!(&mut out, "#[pyo3::pymethods]").unwrap();
    writeln!(&mut out, "impl PyRuleKind {{").unwrap();
    for n in rule_kinds {
        let p = crate::codegen::common::pascal(n);
        writeln!(
            &mut out,
            "    #[classattr] pub const {}: u16 = RuleKind::{}.id();",
            p, p
        )
        .unwrap();
    }
    writeln!(&mut out, "    #[staticmethod]").unwrap();
    writeln!(&mut out, "    fn name(kind: u16) -> &'static str {{").unwrap();
    writeln!(&mut out, "        match kind {{").unwrap();
    for (i, n) in rule_kinds.iter().enumerate() {
        writeln!(&mut out, "            {} => \"{}\",", i, n).unwrap();
    }
    writeln!(&mut out, "            _ => \"?\",").unwrap();
    writeln!(&mut out, "        }}").unwrap();
    writeln!(&mut out, "    }}").unwrap();
    writeln!(&mut out, "}}").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "#[pyo3::pyclass(frozen, module = \"{}\", name = \"TokenKind\")]",
        name
    )
    .unwrap();
    writeln!(&mut out, "struct PyTokenKind;").unwrap();
    writeln!(&mut out, "#[pyo3::pymethods]").unwrap();
    writeln!(&mut out, "impl PyTokenKind {{").unwrap();
    for n in tokens {
        let p = crate::codegen::common::pascal(n);
        writeln!(
            &mut out,
            "    #[classattr] pub const {}: u16 = TokenKind::{} as u16;",
            p, p
        )
        .unwrap();
    }
    writeln!(
        &mut out,
        "    #[classattr] pub const EOF: u16 = parsuna_rt::TOKEN_EOF;"
    )
    .unwrap();
    writeln!(&mut out, "}}").unwrap();
    writeln!(&mut out).unwrap();

    // ---- LabelKind ------------------------------------------------------
    writeln!(
        &mut out,
        "#[pyo3::pyclass(frozen, module = \"{}\", name = \"LabelKind\")]",
        name
    )
    .unwrap();
    writeln!(&mut out, "struct PyLabelKind;").unwrap();
    writeln!(&mut out, "#[pyo3::pymethods]").unwrap();
    writeln!(&mut out, "impl PyLabelKind {{").unwrap();
    for n in labels {
        let p = crate::codegen::common::pascal(n);
        writeln!(
            &mut out,
            "    #[classattr] pub const {}: u16 = LabelKind::{}.id();",
            p, p
        )
        .unwrap();
    }
    writeln!(&mut out, "    #[staticmethod]").unwrap();
    writeln!(&mut out, "    fn name(label: u16) -> &'static str {{").unwrap();
    writeln!(&mut out, "        match label {{").unwrap();
    for (i, n) in labels.iter().enumerate() {
        writeln!(&mut out, "            {} => \"{}\",", i + 1, n).unwrap();
    }
    writeln!(&mut out, "            _ => \"?\",").unwrap();
    writeln!(&mut out, "        }}").unwrap();
    writeln!(&mut out, "    }}").unwrap();
    writeln!(&mut out, "}}").unwrap();
    writeln!(&mut out).unwrap();

    for r in rules {
        let upper = r.to_uppercase();
        writeln!(
            &mut out,
            "/// Parse the `{r}` rule. `emit_skips` (default `True`) controls whether"
        )
        .unwrap();
        writeln!(
            &mut out,
            "/// skip tokens (whitespace, comments) reach the consumer; `emit_unlabeled_tokens`"
        )
        .unwrap();
        writeln!(
            &mut out,
            "/// (default `True`) controls whether tokens without a `name:NAME` label do."
        )
        .unwrap();
        writeln!(
            &mut out,
            "#[pyo3::pyfunction(name = \"parse_{r}\", signature = (src, *, emit_skips=true, emit_unlabeled_tokens=true))]"
        )
        .unwrap();
        writeln!(
            &mut out,
            "fn parse_{r}_py(src: &str, emit_skips: bool, emit_unlabeled_tokens: bool) -> PyParser {{"
        )
        .unwrap();
        writeln!(
            &mut out,
            "    let lex = parsuna_rt::StreamingLexer::<_, TokenKind, LexerDfa>::new(std::io::Cursor::new(src.as_bytes().to_vec()));"
        )
        .unwrap();
        writeln!(
            &mut out,
            "    // Map the (emit_skips, emit_unlabeled_tokens) combo to the matching"
        )
        .unwrap();
        writeln!(
            &mut out,
            "    // ParserConfig — boxed so PyParser can hold any of the variants."
        )
        .unwrap();
        writeln!(
            &mut out,
            "    let inner: Box<dyn Iterator<Item = parsuna_rt::Event<'static, TokenKind, RuleKind>>> ="
        )
        .unwrap();
        writeln!(
            &mut out,
            "        match (emit_skips, emit_unlabeled_tokens) {{"
        )
        .unwrap();
        writeln!(
            &mut out,
            "            (true, true) => Box::new(parsuna_rt::Parser::<_, _, _, _, parsuna_rt::EmitSkips>::new(lex, ENTRY_{upper})),"
        )
        .unwrap();
        writeln!(
            &mut out,
            "            (false, true) => Box::new(parsuna_rt::Parser::<_, _, _, _, parsuna_rt::DropSkips>::new(lex, ENTRY_{upper})),"
        )
        .unwrap();
        writeln!(
            &mut out,
            "            (_, false) => Box::new(parsuna_rt::Parser::<_, _, _, _, parsuna_rt::LabeledOnly>::new(lex, ENTRY_{upper})),"
        )
        .unwrap();
        writeln!(&mut out, "        }};").unwrap();
        writeln!(&mut out, "    PyParser {{ inner }}").unwrap();
        writeln!(&mut out, "}}").unwrap();
    }
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "#[pyo3::pymodule]").unwrap();
    writeln!(
        &mut out,
        "fn {}(_py: pyo3::Python, m: &pyo3::types::PyModule) -> pyo3::PyResult<()> {{",
        name
    )
    .unwrap();
    writeln!(&mut out, "    m.add_class::<PyPos>()?;").unwrap();
    writeln!(&mut out, "    m.add_class::<PySpan>()?;").unwrap();
    writeln!(&mut out, "    m.add_class::<PyError>()?;").unwrap();
    writeln!(&mut out, "    m.add_class::<PyEvent>()?;").unwrap();
    writeln!(&mut out, "    m.add_class::<PyParser>()?;").unwrap();
    writeln!(&mut out, "    m.add_class::<PyRuleKind>()?;").unwrap();
    writeln!(&mut out, "    m.add_class::<PyTokenKind>()?;").unwrap();
    writeln!(&mut out, "    m.add_class::<PyLabelKind>()?;").unwrap();
    for r in rules {
        writeln!(
            &mut out,
            "    m.add_function(pyo3::wrap_pyfunction!(parse_{}_py, m)?)?;",
            r
        )
        .unwrap();
    }
    writeln!(&mut out, "    Ok(())").unwrap();
    writeln!(&mut out, "}}").unwrap();

    out
}

fn build_cargo_toml(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[lib]
name = "{name}"
crate-type = ["cdylib"]

[dependencies]
# Point this `path` at your local parsuna-rt checkout, or replace with a
# crates.io dependency once parsuna-rt is published.
parsuna-rt = {{ path = "../../../runtimes/rust" }}
pyo3 = {{ version = "0.20", features = ["extension-module"] }}
"#
    )
}

fn build_pyproject(name: &str) -> String {
    format!(
        r#"[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "{name}"
version = "0.1.0"
description = "Generated parser for the `{name}` grammar (parsuna)."
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]

[tool.maturin]
features = ["pyo3/extension-module"]
"#
    )
}

const PY_BINDINGS_CORE: &str = r#"
use pyo3::prelude::*;

/// Source position: byte offset plus 1-based line/column.
#[pyclass(frozen, get_all, name = "Pos")]
#[derive(Clone, Copy, Debug)]
struct PyPos { offset: u32, line: u32, column: u32 }

#[pymethods]
impl PyPos {
    fn __repr__(&self) -> String { format!("Pos({}, {}, {})", self.offset, self.line, self.column) }
}

/// Half-open span `[start, end)` over the source.
#[pyclass(frozen, get_all, name = "Span")]
#[derive(Clone, Copy, Debug)]
struct PySpan { start: PyPos, end: PyPos }

#[pymethods]
impl PySpan {
    fn __repr__(&self) -> String {
        format!("Span({}:{}-{}:{})", self.start.line, self.start.column, self.end.line, self.end.column)
    }
}

/// A recoverable parse or lex error.
#[pyclass(frozen, get_all, name = "Error")]
#[derive(Clone, Debug)]
struct PyError { message: String }

#[pymethods]
impl PyError {
    fn __repr__(&self) -> String {
        format!("Error({:?})", self.message)
    }
}

/// A single pull-parser event. `tag` is one of "enter", "exit", "token",
/// "garbage", or "error"; the populated payload field depends on the tag.
///
/// `label` is the codegen's `LabelKind` discriminant for tokens whose
/// grammar position used the `name:NAME` form, or `None` for unlabeled
/// positions / non-token events. Compare against `LabelKind` constants
/// (also exported from this module) — no string handling.
#[pyclass(frozen, get_all, name = "Event")]
#[derive(Clone, Debug)]
struct PyEvent {
    tag: String,
    span: PySpan,
    kind: Option<i32>,
    text: Option<String>,
    label: Option<i32>,
    error: Option<PyError>,
}

#[pymethods]
impl PyEvent {
    fn is_enter(&self) -> bool { self.tag == "enter" }
    fn is_exit(&self) -> bool { self.tag == "exit" }
    fn is_token(&self) -> bool { self.tag == "token" }
    fn is_garbage(&self) -> bool { self.tag == "garbage" }
    fn is_error(&self) -> bool { self.tag == "error" }
    fn __repr__(&self) -> String {
        match (self.tag.as_str(), self.text.as_deref(), self.error.as_ref()) {
            ("enter", _, _) => format!("Event(enter rule={})", self.kind.unwrap_or(0)),
            ("exit", _, _)  => format!("Event(exit rule={})", self.kind.unwrap_or(0)),
            ("token", Some(t), _) => format!("Event(token kind={} text={:?})", self.kind.unwrap_or(0), t),
            ("token", None, _)    => format!("Event(token kind={})", self.kind.unwrap_or(0)),
            ("garbage", Some(t), _) => format!("Event(garbage kind={} text={:?})", self.kind.unwrap_or(0), t),
            ("garbage", None, _)    => format!("Event(garbage kind={})", self.kind.unwrap_or(0)),
            ("error", _, Some(d)) => format!("Event(error {:?})", d.message),
            _ => "Event(?)".to_string(),
        }
    }
}

fn to_py_pos(p: parsuna_rt::Pos) -> PyPos { PyPos { offset: p.offset, line: p.line, column: p.column } }
fn to_py_span(s: parsuna_rt::Span) -> PySpan { PySpan { start: to_py_pos(s.start), end: to_py_pos(s.end) } }
fn to_py_diag(d: parsuna_rt::Error) -> PyError {
    PyError { message: d.message.into_owned() }
}
fn to_py_event(ev: Event) -> PyEvent {
    match ev {
        parsuna_rt::Event::Enter { rule, pos } => PyEvent {
            tag: "enter".into(),
            span: to_py_span(parsuna_rt::Span::point(pos)),
            kind: Some(rule as i32),
            text: None,
            label: None,
            error: None,
        },
        parsuna_rt::Event::Exit { rule, pos } => PyEvent {
            tag: "exit".into(),
            span: to_py_span(parsuna_rt::Span::point(pos)),
            kind: Some(rule as i32),
            text: None,
            label: None,
            error: None,
        },
        parsuna_rt::Event::Error(d) => {
            let span = to_py_span(d.span);
            PyEvent { tag: "error".into(), span, kind: None, text: None, label: None, error: Some(to_py_diag(d)) }
        }
        parsuna_rt::Event::Token(t) => {
            let span = to_py_span(t.span);
            PyEvent {
                tag: "token".into(),
                span,
                kind: t.kind.map(|k| k as i32),
                text: Some(t.text.into_owned()),
                label: t.label.map(|lk| lk.id() as i32),
                error: None,
            }
        }
        parsuna_rt::Event::Garbage(t) => {
            let span = to_py_span(t.span);
            PyEvent {
                tag: "garbage".into(),
                span,
                kind: t.kind.map(|k| k as i32),
                text: Some(t.text.into_owned()),
                label: t.label.map(|lk| lk.id() as i32),
                error: None,
            }
        }
    }
}

/// Pull-based parser. Iterate to walk the parse as a sequence of
/// [`PyEvent`] values, or call `next_event` manually.
///
/// The wrapped iterator is boxed so the same Python type can hold any
/// of the runtime's `ParserConfig` variants (`EmitSkips`, `DropSkips`,
/// `LabeledOnly`) — the per-rule factory functions construct the
/// matching `Parser<...>` and box it.
#[pyclass(unsendable, name = "Parser")]
struct PyParser {
    inner: Box<dyn Iterator<Item = Event<'static, TokenKind, RuleKind>>>,
}

#[pymethods]
impl PyParser {
    fn next_event(&mut self) -> Option<PyEvent> { self.inner.next().map(to_py_event) }

    fn __iter__(slf: PyRef<Self>) -> PyRef<Self> { slf }
    fn __next__(&mut self) -> Option<PyEvent> { self.next_event() }
}
"#;
