use std::fmt::Write;
use std::path::PathBuf;

use crate::codegen::common::pascal;
use crate::codegen::EmittedFile;
use crate::lowering::lexer_dfa::{DfaState, START};
use crate::lowering::{Body, DispatchLeaf, DispatchTree, Instr, StateTable, Tail};

/// Per-backend arguments. Currently empty — kept as a struct (deriving
/// [`clap::Args`]) so the CLI can flatten any future flags in directly
/// and the [`emit`] signature stays stable.
#[derive(clap::Args, Clone, Debug, Default)]
pub struct Args {}

pub fn emit(st: &StateTable, _args: &Args) -> Vec<EmittedFile> {
    let mut s = String::new();

    emit_prelude(&mut s, st);
    emit_token_kinds(&mut s, st);
    emit_rule_kinds(&mut s, st);
    emit_reexports(&mut s);
    emit_compiled_dfa(&mut s, st);
    emit_tables(&mut s, st);
    emit_parser(&mut s);
    emit_step(&mut s, st);
    emit_public_api(&mut s, st);

    let stem = if st.grammar_name.is_empty() {
        "parser".to_string()
    } else {
        st.grammar_name.clone()
    };
    vec![EmittedFile {
        path: PathBuf::from(format!("{}.rs", stem)),
        contents: s,
    }]
}

fn emit_prelude(s: &mut String, _st: &StateTable) {
    writeln!(s, "//! Generated by parsuna — do not edit by hand.").unwrap();
    writeln!(s, "//!").unwrap();
    writeln!(
        s,
        "//! Pull-based, recoverable parser. Call one of the `parse_*_from_str` /"
    )
    .unwrap();
    writeln!(
        s,
        "//! `parse_*_from_reader` constructors and iterate the resulting [`Parser`]"
    )
    .unwrap();
    writeln!(s, "//! to walk the parse as a flat [`Event`] stream.").unwrap();
    writeln!(s, "#![allow(dead_code, unused_imports)]").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use std::io::Read;").unwrap();
    writeln!(
        s,
        "use parsuna_rt::{{DfaMatch, DfaMatcher, LexerBackend, Scanner, StreamingLexer, TERMINATED}};"
    )
    .unwrap();
    writeln!(s).unwrap();
}

fn emit_token_kinds(s: &mut String, st: &StateTable) {
    writeln!(s, "/// The set of token kinds this grammar can emit.").unwrap();
    writeln!(s, "///").unwrap();
    writeln!(
        s,
        "/// `Eof` marks end-of-input; the other variants come from the grammar's"
    )
    .unwrap();
    writeln!(
        s,
        "/// `token` declarations. Lex failures (no pattern matched) are surfaced"
    )
    .unwrap();
    writeln!(
        s,
        "/// as `Token {{ kind: None }}` rather than an in-band error variant."
    )
    .unwrap();
    writeln!(s, "#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]").unwrap();
    writeln!(s, "#[repr(u16)]").unwrap();
    writeln!(s, "pub enum TokenKind {{").unwrap();
    writeln!(s, "    Eof = 0,").unwrap();
    for t in &st.tokens {
        writeln!(s, "    {} = {},", pascal(&t.name), t.kind).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "impl TokenKind {{").unwrap();
    writeln!(s, "    /// Numeric discriminant, equal to `self as u16`.").unwrap();
    writeln!(s, "    pub const fn id(self) -> u16 {{ self as u16 }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "impl parsuna_rt::TokenKindEnum for TokenKind {{").unwrap();
    writeln!(s, "    fn name(self) -> &'static str {{").unwrap();
    writeln!(s, "        match self {{").unwrap();
    writeln!(s, "            TokenKind::Eof => \"EOF\",").unwrap();
    for t in &st.tokens {
        writeln!(
            s,
            "            TokenKind::{} => \"{}\",",
            pascal(&t.name),
            t.name
        )
        .unwrap();
    }
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "    const EOF: Self = Self::Eof;").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_rule_kinds(s: &mut String, st: &StateTable) {
    writeln!(s, "/// One variant per non-fragment rule in the grammar.").unwrap();
    writeln!(s, "///").unwrap();
    writeln!(
        s,
        "/// Attached to [`Event::Enter`] and [`Event::Exit`] so consumers can"
    )
    .unwrap();
    writeln!(s, "/// tell which rule a subtree corresponds to.").unwrap();
    writeln!(s, "#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]").unwrap();
    writeln!(s, "#[repr(u16)]").unwrap();
    writeln!(s, "pub enum RuleKind {{").unwrap();
    for (i, n) in st.rule_kinds.iter().enumerate() {
        writeln!(s, "    {} = {},", pascal(n), i).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "impl RuleKind {{").unwrap();
    writeln!(s, "    /// Numeric discriminant, equal to `self as u16`.").unwrap();
    writeln!(s, "    pub const fn id(self) -> u16 {{ self as u16 }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "impl parsuna_rt::RuleKindEnum for RuleKind {{").unwrap();
    writeln!(s, "    fn name(self) -> &'static str {{").unwrap();
    writeln!(s, "        match self {{").unwrap();
    for n in &st.rule_kinds {
        writeln!(s, "            RuleKind::{} => \"{}\",", pascal(n), n).unwrap();
    }
    if st.rule_kinds.is_empty() {}
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_reexports(s: &mut String) {
    s.push_str("\n\n");

    s.push_str("/// Re-exports of the runtime types used by this parser.\n");
    s.push_str("pub use parsuna_rt::{Span, Pos, Error};\n");
    s.push_str("/// Parse event carrying this grammar's token and rule kinds.\n");
    s.push_str("pub type Event<'a> = parsuna_rt::Event<'a, TokenKind, RuleKind>;\n");
    s.push_str("/// A lexed token with this grammar's [`TokenKind`].\n");
    s.push_str("pub type Token<'a> = parsuna_rt::Token<'a, TokenKind>;\n\n");
}

fn emit_compiled_dfa(s: &mut String, st: &StateTable) {
    let dfa = &st.lexer_dfa;

    writeln!(s).unwrap();
    writeln!(s, "/// Compiled lexer DFA for this grammar.").unwrap();
    writeln!(s, "///").unwrap();
    writeln!(
        s,
        "/// Zero-sized type whose [`DfaMatcher`] impl drives the lexer via a"
    )
    .unwrap();
    writeln!(
        s,
        "/// per-state `match` rather than a transition table. Generated code"
    )
    .unwrap();
    writeln!(s, "/// supplies this to [`Scanner`]/[`StreamingLexer`].").unwrap();
    writeln!(s, "pub struct LexerDfa;").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "impl DfaMatcher<TokenKind> for LexerDfa {{").unwrap();
    writeln!(s, "    #[inline]").unwrap();
    writeln!(
        s,
        "    fn longest_match(buf: &[u8], start: usize) -> DfaMatch<TokenKind> {{"
    )
    .unwrap();
    writeln!(s, "        let mut pos = start;").unwrap();
    writeln!(s, "        let mut best_len: usize = 0;").unwrap();
    writeln!(s, "        let mut best_kind: Option<TokenKind> = None;").unwrap();
    writeln!(s, "        let mut state: u32 = {};", START).unwrap();
    writeln!(s, "        loop {{").unwrap();
    writeln!(s, "            match state {{").unwrap();

    for ds in dfa {
        emit_dfa_state_arm(s, st, ds, "                ");
    }

    writeln!(s, "                _ => break,").unwrap();
    writeln!(s, "            }}").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(
        s,
        "        DfaMatch {{ best_len, best_kind, scanned: pos - start }}"
    )
    .unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_dfa_state_arm(s: &mut String, st: &StateTable, ds: &DfaState, ind: &str) {
    if ds.arms.is_empty() {
        writeln!(s, "{}{} => break,", ind, ds.id).unwrap();
        return;
    }

    // Fast path for states with a self-loop on a contiguous byte set:
    // peel the loop into a single `while` that advances `pos` past every
    // byte in the set in one go. Saves an outer-loop iteration per
    // looped byte — this is most of a typical lexer's hot path
    // (whitespace runs, identifier bodies, comment / string contents).
    // The byte that breaks the inner loop falls through to the regular
    // dispatch below, so non-self-loop transitions are unchanged.
    let inner_ind = if ds.self_loop.is_empty() {
        ind.to_string()
    } else {
        let pat = format_byte_pattern(&ds.self_loop);
        writeln!(s, "{}{} => {{", ind, ds.id).unwrap();
        writeln!(s, "{}    while let Some(&b) = buf.get(pos) {{", ind).unwrap();
        writeln!(s, "{}        if !matches!(b, {}) {{ break; }}", ind, pat).unwrap();
        writeln!(s, "{}        pos += 1;", ind).unwrap();
        writeln!(s, "{}    }}", ind).unwrap();
        if let Some(kind) = ds.accept {
            writeln!(s, "{}    best_len = pos - start;", ind).unwrap();
            writeln!(
                s,
                "{}    best_kind = Some({});",
                ind,
                token_variant(st, kind)
            )
            .unwrap();
        }
        format!("{}    ", ind)
    };

    let prefix = if ds.self_loop.is_empty() {
        format!("{}{} => ", ind, ds.id)
    } else {
        inner_ind.clone()
    };

    writeln!(s, "{}match buf.get(pos) {{", prefix).unwrap();
    for arm in &ds.arms {
        let pat = format_byte_pattern(&arm.ranges);
        let is_single_byte = arm.ranges.len() == 1 && arm.ranges[0].0 == arm.ranges[0].1;
        let wrapped = if is_single_byte {
            pat
        } else {
            format!("({})", pat)
        };
        write!(
            s,
            "{}    Some(&{}) => {{ pos += 1; state = {};",
            inner_ind, wrapped, arm.target
        )
        .unwrap();
        if let Some(kind) = arm.target_accept {
            write!(
                s,
                " best_len = pos - start; best_kind = Some({});",
                token_variant(st, kind)
            )
            .unwrap();
        }
        writeln!(s, " }}").unwrap();
    }
    writeln!(s, "{}    _ => break,", inner_ind).unwrap();
    if ds.self_loop.is_empty() {
        writeln!(s, "{}}},", ind).unwrap();
    } else {
        writeln!(s, "{}}}", inner_ind).unwrap();
        writeln!(s, "{}}},", ind).unwrap();
    }
}

fn format_byte_pattern(ranges: &[(u8, u8)]) -> String {
    ranges
        .iter()
        .map(|(lo, hi)| {
            if lo == hi {
                byte_literal(*lo)
            } else {
                format!("{}..={}", byte_literal(*lo), byte_literal(*hi))
            }
        })
        .collect::<Vec<_>>()
        .join(" | ")
}

fn byte_literal(b: u8) -> String {
    match b {
        b'\\' => "b'\\\\'".to_string(),
        b'\'' => "b'\\''".to_string(),
        b'\n' => "b'\\n'".to_string(),
        b'\r' => "b'\\r'".to_string(),
        b'\t' => "b'\\t'".to_string(),
        0x20..=0x7E => format!("b'{}'", b as char),
        _ => format!("0x{:02x}", b),
    }
}

fn emit_tables(s: &mut String, st: &StateTable) {
    writeln!(s).unwrap();

    writeln!(
        s,
        "/// Lookahead required to disambiguate every alternative (LL(k))."
    )
    .unwrap();
    writeln!(s, "pub const K: usize = {};", st.k).unwrap();

    for (name, id) in &st.entry_states {
        writeln!(s, "const ENTRY_{}: u32 = {};", name.to_uppercase(), id).unwrap();
    }
    writeln!(s).unwrap();

    for f in &st.first_sets {
        if !f.has_references {
            continue;
        }
        write!(s, "static FIRST_{}: &[&[TokenKind]] = &[", f.id).unwrap();
        for (j, seq) in f.seqs.iter().enumerate() {
            if j > 0 {
                s.push_str(", ");
            }
            s.push_str("&[");
            for (k, t) in seq.iter().enumerate() {
                if k > 0 {
                    s.push_str(", ");
                }
                write!(s, "{}", token_variant(st, *t)).unwrap();
            }
            s.push(']');
        }
        writeln!(s, "];").unwrap();
    }
    writeln!(s).unwrap();
    for f in &st.sync_sets {
        write!(s, "static SYNC_{}: &[TokenKind] = &[", f.id).unwrap();
        for (k, t) in f.kinds.iter().enumerate() {
            if k > 0 {
                s.push_str(", ");
            }
            write!(s, "{}", token_variant(st, *t)).unwrap();
        }
        writeln!(s, "];").unwrap();
    }
    writeln!(s).unwrap();
}

fn token_variant(st: &StateTable, kind: u16) -> String {
    if kind == 0 {
        return "TokenKind::Eof".to_string();
    }
    match st.tokens.iter().find(|t| t.kind == kind) {
        Some(t) => format!("TokenKind::{}", pascal(&t.name)),
        None => panic!("unknown token id {} while emitting Rust backend", kind),
    }
}

fn rule_variant(st: &StateTable, kind: u16) -> String {
    let name = st
        .rule_kinds
        .get(kind as usize)
        .unwrap_or_else(|| panic!("unknown rule kind id {} while emitting Rust backend", kind));
    format!("RuleKind::{}", pascal(name))
}

fn emit_parser(s: &mut String) {
    s.push_str(
        r#"
/// Zero-sized marker type that carries the generated dispatch logic via
/// [`parsuna_rt::Grammar`]. You never construct one directly — it's a
/// type-level parameter to [`Parser`].
pub struct Grammar;

/// Parser alias pinning the grammar and lookahead. `L` is any
/// [`LexerBackend`]; the generated `parse_*_from_str`/`parse_*_from_reader`
/// helpers build a parser with either [`Scanner`] or [`StreamingLexer`].
pub type Parser<'a, L> = parsuna_rt::Parser<'a, L, K, Grammar>;
"#,
    );
}

fn kind_pattern(st: &StateTable, first: &[Vec<u16>]) -> String {
    let mut kinds: Vec<u16> = first
        .iter()
        .map(|seq| {
            assert_eq!(seq.len(), 1, "kind_pattern expects LL(1) singletons");
            seq[0]
        })
        .collect();
    kinds.sort_unstable();
    kinds.dedup();
    kinds
        .iter()
        .map(|k| format!("Some({})", token_variant(st, *k)))
        .collect::<Vec<_>>()
        .join(" | ")
}

fn emit_instr(s: &mut String, st: &StateTable, op: &Instr, ind: &str) {
    match op {
        Instr::Enter(k) => writeln!(
            s,
            "{}event = Some(p.enter({}));",
            ind,
            rule_variant(st, *k)
        )
        .unwrap(),
        Instr::Exit(k) => writeln!(
            s,
            "{}event = Some(p.exit({}));",
            ind,
            rule_variant(st, *k)
        )
        .unwrap(),
        Instr::Expect {
            kind,
            token_name,
            sync,
        } => writeln!(
            s,
            "{}event = Some(p.expect({}, SYNC_{}, \"expected {}\"));",
            ind,
            token_variant(st, *kind),
            sync,
            token_name
        )
        .unwrap(),
        Instr::PushRet(r) => writeln!(s, "{}p.push_ret({});", ind, r).unwrap(),
    }
}

fn emit_tail(s: &mut String, st: &StateTable, tail: &Tail, ind: &str) {
    match tail {
        Tail::Jump(n) => writeln!(s, "{}cur = {};", ind, n).unwrap(),
        Tail::Ret => writeln!(s, "{}cur = p.ret();", ind).unwrap(),
        Tail::Star {
            first,
            body,
            cont,
            head,
        } => {
            emit_lookahead_branch(
                s,
                st,
                *first,
                ind,
                |s, ind| {
                    writeln!(s, "{}p.push_ret({});", ind, head).unwrap();
                    emit_body(s, st, body, ind);
                },
                |s, ind| match cont {
                    Some(n) => writeln!(s, "{}cur = {};", ind, n).unwrap(),
                    None => writeln!(s, "{}cur = p.ret();", ind).unwrap(),
                },
            );
        }
        Tail::Opt { first, body, cont } => {
            emit_lookahead_branch(
                s,
                st,
                *first,
                ind,
                |s, ind| {
                    if let Some(n) = cont {
                        writeln!(s, "{}p.push_ret({});", ind, n).unwrap();
                    }
                    emit_body(s, st, body, ind);
                },
                |s, ind| match cont {
                    Some(n) => writeln!(s, "{}cur = {};", ind, n).unwrap(),
                    None => writeln!(s, "{}cur = p.ret();", ind).unwrap(),
                },
            );
        }
        Tail::Dispatch { tree, sync, cont } => {
            emit_dispatch_tree(s, st, tree, *sync, *cont, ind);
        }
    }
}

/// Emit each instr in `body`'s head, then the tail. The tail is the
/// body's terminator — `Ret`, `Jump`, or a branchy op that encodes
/// its own continuation — so the linear emission already settles the
/// post-body transition with no extra glue.
fn emit_body(s: &mut String, st: &StateTable, body: &Body, ind: &str) {
    for op in &body.instrs {
        emit_instr(s, st, op, ind);
    }
    emit_tail(s, st, &body.tail, ind);
}

fn emit_lookahead_branch(
    s: &mut String,
    st: &StateTable,
    first: u32,
    ind: &str,
    on_match: impl FnOnce(&mut String, &str),
    on_miss: impl FnOnce(&mut String, &str),
) {
    if st.k == 1 {
        let pat = kind_pattern(st, &st.first_sets[first as usize].seqs);
        writeln!(s, "{}match p.look(0).kind {{", ind).unwrap();
        writeln!(s, "{}    {} => {{", ind, pat).unwrap();
        on_match(s, &format!("{}        ", ind));
        writeln!(s, "{}    }}", ind).unwrap();
        writeln!(s, "{}    _ => {{", ind).unwrap();
        on_miss(s, &format!("{}        ", ind));
        writeln!(s, "{}    }}", ind).unwrap();
        writeln!(s, "{}}}", ind).unwrap();
    } else {
        writeln!(s, "{}if p.matches_first(FIRST_{}) {{", ind, first).unwrap();
        on_match(s, &format!("{}    ", ind));
        writeln!(s, "{}}} else {{", ind).unwrap();
        on_miss(s, &format!("{}    ", ind));
        writeln!(s, "{}}}", ind).unwrap();
    }
}

fn emit_dispatch_tree(
    s: &mut String,
    st: &StateTable,
    tree: &DispatchTree,
    sync: u32,
    cont: Option<u32>,
    ind: &str,
) {
    match tree {
        DispatchTree::Leaf(leaf) => emit_dispatch_leaf(s, st, leaf, sync, cont, ind),
        DispatchTree::Switch {
            depth,
            arms,
            default,
        } => {
            writeln!(s, "{}match p.look({}).kind {{", ind, depth).unwrap();
            let inner = format!("{}    ", ind);
            let inner2 = format!("{}    ", inner);
            for (kind, sub) in arms {
                let pat = format!("Some({})", token_variant(st, *kind));
                writeln!(s, "{}{} => {{", inner, pat).unwrap();
                emit_dispatch_tree(s, st, sub, sync, cont, &inner2);
                writeln!(s, "{}}}", inner).unwrap();
            }
            writeln!(s, "{}_ => {{", inner).unwrap();
            emit_dispatch_leaf(s, st, default, sync, cont, &inner2);
            writeln!(s, "{}}}", inner).unwrap();
            writeln!(s, "{}}}", ind).unwrap();
        }
    }
}

fn emit_dispatch_leaf(s: &mut String, st: &StateTable, leaf: &DispatchLeaf, sync: u32, cont: Option<u32>, ind: &str) {
    match (leaf, cont) {
        (DispatchLeaf::Arm(b), Some(n)) => {
            writeln!(s, "{}p.push_ret({});", ind, n).unwrap();
            emit_body(s, st, b, ind);
        }
        (DispatchLeaf::Arm(b), None) => {
            emit_body(s, st, b, ind);
        }
        (DispatchLeaf::Fallthrough, Some(n)) => {
            writeln!(s, "{}cur = {};", ind, n).unwrap();
        }
        (DispatchLeaf::Fallthrough, None) => {
            writeln!(s, "{}cur = p.ret();", ind).unwrap();
        }
        (DispatchLeaf::Error, Some(n)) => {
            writeln!(s, "{}cur = {};", ind, n).unwrap();
            writeln!(s, "{}event = Some(p.error_here(\"unexpected token\"));", ind).unwrap();
            writeln!(s, "{}p.recover_to(SYNC_{});", ind, sync).unwrap();
        }
        (DispatchLeaf::Error, None) => {
            writeln!(s, "{}event = Some(p.error_here(\"unexpected token\"));", ind).unwrap();
            writeln!(s, "{}p.recover_to(SYNC_{});", ind, sync).unwrap();
            writeln!(s, "{}cur = p.ret();", ind).unwrap();
        }
    }
}

fn emit_step(s: &mut String, st: &StateTable) {
    let skip_kinds: Vec<u16> = st
        .tokens
        .iter()
        .filter(|t| t.skip)
        .map(|t| t.kind)
        .collect();
    let has_skips = !skip_kinds.is_empty();

    writeln!(s, "impl parsuna_rt::Grammar<K> for Grammar {{").unwrap();
    writeln!(s, "    type TokenKind = TokenKind;").unwrap();
    writeln!(s, "    type RuleKind = RuleKind;").unwrap();
    writeln!(s, "    const HAS_SKIPS: bool = {};", has_skips).unwrap();
    writeln!(s).unwrap();
    writeln!(s, "    #[inline(always)]").unwrap();
    writeln!(s, "    fn is_skip(kind: TokenKind) -> bool {{").unwrap();
    if has_skips {
        let pat = skip_kinds
            .iter()
            .map(|k| token_variant(st, *k))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(s, "        matches!(kind, {})", pat).unwrap();
    } else {
        writeln!(s, "        let _ = kind; false").unwrap();
    }
    writeln!(s, "    }}").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "    #[inline]").unwrap();
    writeln!(
        s,
        "    fn step<'a, 'p, L: LexerBackend<'a, Self::TokenKind>>(p: &mut parsuna_rt::Cursor<'p, 'a, L, K, Self>) -> Option<parsuna_rt::Event<'a, TokenKind, RuleKind>> {{"
    )
    .unwrap();
    // One match arm per call. Each arm runs a state body's ops —
    // possibly assigning `event` (Enter/Exit/Expect/error_here) and
    // always updating `cur`. The runtime's next_event loop calls
    // step again if we return None.
    writeln!(s, "        let mut cur = p.state();").unwrap();
    writeln!(
        s,
        "        let mut event: Option<parsuna_rt::Event<'a, TokenKind, RuleKind>> = None;"
    )
    .unwrap();
    writeln!(s, "        match cur {{").unwrap();
    for state in st.states.values() {
        writeln!(s, "            {} => {{ // {}", state.id, state.label).unwrap();
        let ind = "                ";
        emit_body(s, st, &state.body, ind);
        writeln!(s, "            }}").unwrap();
    }
    writeln!(s, "            _ => unreachable!(\"unknown state\"),").unwrap();
    writeln!(s, "        }}").unwrap();
    writeln!(s, "        p.set_state(cur);").unwrap();
    writeln!(s, "        event").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_public_api(s: &mut String, st: &StateTable) {
    if !st.entry_states.is_empty() {
        writeln!(s).unwrap();
        writeln!(s).unwrap();

        for (name, _) in &st.entry_states {
            writeln!(s, "/// Parse the `{name}` rule from an in-memory string.").unwrap();
            writeln!(s, "///").unwrap();
            writeln!(s, "/// Zero-copy: tokens borrow their text from `src`.").unwrap();
            writeln!(
                s,
                "pub fn parse_{name}_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {{",
                name = name
            )
            .unwrap();
            writeln!(
                s,
                "    Parser::new(Scanner::new(src), ENTRY_{upper})",
                upper = name.to_uppercase()
            )
            .unwrap();
            writeln!(s, "}}").unwrap();
            writeln!(s).unwrap();

            writeln!(s, "/// Parse the `{name}` rule from any [`Read`] source.").unwrap();
            writeln!(s, "///").unwrap();
            writeln!(
                s,
                "/// Streaming: tokens own their text; memory use stays bounded regardless of"
            )
            .unwrap();
            writeln!(s, "/// input size.").unwrap();
            writeln!(
                s,
                "pub fn parse_{name}_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {{",
                name = name
            )
            .unwrap();
            writeln!(
                s,
                "    Parser::new(StreamingLexer::new(reader), ENTRY_{upper})",
                upper = name.to_uppercase()
            )
            .unwrap();
            writeln!(s, "}}").unwrap();
            writeln!(s).unwrap();
        }
    }
}
