use std::fmt::Write;
use std::path::PathBuf;

use crate::codegen::common::pascal;
use crate::codegen::EmittedFile;
use crate::lowering::lexer_dfa::{DfaState, START};
use crate::lowering::recovery::{Insertion, PostFirst};
use crate::lowering::{Body, DispatchLeaf, DispatchTree, Instr, StateTable, Tail};

/// Per-backend arguments. Currently empty — kept as a struct (deriving
/// [`clap::Args`]) so the CLI can flatten any future flags in directly
/// and the [`emit`] signature stays stable.
#[derive(clap::Args, Clone, Debug, Default)]
pub struct Args {}

pub fn emit(st: &StateTable, _args: &Args) -> Vec<EmittedFile> {
    let mut s = String::new();

    emit_header(&mut s, st);
    emit_imports(&mut s);
    emit_constants(&mut s, st);
    emit_dfa(&mut s, st);
    emit_tables(&mut s, st);
    emit_drive(&mut s, st);
    emit_public_api(&mut s, st);

    let stem = if st.grammar_name.is_empty() {
        "parser".to_string()
    } else {
        st.grammar_name.clone()
    };
    vec![EmittedFile {
        path: PathBuf::from(format!("{}.ts", stem)),
        contents: s,
    }]
}

fn emit_header(s: &mut String, _st: &StateTable) {
    writeln!(s, "// Generated by parsuna — do not edit by hand.").unwrap();
    writeln!(s, "//").unwrap();
    writeln!(
        s,
        "// Pull-based, recoverable parser. Call one of the `parseXxx` entry"
    )
    .unwrap();
    writeln!(
        s,
        "// points and iterate the returned Parser to walk the parse as a"
    )
    .unwrap();
    writeln!(
        s,
        "// flat Event stream. Requires the `parsuna-rt` runtime package."
    )
    .unwrap();
    writeln!(s).unwrap();
}

fn emit_imports(s: &mut String) {
    writeln!(
        s,
        "import {{ Cursor, DfaMatch, Event, Lexer, Parser, TERMINATED }} from \"parsuna-rt\";"
    )
    .unwrap();
    writeln!(
        s,
        "export type {{ Pos, Span, Token, ParseError, Event }} from \"parsuna-rt\";"
    )
    .unwrap();
    writeln!(s, "export {{ errorToString }} from \"parsuna-rt\";").unwrap();
    writeln!(s).unwrap();
}

fn emit_constants(s: &mut String, st: &StateTable) {
    writeln!(s, "/**").unwrap();
    writeln!(
        s,
        " * Token kinds this grammar can emit. `Eof` is a runtime sentinel; every"
    )
    .unwrap();
    writeln!(
        s,
        " * other variant corresponds to a `token` declaration in the grammar."
    )
    .unwrap();
    writeln!(
        s,
        " * Lex failures (no pattern matched) come through as `Token {{ kind: null }}`"
    )
    .unwrap();
    writeln!(s, " * rather than an in-band error variant.").unwrap();
    writeln!(s, " */").unwrap();
    writeln!(s, "export enum TokenKind {{").unwrap();
    writeln!(s, "  Eof = 0,").unwrap();
    for t in &st.tokens {
        writeln!(s, "  {} = {},", pascal(&t.name), t.kind).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "/** Human-readable name for a token kind, for diagnostics. */"
    )
    .unwrap();
    writeln!(s, "export function tokenKindName(k: TokenKind): string {{").unwrap();
    writeln!(s, "  switch (k) {{").unwrap();
    writeln!(s, "    case TokenKind.Eof: return \"EOF\";").unwrap();
    for t in &st.tokens {
        writeln!(
            s,
            "    case TokenKind.{}: return \"{}\";",
            pascal(&t.name),
            t.name
        )
        .unwrap();
    }
    writeln!(s, "    default: return \"?\";").unwrap();
    writeln!(s, "  }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "/**").unwrap();
    writeln!(
        s,
        " * One variant per non-fragment grammar rule. Attached to enter/exit"
    )
    .unwrap();
    writeln!(
        s,
        " * events so consumers can identify the rule a subtree corresponds to."
    )
    .unwrap();
    writeln!(s, " */").unwrap();
    writeln!(s, "export enum RuleKind {{").unwrap();
    for (i, n) in st.rule_kinds.iter().enumerate() {
        writeln!(s, "  {} = {},", pascal(n), i).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "/** Human-readable name for a rule kind, for diagnostics. */"
    )
    .unwrap();
    writeln!(s, "export function ruleKindName(k: RuleKind): string {{").unwrap();
    writeln!(s, "  switch (k) {{").unwrap();
    for n in &st.rule_kinds {
        writeln!(s, "    case RuleKind.{}: return \"{}\";", pascal(n), n).unwrap();
    }
    writeln!(s, "    default: return \"?\";").unwrap();
    writeln!(s, "  }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    // ---- LabelKind ------------------------------------------------------
    writeln!(s, "/**").unwrap();
    writeln!(s, " * One variant per distinct grammar label (`name:NAME` form).").unwrap();
    writeln!(s, " *").unwrap();
    writeln!(
        s,
        " * `Token.label` is `LabelKind | null`. Compare against named values:"
    )
    .unwrap();
    writeln!(
        s,
        " * `tok.label === LabelKind.Foo` — no string handling required."
    )
    .unwrap();
    writeln!(s, " */").unwrap();
    writeln!(s, "export enum LabelKind {{").unwrap();
    for (i, n) in st.labels.iter().enumerate() {
        writeln!(s, "  {} = {},", pascal(n), i + 1).unwrap();
    }
    if st.labels.is_empty() {
        writeln!(s, "  _Empty = 0xFFFF,").unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "/** Human-readable name for a label kind, for diagnostics. */"
    )
    .unwrap();
    writeln!(s, "export function labelKindName(k: LabelKind): string {{").unwrap();
    writeln!(s, "  switch (k) {{").unwrap();
    for n in &st.labels {
        writeln!(s, "    case LabelKind.{}: return \"{}\";", pascal(n), n).unwrap();
    }
    if st.labels.is_empty() {
        writeln!(s, "    case LabelKind._Empty: return \"\";").unwrap();
    }
    writeln!(s, "    default: return \"?\";").unwrap();
    writeln!(s, "  }}").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn token_variant(st: &StateTable, kind: u16) -> String {
    if kind == 0 {
        return "TokenKind.Eof".to_string();
    }
    match st.tokens.iter().find(|t| t.kind == kind) {
        Some(t) => format!("TokenKind.{}", pascal(&t.name)),
        None => panic!(
            "unknown token id {} while emitting TypeScript backend",
            kind
        ),
    }
}

/// Decide how a `Star`/`Opt` test should read the FIRST set.
///
/// For LL(1) the FIRST set is a flat list of single tokens — inline
/// them as a chain of `look(0).kind === T` comparisons so codegen can
/// drop the constant table entirely (matching the Rust backend's
/// `kind_pattern` path). For LL(k>1) we still consult the emitted
/// FIRST_n constant via `matchesFirst`.
fn first_set_test(st: &StateTable, first: u32) -> String {
    if st.k == 1 {
        let f = &st.first_sets[first as usize];
        let mut kinds: Vec<u16> = f
            .seqs
            .iter()
            .map(|seq| {
                debug_assert_eq!(seq.len(), 1, "first_set_test expects LL(1) singletons");
                seq[0]
            })
            .collect();
        kinds.sort_unstable();
        kinds.dedup();
        let parts: Vec<String> = kinds
            .iter()
            .map(|k| format!("p.look(0).kind === {}", token_variant(st, *k)))
            .collect();
        parts.join(" || ")
    } else {
        format!("p.matchesFirst(FIRST_{})", first)
    }
}

fn rule_variant(st: &StateTable, kind: u16) -> String {
    let name = st.rule_kinds.get(kind as usize).unwrap_or_else(|| {
        panic!(
            "unknown rule kind id {} while emitting TypeScript backend",
            kind
        )
    });
    format!("RuleKind.{}", pascal(name))
}

fn emit_dfa(s: &mut String, st: &StateTable) {
    writeln!(s, "/**").unwrap();
    writeln!(
        s,
        " * Scan `buf[start:]` for the longest accepted token in `mode`."
    )
    .unwrap();
    writeln!(
        s,
        " * Returns the best match and how many bytes were scanned (so the"
    )
    .unwrap();
    writeln!(s, " * lexer can detect buffer exhaustion mid-token).").unwrap();
    writeln!(s, " *").unwrap();
    writeln!(
        s,
        " * Branches on `mode` and falls into the per-mode helper. Single-mode"
    )
    .unwrap();
    writeln!(
        s,
        " * grammars collapse to a direct call so the dispatch inlines away."
    )
    .unwrap();
    writeln!(s, " */").unwrap();
    writeln!(
        s,
        "function longestMatch(buf: string, start: number, mode: number): DfaMatch<TokenKind> {{"
    )
    .unwrap();
    if st.modes.len() == 1 {
        writeln!(s, "  void mode;").unwrap();
        writeln!(s, "  return longestMatchMode0(buf, start);").unwrap();
    } else {
        writeln!(s, "  switch (mode) {{").unwrap();
        for m in &st.modes {
            writeln!(
                s,
                "    case {}: return longestMatchMode{}(buf, start);",
                m.id, m.id
            )
            .unwrap();
        }
        writeln!(
            s,
            "    default: return {{ bestLen: 0, bestKind: null, scanned: 0 }};"
        )
        .unwrap();
        writeln!(s, "  }}").unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    for m in &st.modes {
        writeln!(
            s,
            "/** Longest-match helper for lexer mode `{}` (id {}). */",
            m.name, m.id
        )
        .unwrap();
        writeln!(
            s,
            "function longestMatchMode{}(buf: string, start: number): DfaMatch<TokenKind> {{",
            m.id
        )
        .unwrap();
        writeln!(s, "  let pos = start;").unwrap();
        writeln!(s, "  let bestLen = 0;").unwrap();
        writeln!(s, "  let bestKind: TokenKind | null = null;").unwrap();
        writeln!(s, "  let state = {};", START).unwrap();
        writeln!(s, "  for (;;) {{").unwrap();
        writeln!(s, "    switch (state) {{").unwrap();
        for ds in &m.dfa { emit_dfa_state_arm(s, st, ds, m.id); }
        writeln!(
            s,
            "      default: return {{ bestLen, bestKind, scanned: pos - start }};"
        )
        .unwrap();
        writeln!(s, "    }}").unwrap();
        writeln!(s, "  }}").unwrap();
        writeln!(s, "}}").unwrap();
        writeln!(s).unwrap();
    }

    write!(
        s,
        "export const SKIP_KINDS: ReadonlySet<TokenKind> = new Set(["
    )
    .unwrap();
    let mut first = true;
    for t in &st.tokens {
        if t.skip {
            if !first {
                s.push_str(", ");
            }
            first = false;
            write!(s, "{}", token_variant(st, t.kind)).unwrap();
        }
    }
    writeln!(s, "]);").unwrap();
    writeln!(s).unwrap();

    // Per-state sticky regex used by the self-loop scan-skip prologue.
    // Sets `lastIndex = pos`, runs `.test()` once; on a match the regex
    // bumps `lastIndex` past the entire run, and the prologue copies
    // it back into `pos`. Irregexp scans these classes with its native
    // SIMD primitives, so a 64 KiB whitespace run becomes one tight
    // bulk loop instead of one switch dispatch per byte. Qualified by
    // mode id because DFA state ids are per-mode and would otherwise
    // collide across modes.
    for m in &st.modes {
        for ds in &m.dfa {
            let self_loop = ds.self_loop_ranges();
            if !self_loop.is_empty() {
                writeln!(
                    s,
                    "const SKIP_M{}_S{} = /[{}]+/y;",
                    m.id,
                    ds.id,
                    regex_class(self_loop)
                )
                .unwrap();
            }
        }
    }
    writeln!(s).unwrap();
}

fn regex_class(ranges: &[(u8, u8)]) -> String {
    let mut out = String::new();
    for &(lo, hi) in ranges {
        if lo == hi {
            out.push_str(&regex_byte(lo));
        } else {
            out.push_str(&regex_byte(lo));
            out.push('-');
            out.push_str(&regex_byte(hi));
        }
    }
    out
}

fn regex_byte(b: u8) -> String {
    // Always emit `\xHH`. Escapes the regex-class metacharacters
    // (`]`, `^`, `-`, `\`) implicitly because they're never < 0x80
    // taken alone — the hex form sidesteps the question entirely.
    format!("\\x{:02x}", b)
}

fn emit_dfa_state_arm(
    s: &mut String,
    st: &StateTable,
        ds: &DfaState,
    mode_id: u32,
) {
    if ds.arms.is_empty() {
        writeln!(
            s,
            "      case {}: return {{ bestLen, bestKind, scanned: pos - start }};",
            ds.id
        )
        .unwrap();
        return;
    }
    writeln!(s, "      case {}: {{", ds.id).unwrap();
    if !ds.self_loop_ranges().is_empty() {
        writeln!(s, "        SKIP_M{}_S{}.lastIndex = pos;", mode_id, ds.id).unwrap();
        writeln!(
            s,
            "        if (SKIP_M{m}_S{n}.test(buf)) pos = SKIP_M{m}_S{n}.lastIndex;",
            m = mode_id,
            n = ds.id
        )
        .unwrap();
        if let Some(kind) = ds.accept {
            writeln!(s, "        bestLen = pos - start;").unwrap();
            writeln!(
                s,
                "        bestKind = {};",
                token_variant(st, kind)
            )
            .unwrap();
        }
    }
    writeln!(
        s,
        "        if (pos >= buf.length) return {{ bestLen, bestKind, scanned: pos - start }};"
    )
    .unwrap();
    writeln!(s, "        const b = buf.charCodeAt(pos);").unwrap();
    let mut first = true;
    for arm in &ds.arms {
        let cond = byte_cond(&arm.ranges);
        let kw = if first { "if" } else { "else if" };
        first = false;
        write!(
            s,
            "        {} ({}) {{ pos++; state = {};",
            kw, cond, arm.target
        )
        .unwrap();
        if let Some(kind) = arm.target_accept {
            write!(
                s,
                " bestLen = pos - start; bestKind = {};",
                token_variant(st, kind)
            )
            .unwrap();
        }
        writeln!(s, " }}").unwrap();
    }
    writeln!(
        s,
        "        else return {{ bestLen, bestKind, scanned: pos - start }};"
    )
    .unwrap();
    writeln!(s, "        break;").unwrap();
    writeln!(s, "      }}").unwrap();
}


fn byte_cond(ranges: &[(u8, u8)]) -> String {
    let terms: Vec<String> = ranges
        .iter()
        .map(|(lo, hi)| {
            if lo == hi {
                format!("b === 0x{:02x}", lo)
            } else {
                format!("(b >= 0x{:02x} && b <= 0x{:02x})", lo, hi)
            }
        })
        .collect();
    terms.join(" || ")
}

fn emit_tables(s: &mut String, st: &StateTable) {
    writeln!(s, "const K = {};", st.k).unwrap();
    for (name, id) in &st.entry_states {
        writeln!(s, "const ENTRY_{} = {};", name.to_uppercase(), id).unwrap();
    }

    for f in &st.first_sets {
        if !f.has_references {
            continue;
        }
        let seqs: Vec<String> = f
            .seqs
            .iter()
            .map(|seq| {
                format!(
                    "[{}]",
                    seq.iter()
                        .map(|t| token_variant(st, *t))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            })
            .collect();
        writeln!(
            s,
            "const FIRST_{}: readonly (readonly TokenKind[])[] = [{}];",
            f.id,
            seqs.join(", ")
        )
        .unwrap();
    }
    for f in &st.sync_sets {
        writeln!(
            s,
            "const SYNC_{}: readonly TokenKind[] = [{}];",
            f.id,
            f.kinds
                .iter()
                .map(|t| token_variant(st, *t))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    writeln!(s).unwrap();
}

fn emit_drive(s: &mut String, st: &StateTable) {
    writeln!(
        s,
        "function step(p: Cursor<TokenKind, RuleKind, LabelKind>): Event<TokenKind, RuleKind, LabelKind> | undefined {{"
    )
    .unwrap();
    writeln!(s, "  let cur = p.getState();").unwrap();
    writeln!(s, "  let event: Event<TokenKind, RuleKind, LabelKind> | undefined = undefined;").unwrap();
    writeln!(s, "  switch (cur) {{").unwrap();
    for state in st.states.values() {
        writeln!(s, "    case {}: {{ // {}", state.id, state.label).unwrap();
        emit_body(s, st, &state.body, "      ");
        writeln!(s, "      break;").unwrap();
        writeln!(s, "    }}").unwrap();
    }
    writeln!(
        s,
        "    default: throw new Error(`unknown state ${{cur}}`);"
    )
    .unwrap();
    writeln!(s, "  }}").unwrap();
    writeln!(s, "  p.setState(cur);").unwrap();
    writeln!(s, "  return event;").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_instr(s: &mut String, st: &StateTable, op: &Instr) {
    match op {
        Instr::Enter(k) => {
            writeln!(s, "      event = p.enter({});", rule_variant(st, *k)).unwrap();
        }
        Instr::Exit(k) => {
            writeln!(s, "      event = p.exit({});", rule_variant(st, *k)).unwrap();
        }
        Instr::Expect {
            kind,
            token_name,
            sync,
            label,
        } => {
            let label_arg = match label {
                Some(id) => format!(
                    "LabelKind.{}",
                    pascal(&st.labels[(*id as usize) - 1])
                ),
                None => "null".to_string(),
            };
            writeln!(
                s,
                "      event = p.tryConsume({}, SYNC_{}, \"expected {}\", {});",
                token_variant(st, *kind),
                sync,
                token_name,
                label_arg,
            )
            .unwrap();
        }
        Instr::PushRet(r) => {
            writeln!(s, "      p.pushRet({});", r).unwrap();
        }
    }
}

fn emit_tail(s: &mut String, st: &StateTable, tail: &Tail) {
    match tail {
        Tail::Jump(n) => {
            writeln!(s, "      cur = {};", n).unwrap();
        }
        Tail::Ret => {
            writeln!(s, "      cur = p.popRet();").unwrap();
        }
        Tail::Star { first, body, cont, head } => {
            writeln!(s, "      if ({}) {{", first_set_test(st, *first)).unwrap();
            writeln!(s, "        p.pushRet({});", head).unwrap();
            emit_body(s, st, body, "        ");
            writeln!(s, "      }}").unwrap();
            match cont {
                Some(n) => writeln!(s, "      else cur = {};", n).unwrap(),
                None => writeln!(s, "      else cur = p.popRet();").unwrap(),
            }
        }
        Tail::Opt { first, body, cont } => {
            writeln!(s, "      if ({}) {{", first_set_test(st, *first)).unwrap();
            if let Some(n) = cont {
                writeln!(s, "        p.pushRet({});", n).unwrap();
            }
            emit_body(s, st, body, "        ");
            writeln!(s, "      }}").unwrap();
            match cont {
                Some(n) => writeln!(s, "      else cur = {};", n).unwrap(),
                None => writeln!(s, "      else cur = p.popRet();").unwrap(),
            }
        }
        Tail::Dispatch {
            tree,
            sync,
            cont,
            insertions,
        } => {
            emit_dispatch_tree(s, st, tree, *sync, *cont, insertions, "      ");
        }
    }
}

fn emit_body(s: &mut String, st: &StateTable, body: &Body, _ind: &str) {
    for op in &body.instrs {
        emit_instr(s, st, op);
    }
    emit_tail(s, st, &body.tail);
}

fn emit_dispatch_tree(
    s: &mut String,
    st: &StateTable,
    tree: &DispatchTree,
    sync: u32,
    cont: Option<u32>,
    insertions: &[Insertion],
    ind: &str,
) {
    match tree {
        DispatchTree::Leaf(leaf) => emit_dispatch_leaf_block(s, st, leaf, sync, cont, &[], ind),
        DispatchTree::Switch {
            depth,
            arms,
            default,
        } => {
            // Insertion arms only flow at depth 0; nested sub-trees
            // can't contribute new `look[0]` candidates.
            let inner_inserts: &[Insertion] = if *depth == 0 { insertions } else { &[] };

            writeln!(s, "{}switch (p.look({}).kind) {{", ind, depth).unwrap();
            let inner = format!("{}  ", ind);
            for (kind, sub) in arms {
                let pat = token_variant(st, *kind);
                writeln!(s, "{}case {}: {{", inner, pat).unwrap();
                emit_dispatch_tree(s, st, sub, sync, cont, &[], &format!("{}  ", inner));
                writeln!(s, "{}  break;", inner).unwrap();
                writeln!(s, "{}}}", inner).unwrap();
            }
            writeln!(s, "{}default: {{", inner).unwrap();
            emit_dispatch_leaf_block(
                s,
                st,
                default,
                sync,
                cont,
                inner_inserts,
                &format!("{}  ", inner),
            );
            writeln!(s, "{}  break;", inner).unwrap();
            writeln!(s, "{}}}", inner).unwrap();
            writeln!(s, "{}}}", ind).unwrap();
        }
    }
}

fn emit_insertion(s: &mut String, st: &StateTable, ins: &Insertion, ind: &str) {
    let cond = ins
        .kinds_to_match
        .iter()
        .map(|k| format!("look0 === {}", token_variant(st, *k)))
        .collect::<Vec<_>>()
        .join(" || ");
    writeln!(s, "{}if ({}) {{", ind, cond).unwrap();
    let inner = format!("{}  ", ind);
    match &ins.post_first {
        PostFirst::Jump(n) => {
            writeln!(s, "{}cur = {};", inner, n).unwrap();
        }
        PostFirst::PushAndJump { push, jump } => {
            writeln!(s, "{}p.pushRet({});", inner, push).unwrap();
            writeln!(s, "{}cur = {};", inner, jump).unwrap();
        }
        PostFirst::Cont(c) => {
            writeln!(s, "{}cur = {};", inner, c).unwrap();
        }
        PostFirst::TailReturn => {
            writeln!(s, "{}cur = p.popRet();", inner).unwrap();
        }
    }
    writeln!(
        s,
        "{}event = p.errorHere(\"expected {}\");",
        inner, ins.token_name
    )
    .unwrap();
    writeln!(s, "{}}} else ", ind).unwrap();
}

fn emit_dispatch_leaf_block(
    s: &mut String,
    st: &StateTable,
    leaf: &DispatchLeaf,
    sync: u32,
    cont: Option<u32>,
    insertions: &[Insertion],
    ind: &str,
) {
    match (leaf, cont) {
        (DispatchLeaf::Arm(b), Some(n)) => {
            writeln!(s, "{}p.pushRet({});", ind, n).unwrap();
            emit_body(s, st, b, ind);
        }
        (DispatchLeaf::Arm(b), None) => emit_body(s, st, b, ind),
        (DispatchLeaf::Fallthrough, Some(n)) => writeln!(s, "{}cur = {};", ind, n).unwrap(),
        (DispatchLeaf::Fallthrough, None) => writeln!(s, "{}cur = p.popRet();", ind).unwrap(),
        (DispatchLeaf::Error, _) => {
            // Insertion-recovery: try each arm's "I'd accept this if
            // my first token had been there" set. The dispatch's
            // primary arms already matched first via the outer
            // switch, so any look[0] reaching this branch is by
            // definition *not* a primary kind.
            if !insertions.is_empty() {
                writeln!(s, "{}const look0 = p.look(0).kind;", ind).unwrap();
                for ins in insertions {
                    emit_insertion(s, st, ins, ind);
                }
            }
            writeln!(s, "{}{{", ind).unwrap();
            let inner = format!("{}  ", ind);
            match cont {
                Some(n) => {
                    writeln!(s, "{}cur = {};", inner, n).unwrap();
                    writeln!(s, "{}event = p.errorHere(\"unexpected token\");", inner).unwrap();
                    writeln!(s, "{}p.recoverTo(SYNC_{});", inner, sync).unwrap();
                }
                None => {
                    writeln!(s, "{}event = p.errorHere(\"unexpected token\");", inner).unwrap();
                    writeln!(s, "{}p.recoverTo(SYNC_{});", inner, sync).unwrap();
                    writeln!(s, "{}cur = p.popRet();", inner).unwrap();
                }
            }
            writeln!(s, "{}}}", ind).unwrap();
        }
    }
}

fn emit_apply_actions(s: &mut String, st: &StateTable) {
    use crate::lowering::ModeActionInfo;

    let action_tokens: Vec<&crate::lowering::TokenInfo> = st
        .tokens
        .iter()
        .filter(|t| !t.mode_actions.is_empty())
        .collect();

    writeln!(s, "/**").unwrap();
    writeln!(
        s,
        " * Apply per-token mode-stack actions to `lex`. Generated as a"
    )
    .unwrap();
    writeln!(
        s,
        " * switch over token kinds; tokens without `-> push/pop` fall through."
    )
    .unwrap();
    writeln!(s, " */").unwrap();
    writeln!(
        s,
        "function applyActions(kind: TokenKind | null, lex: Lexer<TokenKind, LabelKind>): void {{"
    )
    .unwrap();
    if action_tokens.is_empty() {
        writeln!(s, "  void kind;").unwrap();
        writeln!(s, "  void lex;").unwrap();
    } else {
        writeln!(s, "  switch (kind) {{").unwrap();
        for t in &action_tokens {
            writeln!(s, "    case {}:", token_variant(st, t.kind)).unwrap();
            for action in &t.mode_actions {
                match action {
                    ModeActionInfo::Push(id) => {
                        writeln!(s, "      lex.pushMode({});", id).unwrap();
                    }
                    ModeActionInfo::Pop => {
                        writeln!(s, "      lex.popMode();").unwrap();
                    }
                }
            }
            writeln!(s, "      break;").unwrap();
        }
        writeln!(s, "    default: break;").unwrap();
        writeln!(s, "  }}").unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
}

fn emit_public_api(s: &mut String, st: &StateTable) {
    emit_apply_actions(s, st);
    writeln!(
        s,
        "const PARSER_CONFIG = {{ k: K, eofKind: TokenKind.Eof, isSkip: (k: TokenKind) => SKIP_KINDS.has(k), step, applyActions }};"
    )
    .unwrap();
    writeln!(s).unwrap();
    for (name, _) in &st.entry_states {
        let pascal_name = pascal(name);
        let upper = name.to_uppercase();

        writeln!(
            s,
            "/** Parse the `{name}` rule from a source string. `options.emitSkips` (default `true`) controls whether skip tokens (whitespace, comments) reach the consumer; `options.emitUnlabeledTokens` (default `true`) controls whether tokens without a `name:NAME` label do. Pass `{{ emitSkips: false, emitUnlabeledTokens: false }}` for an AST-shaped event stream that only surfaces labelled positions. */"
        )
        .unwrap();
        writeln!(
            s,
            "export function parse{pascal_name}(src: string, options?: {{ emitSkips?: boolean; emitUnlabeledTokens?: boolean }}): Parser<TokenKind, RuleKind, LabelKind> {{"
        )
        .unwrap();
        writeln!(
            s,
            "  const lex = new Lexer<TokenKind, LabelKind>(src, longestMatch, TokenKind.Eof);"
        )
        .unwrap();
        writeln!(
            s,
            "  return new Parser<TokenKind, RuleKind, LabelKind>(lex, ENTRY_{upper}, PARSER_CONFIG, options);"
        )
        .unwrap();
        writeln!(s, "}}").unwrap();
        writeln!(s).unwrap();
    }
}
