//! Generated by parsuna — do not edit by hand.
//!
//! Pull-based, recoverable parser. Call one of the `parse_*_from_str` /
//! `parse_*_from_reader` constructors and iterate the resulting [`Parser`]
//! to walk the parse as a flat [`Event`] stream.
#![allow(dead_code, unused_imports)]

use std::io::Read;
use parsuna_rt::{DfaMatch, DfaMatcher, LexerBackend, Scanner, StreamingLexer, TERMINATED};

/// The set of token kinds this grammar can emit.
///
/// `Eof` marks end-of-input; the other variants come from the grammar's
/// `token` declarations. Lex failures (no pattern matched) are surfaced
/// as `Token { kind: None }` rather than an in-band error variant.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum TokenKind {
    Eof = 0,
    Lparen = 1,
    Rparen = 2,
    Lbrack = 3,
    Rbrack = 4,
    Comma = 5,
    Eq = 6,
    Semi = 7,
    Pipe = 8,
    Question = 9,
    Star = 10,
    Plus = 11,
    Dotdot = 12,
    Dot = 13,
    Bang = 14,
    String = 15,
    Char = 16,
    Ident = 17,
    Ws = 18,
    Comment = 19,
}

impl TokenKind {
    /// Numeric discriminant, equal to `self as u16`.
    pub const fn id(self) -> u16 { self as u16 }
}

impl parsuna_rt::TokenKindEnum for TokenKind {
    fn name(self) -> &'static str {
        match self {
            TokenKind::Eof => "EOF",
            TokenKind::Lparen => "LPAREN",
            TokenKind::Rparen => "RPAREN",
            TokenKind::Lbrack => "LBRACK",
            TokenKind::Rbrack => "RBRACK",
            TokenKind::Comma => "COMMA",
            TokenKind::Eq => "EQ",
            TokenKind::Semi => "SEMI",
            TokenKind::Pipe => "PIPE",
            TokenKind::Question => "QUESTION",
            TokenKind::Star => "STAR",
            TokenKind::Plus => "PLUS",
            TokenKind::Dotdot => "DOTDOT",
            TokenKind::Dot => "DOT",
            TokenKind::Bang => "BANG",
            TokenKind::String => "STRING",
            TokenKind::Char => "CHAR",
            TokenKind::Ident => "IDENT",
            TokenKind::Ws => "WS",
            TokenKind::Comment => "COMMENT",
        }
    }
    const EOF: Self = Self::Eof;
}

/// One variant per non-fragment rule in the grammar.
///
/// Attached to [`Event::Enter`] and [`Event::Exit`] so consumers can
/// tell which rule a subtree corresponds to.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum RuleKind {
    AltExpr = 0,
    Annot = 1,
    Annots = 2,
    Atom = 3,
    CharPrimary = 4,
    Decl = 5,
    File = 6,
    Group = 7,
    NegClass = 8,
    SeqExpr = 9,
}

impl RuleKind {
    /// Numeric discriminant, equal to `self as u16`.
    pub const fn id(self) -> u16 { self as u16 }
}

impl parsuna_rt::RuleKindEnum for RuleKind {
    fn name(self) -> &'static str {
        match self {
            RuleKind::AltExpr => "alt_expr",
            RuleKind::Annot => "annot",
            RuleKind::Annots => "annots",
            RuleKind::Atom => "atom",
            RuleKind::CharPrimary => "char_primary",
            RuleKind::Decl => "decl",
            RuleKind::File => "file",
            RuleKind::Group => "group",
            RuleKind::NegClass => "neg_class",
            RuleKind::SeqExpr => "seq_expr",
        }
    }
}



/// Re-exports of the runtime types used by this parser.
pub use parsuna_rt::{Span, Pos, Error};
/// Parse event carrying this grammar's token and rule kinds.
pub type Event<'a> = parsuna_rt::Event<'a, TokenKind, RuleKind>;
/// A lexed token with this grammar's [`TokenKind`].
pub type Token<'a> = parsuna_rt::Token<'a, TokenKind>;


/// Compiled lexer DFA for this grammar.
///
/// Zero-sized type whose [`DfaMatcher`] impl drives the lexer via a
/// per-state `match` rather than a transition table. Generated code
/// supplies this to [`Scanner`]/[`StreamingLexer`].
pub struct LexerDfa;

impl DfaMatcher<TokenKind> for LexerDfa {
    #[inline]
    fn longest_match(buf: &[u8], start: usize) -> DfaMatch<TokenKind> {
        let mut pos = start;
        let mut best_len: usize = 0;
        let mut best_kind: Option<TokenKind> = None;
        let mut state: u32 = 1;
        loop {
            match state {
                1 => match buf.get(pos) {
                    Some(&b'\'') => { pos += 1; state = 2; }
                    Some(&b'"') => { pos += 1; state = 3; }
                    Some(&b'/') => { pos += 1; state = 7; }
                    Some(&b'(') => { pos += 1; state = 35; best_len = pos - start; best_kind = Some(TokenKind::Lparen); }
                    Some(&b')') => { pos += 1; state = 36; best_len = pos - start; best_kind = Some(TokenKind::Rparen); }
                    Some(&b'[') => { pos += 1; state = 37; best_len = pos - start; best_kind = Some(TokenKind::Lbrack); }
                    Some(&b']') => { pos += 1; state = 38; best_len = pos - start; best_kind = Some(TokenKind::Rbrack); }
                    Some(&b',') => { pos += 1; state = 39; best_len = pos - start; best_kind = Some(TokenKind::Comma); }
                    Some(&b'=') => { pos += 1; state = 40; best_len = pos - start; best_kind = Some(TokenKind::Eq); }
                    Some(&b';') => { pos += 1; state = 41; best_len = pos - start; best_kind = Some(TokenKind::Semi); }
                    Some(&b'|') => { pos += 1; state = 42; best_len = pos - start; best_kind = Some(TokenKind::Pipe); }
                    Some(&b'?') => { pos += 1; state = 43; best_len = pos - start; best_kind = Some(TokenKind::Question); }
                    Some(&b'*') => { pos += 1; state = 44; best_len = pos - start; best_kind = Some(TokenKind::Star); }
                    Some(&b'+') => { pos += 1; state = 45; best_len = pos - start; best_kind = Some(TokenKind::Plus); }
                    Some(&b'.') => { pos += 1; state = 47; best_len = pos - start; best_kind = Some(TokenKind::Dot); }
                    Some(&b'!') => { pos += 1; state = 48; best_len = pos - start; best_kind = Some(TokenKind::Bang); }
                    Some(&(b'A'..=b'Z' | b'_' | b'a'..=b'z')) => { pos += 1; state = 51; best_len = pos - start; best_kind = Some(TokenKind::Ident); }
                    Some(&(b'\t'..=b'\n' | b'\r' | b' ')) => { pos += 1; state = 52; best_len = pos - start; best_kind = Some(TokenKind::Ws); }
                    _ => break,
                },
                2 => match buf.get(pos) {
                    Some(&b'\\') => { pos += 1; state = 5; }
                    Some(&(0x00..=b'\t' | 0x0b..=b'&' | b'('..=b'[' | b']'..=0x7f)) => { pos += 1; state = 6; }
                    Some(&(0xc2..=0xdf)) => { pos += 1; state = 15; }
                    Some(&(0xe1..=0xec | 0xee..=0xef)) => { pos += 1; state = 17; }
                    Some(&(0xf1..=0xf3)) => { pos += 1; state = 19; }
                    Some(&0xed) => { pos += 1; state = 23; }
                    Some(&0xf4) => { pos += 1; state = 26; }
                    Some(&0xf0) => { pos += 1; state = 30; }
                    Some(&0xe0) => { pos += 1; state = 33; }
                    _ => break,
                },
                3 => {
                    while let Some(&b) = buf.get(pos) {
                        if !matches!(b, 0x00..=b'\t' | 0x0b..=b'!' | b'#'..=b'[' | b']'..=0x7f) { break; }
                        pos += 1;
                    }
                    match buf.get(pos) {
                        Some(&(0x00..=b'\t' | 0x0b..=b'!' | b'#'..=b'[' | b']'..=0x7f)) => { pos += 1; state = 3; }
                        Some(&b'\\') => { pos += 1; state = 4; }
                        Some(&(0xc2..=0xdf)) => { pos += 1; state = 14; }
                        Some(&(0xe1..=0xec | 0xee..=0xef)) => { pos += 1; state = 16; }
                        Some(&(0xf1..=0xf3)) => { pos += 1; state = 18; }
                        Some(&0xed) => { pos += 1; state = 22; }
                        Some(&0xf4) => { pos += 1; state = 25; }
                        Some(&0xf0) => { pos += 1; state = 29; }
                        Some(&0xe0) => { pos += 1; state = 32; }
                        Some(&b'"') => { pos += 1; state = 49; best_len = pos - start; best_kind = Some(TokenKind::String); }
                        _ => break,
                    }
                },
                4 => match buf.get(pos) {
                    Some(&(b'"' | b'\'' | b'0' | b'\\' | b'n' | b'r' | b't')) => { pos += 1; state = 3; }
                    Some(&b'u') => { pos += 1; state = 12; }
                    _ => break,
                },
                5 => match buf.get(pos) {
                    Some(&(b'"' | b'\'' | b'0' | b'\\' | b'n' | b'r' | b't')) => { pos += 1; state = 6; }
                    Some(&b'u') => { pos += 1; state = 13; }
                    _ => break,
                },
                6 => match buf.get(pos) {
                    Some(&b'\'') => { pos += 1; state = 50; best_len = pos - start; best_kind = Some(TokenKind::Char); }
                    _ => break,
                },
                7 => match buf.get(pos) {
                    Some(&b'/') => { pos += 1; state = 53; best_len = pos - start; best_kind = Some(TokenKind::Comment); }
                    _ => break,
                },
                8 => {
                    while let Some(&b) = buf.get(pos) {
                        if !matches!(b, b'0'..=b'9' | b'A'..=b'F' | b'a'..=b'f') { break; }
                        pos += 1;
                    }
                    match buf.get(pos) {
                        Some(&b'}') => { pos += 1; state = 3; }
                        Some(&(b'0'..=b'9' | b'A'..=b'F' | b'a'..=b'f')) => { pos += 1; state = 8; }
                        _ => break,
                    }
                },
                9 => {
                    while let Some(&b) = buf.get(pos) {
                        if !matches!(b, b'0'..=b'9' | b'A'..=b'F' | b'a'..=b'f') { break; }
                        pos += 1;
                    }
                    match buf.get(pos) {
                        Some(&b'}') => { pos += 1; state = 6; }
                        Some(&(b'0'..=b'9' | b'A'..=b'F' | b'a'..=b'f')) => { pos += 1; state = 9; }
                        _ => break,
                    }
                },
                10 => match buf.get(pos) {
                    Some(&(b'0'..=b'9' | b'A'..=b'F' | b'a'..=b'f')) => { pos += 1; state = 8; }
                    _ => break,
                },
                11 => match buf.get(pos) {
                    Some(&(b'0'..=b'9' | b'A'..=b'F' | b'a'..=b'f')) => { pos += 1; state = 9; }
                    _ => break,
                },
                12 => match buf.get(pos) {
                    Some(&b'{') => { pos += 1; state = 10; }
                    _ => break,
                },
                13 => match buf.get(pos) {
                    Some(&b'{') => { pos += 1; state = 11; }
                    _ => break,
                },
                14 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 3; }
                    _ => break,
                },
                15 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 6; }
                    _ => break,
                },
                16 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 14; }
                    _ => break,
                },
                17 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 15; }
                    _ => break,
                },
                18 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 16; }
                    _ => break,
                },
                19 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 17; }
                    _ => break,
                },
                20 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 21; }
                    _ => break,
                },
                21 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 28; }
                    _ => break,
                },
                22 => match buf.get(pos) {
                    Some(&(0x80..=0x9f)) => { pos += 1; state = 14; }
                    _ => break,
                },
                23 => match buf.get(pos) {
                    Some(&(0x80..=0x9f)) => { pos += 1; state = 15; }
                    _ => break,
                },
                24 => match buf.get(pos) {
                    Some(&(0x80..=0x9f)) => { pos += 1; state = 28; }
                    _ => break,
                },
                25 => match buf.get(pos) {
                    Some(&(0x80..=0x8f)) => { pos += 1; state = 16; }
                    _ => break,
                },
                26 => match buf.get(pos) {
                    Some(&(0x80..=0x8f)) => { pos += 1; state = 17; }
                    _ => break,
                },
                27 => match buf.get(pos) {
                    Some(&(0x80..=0x8f)) => { pos += 1; state = 21; }
                    _ => break,
                },
                28 => match buf.get(pos) {
                    Some(&(0x80..=0xbf)) => { pos += 1; state = 53; best_len = pos - start; best_kind = Some(TokenKind::Comment); }
                    _ => break,
                },
                29 => match buf.get(pos) {
                    Some(&(0x90..=0xbf)) => { pos += 1; state = 16; }
                    _ => break,
                },
                30 => match buf.get(pos) {
                    Some(&(0x90..=0xbf)) => { pos += 1; state = 17; }
                    _ => break,
                },
                31 => match buf.get(pos) {
                    Some(&(0x90..=0xbf)) => { pos += 1; state = 21; }
                    _ => break,
                },
                32 => match buf.get(pos) {
                    Some(&(0xa0..=0xbf)) => { pos += 1; state = 14; }
                    _ => break,
                },
                33 => match buf.get(pos) {
                    Some(&(0xa0..=0xbf)) => { pos += 1; state = 15; }
                    _ => break,
                },
                34 => match buf.get(pos) {
                    Some(&(0xa0..=0xbf)) => { pos += 1; state = 28; }
                    _ => break,
                },
                35 => break,
                36 => break,
                37 => break,
                38 => break,
                39 => break,
                40 => break,
                41 => break,
                42 => break,
                43 => break,
                44 => break,
                45 => break,
                46 => break,
                47 => match buf.get(pos) {
                    Some(&b'.') => { pos += 1; state = 46; best_len = pos - start; best_kind = Some(TokenKind::Dotdot); }
                    _ => break,
                },
                48 => break,
                49 => break,
                50 => break,
                51 => {
                    while let Some(&b) = buf.get(pos) {
                        if !matches!(b, b'0'..=b'9' | b'A'..=b'Z' | b'_' | b'a'..=b'z') { break; }
                        pos += 1;
                    }
                    best_len = pos - start;
                    best_kind = Some(TokenKind::Ident);
                    match buf.get(pos) {
                        Some(&(b'0'..=b'9' | b'A'..=b'Z' | b'_' | b'a'..=b'z')) => { pos += 1; state = 51; best_len = pos - start; best_kind = Some(TokenKind::Ident); }
                        _ => break,
                    }
                },
                52 => {
                    while let Some(&b) = buf.get(pos) {
                        if !matches!(b, b'\t'..=b'\n' | b'\r' | b' ') { break; }
                        pos += 1;
                    }
                    best_len = pos - start;
                    best_kind = Some(TokenKind::Ws);
                    match buf.get(pos) {
                        Some(&(b'\t'..=b'\n' | b'\r' | b' ')) => { pos += 1; state = 52; best_len = pos - start; best_kind = Some(TokenKind::Ws); }
                        _ => break,
                    }
                },
                53 => {
                    while let Some(&b) = buf.get(pos) {
                        if !matches!(b, 0x00..=b'\t' | 0x0b..=0x7f) { break; }
                        pos += 1;
                    }
                    best_len = pos - start;
                    best_kind = Some(TokenKind::Comment);
                    match buf.get(pos) {
                        Some(&(0xf1..=0xf3)) => { pos += 1; state = 20; }
                        Some(&(0xe1..=0xec | 0xee..=0xef)) => { pos += 1; state = 21; }
                        Some(&0xed) => { pos += 1; state = 24; }
                        Some(&0xf4) => { pos += 1; state = 27; }
                        Some(&(0xc2..=0xdf)) => { pos += 1; state = 28; }
                        Some(&0xf0) => { pos += 1; state = 31; }
                        Some(&0xe0) => { pos += 1; state = 34; }
                        Some(&(0x00..=b'\t' | 0x0b..=0x7f)) => { pos += 1; state = 53; best_len = pos - start; best_kind = Some(TokenKind::Comment); }
                        _ => break,
                    }
                },
                _ => break,
            }
        }
        DfaMatch { best_len, best_kind, scanned: pos - start }
    }
}


/// Lookahead required to disambiguate every alternative (LL(k)).
pub const K: usize = 1;
const ENTRY_FILE: u32 = 1;
const ENTRY_DECL: u32 = 5;
const ENTRY_ANNOTS: u32 = 11;
const ENTRY_ANNOT: u32 = 16;
const ENTRY_ALT_EXPR: u32 = 19;
const ENTRY_SEQ_EXPR: u32 = 22;
const ENTRY_GROUP: u32 = 27;
const ENTRY_ATOM: u32 = 31;
const ENTRY_CHAR_PRIMARY: u32 = 34;
const ENTRY_NEG_CLASS: u32 = 39;


static SYNC_0: &[TokenKind] = &[TokenKind::Eof];
static SYNC_1: &[TokenKind] = &[TokenKind::Eof, TokenKind::Ident];
static SYNC_2: &[TokenKind] = &[TokenKind::Eof, TokenKind::Rbrack, TokenKind::Comma, TokenKind::Ident];
static SYNC_3: &[TokenKind] = &[TokenKind::Eof, TokenKind::Lparen, TokenKind::Rparen, TokenKind::Lbrack, TokenKind::Semi, TokenKind::Pipe, TokenKind::Question, TokenKind::Star, TokenKind::Plus, TokenKind::Dot, TokenKind::Bang, TokenKind::String, TokenKind::Char, TokenKind::Ident];


/// Zero-sized marker type that carries the generated dispatch logic via
/// [`parsuna_rt::Grammar`]. You never construct one directly — it's a
/// type-level parameter to [`Parser`].
pub struct Grammar;

/// Parser alias pinning the grammar and lookahead. `L` is any
/// [`LexerBackend`]; the generated `parse_*_from_str`/`parse_*_from_reader`
/// helpers build a parser with either [`Scanner`] or [`StreamingLexer`].
pub type Parser<'a, L> = parsuna_rt::Parser<'a, L, K, Grammar>;
impl parsuna_rt::Grammar<K> for Grammar {
    type TokenKind = TokenKind;
    type RuleKind = RuleKind;
    const HAS_SKIPS: bool = true;

    #[inline(always)]
    fn is_skip(kind: TokenKind) -> bool {
        matches!(kind, TokenKind::Ws | TokenKind::Comment)
    }

    #[inline]
    fn step<'a, 'p, L: LexerBackend<'a, Self::TokenKind>>(p: &mut parsuna_rt::Cursor<'p, 'a, L, K, Self>) -> Option<parsuna_rt::Event<'a, TokenKind, RuleKind>> {
        let mut cur = p.state();
        let mut event: Option<parsuna_rt::Event<'a, TokenKind, RuleKind>> = None;
        match cur {
            1 => { // file:enter
                event = Some(p.enter(RuleKind::File));
                match p.look(0).kind {
                    Some(TokenKind::Ident) => {
                        p.push_ret(2);
                        cur = 4;
                    }
                    _ => {
                        cur = 3;
                    }
                }
            }
            2 => { // file:star
                match p.look(0).kind {
                    Some(TokenKind::Ident) => {
                        p.push_ret(2);
                        event = Some(p.enter(RuleKind::Decl));
                        cur = 6;
                    }
                    _ => {
                        cur = 3;
                    }
                }
            }
            3 => { // file:exit
                event = Some(p.exit(RuleKind::File));
                cur = p.ret();
            }
            4 => { // file:star-body:call:decl
                event = Some(p.enter(RuleKind::Decl));
                cur = 6;
            }
            5 => { // decl:enter
                event = Some(p.enter(RuleKind::Decl));
                cur = 6;
            }
            6 => { // decl:expect:IDENT
                event = Some(p.expect(TokenKind::Ident, SYNC_1, "expected IDENT"));
                cur = 7;
            }
            7 => { // decl:expect:EQ
                event = Some(p.expect(TokenKind::Eq, SYNC_1, "expected EQ"));
                p.push_ret(8);
                cur = 19;
            }
            8 => { // decl:opt
                match p.look(0).kind {
                    Some(TokenKind::Lbrack) => {
                        p.push_ret(9);
                        event = Some(p.enter(RuleKind::Annots));
                        cur = 12;
                    }
                    _ => {
                        cur = 9;
                    }
                }
            }
            9 => { // decl:expect:SEMI
                event = Some(p.expect(TokenKind::Semi, SYNC_1, "expected SEMI"));
                cur = 10;
            }
            10 => { // decl:exit
                event = Some(p.exit(RuleKind::Decl));
                cur = p.ret();
            }
            11 => { // annots:enter
                event = Some(p.enter(RuleKind::Annots));
                cur = 12;
            }
            12 => { // annots:expect:LBRACK
                event = Some(p.expect(TokenKind::Lbrack, SYNC_1, "expected LBRACK"));
                p.push_ret(13);
                cur = 16;
            }
            13 => { // annots:star
                match p.look(0).kind {
                    Some(TokenKind::Comma) => {
                        p.push_ret(13);
                        event = Some(p.expect(TokenKind::Comma, SYNC_1, "expected COMMA"));
                        cur = 16;
                    }
                    _ => {
                        cur = 14;
                    }
                }
            }
            14 => { // annots:expect:RBRACK
                event = Some(p.expect(TokenKind::Rbrack, SYNC_1, "expected RBRACK"));
                cur = 15;
            }
            15 => { // annots:exit
                event = Some(p.exit(RuleKind::Annots));
                cur = p.ret();
            }
            16 => { // annot:enter
                event = Some(p.enter(RuleKind::Annot));
                cur = 17;
            }
            17 => { // annot:expect:IDENT
                event = Some(p.expect(TokenKind::Ident, SYNC_2, "expected IDENT"));
                cur = 18;
            }
            18 => { // annot:exit
                event = Some(p.exit(RuleKind::Annot));
                cur = p.ret();
            }
            19 => { // alt_expr:enter
                event = Some(p.enter(RuleKind::AltExpr));
                p.push_ret(20);
                cur = 22;
            }
            20 => { // alt_expr:star
                match p.look(0).kind {
                    Some(TokenKind::Pipe) => {
                        p.push_ret(20);
                        event = Some(p.expect(TokenKind::Pipe, SYNC_3, "expected PIPE"));
                        cur = 22;
                    }
                    _ => {
                        cur = 21;
                    }
                }
            }
            21 => { // alt_expr:exit
                event = Some(p.exit(RuleKind::AltExpr));
                cur = p.ret();
            }
            22 => { // seq_expr:enter
                event = Some(p.enter(RuleKind::SeqExpr));
                match p.look(0).kind {
                    Some(TokenKind::Lparen) | Some(TokenKind::Dot) | Some(TokenKind::Bang) | Some(TokenKind::String) | Some(TokenKind::Char) | Some(TokenKind::Ident) => {
                        p.push_ret(23);
                        cur = 25;
                    }
                    _ => {
                        cur = 24;
                    }
                }
            }
            23 => { // seq_expr:star
                match p.look(0).kind {
                    Some(TokenKind::Lparen) | Some(TokenKind::Dot) | Some(TokenKind::Bang) | Some(TokenKind::String) | Some(TokenKind::Char) | Some(TokenKind::Ident) => {
                        p.push_ret(23);
                        p.push_ret(26);
                        match p.look(0).kind {
                            Some(TokenKind::Lparen) => {
                                event = Some(p.enter(RuleKind::Group));
                                cur = 28;
                            }
                            Some(TokenKind::Dot) => {
                                event = Some(p.enter(RuleKind::Atom));
                                cur = 32;
                            }
                            Some(TokenKind::Bang) => {
                                event = Some(p.enter(RuleKind::Atom));
                                cur = 32;
                            }
                            Some(TokenKind::String) => {
                                event = Some(p.enter(RuleKind::Atom));
                                cur = 32;
                            }
                            Some(TokenKind::Char) => {
                                event = Some(p.enter(RuleKind::Atom));
                                cur = 32;
                            }
                            Some(TokenKind::Ident) => {
                                event = Some(p.enter(RuleKind::Atom));
                                cur = 32;
                            }
                            _ => { event = Some(p.error_here("unexpected token")); p.recover_to(SYNC_3); cur = p.ret(); }
                        }
                    }
                    _ => {
                        cur = 24;
                    }
                }
            }
            24 => { // seq_expr:exit
                event = Some(p.exit(RuleKind::SeqExpr));
                cur = p.ret();
            }
            25 => { // seq_expr:star-body:call:_postfix_expr
                p.push_ret(26);
                match p.look(0).kind {
                    Some(TokenKind::Lparen) => {
                        event = Some(p.enter(RuleKind::Group));
                        cur = 28;
                    }
                    Some(TokenKind::Dot) => {
                        event = Some(p.enter(RuleKind::Atom));
                        cur = 32;
                    }
                    Some(TokenKind::Bang) => {
                        event = Some(p.enter(RuleKind::Atom));
                        cur = 32;
                    }
                    Some(TokenKind::String) => {
                        event = Some(p.enter(RuleKind::Atom));
                        cur = 32;
                    }
                    Some(TokenKind::Char) => {
                        event = Some(p.enter(RuleKind::Atom));
                        cur = 32;
                    }
                    Some(TokenKind::Ident) => {
                        event = Some(p.enter(RuleKind::Atom));
                        cur = 32;
                    }
                    _ => { event = Some(p.error_here("unexpected token")); p.recover_to(SYNC_3); cur = p.ret(); }
                }
            }
            26 => { // _postfix_expr:star
                match p.look(0).kind {
                    Some(TokenKind::Question) | Some(TokenKind::Star) | Some(TokenKind::Plus) => {
                        p.push_ret(26);
                        match p.look(0).kind {
                            Some(TokenKind::Question) => {
                                event = Some(p.expect(TokenKind::Question, SYNC_3, "expected QUESTION"));
                                cur = p.ret();
                            }
                            Some(TokenKind::Star) => {
                                event = Some(p.expect(TokenKind::Star, SYNC_3, "expected STAR"));
                                cur = p.ret();
                            }
                            Some(TokenKind::Plus) => {
                                event = Some(p.expect(TokenKind::Plus, SYNC_3, "expected PLUS"));
                                cur = p.ret();
                            }
                            _ => { event = Some(p.error_here("unexpected token")); p.recover_to(SYNC_3); cur = p.ret(); }
                        }
                    }
                    _ => {
                        cur = p.ret();
                    }
                }
            }
            27 => { // group:enter
                event = Some(p.enter(RuleKind::Group));
                cur = 28;
            }
            28 => { // group:expect:LPAREN
                event = Some(p.expect(TokenKind::Lparen, SYNC_3, "expected LPAREN"));
                p.push_ret(29);
                cur = 19;
            }
            29 => { // group:expect:RPAREN
                event = Some(p.expect(TokenKind::Rparen, SYNC_3, "expected RPAREN"));
                cur = 30;
            }
            30 => { // group:exit
                event = Some(p.exit(RuleKind::Group));
                cur = p.ret();
            }
            31 => { // atom:enter
                event = Some(p.enter(RuleKind::Atom));
                cur = 32;
            }
            32 => { // atom:dispatch
                match p.look(0).kind {
                    Some(TokenKind::Dot) => {
                        p.push_ret(33);
                        event = Some(p.enter(RuleKind::CharPrimary));
                        cur = 35;
                    }
                    Some(TokenKind::Bang) => {
                        p.push_ret(33);
                        event = Some(p.enter(RuleKind::NegClass));
                        cur = 40;
                    }
                    Some(TokenKind::String) => {
                        p.push_ret(33);
                        event = Some(p.expect(TokenKind::String, SYNC_3, "expected STRING"));
                        cur = p.ret();
                    }
                    Some(TokenKind::Char) => {
                        p.push_ret(33);
                        event = Some(p.enter(RuleKind::CharPrimary));
                        cur = 35;
                    }
                    Some(TokenKind::Ident) => {
                        p.push_ret(33);
                        event = Some(p.expect(TokenKind::Ident, SYNC_3, "expected IDENT"));
                        cur = p.ret();
                    }
                    _ => { cur = 33; event = Some(p.error_here("unexpected token")); p.recover_to(SYNC_3); }
                }
            }
            33 => { // atom:exit
                event = Some(p.exit(RuleKind::Atom));
                cur = p.ret();
            }
            34 => { // char_primary:enter
                event = Some(p.enter(RuleKind::CharPrimary));
                cur = 35;
            }
            35 => { // char_primary:dispatch
                match p.look(0).kind {
                    Some(TokenKind::Dot) => {
                        p.push_ret(36);
                        event = Some(p.expect(TokenKind::Dot, SYNC_3, "expected DOT"));
                        cur = p.ret();
                    }
                    Some(TokenKind::Char) => {
                        p.push_ret(36);
                        event = Some(p.expect(TokenKind::Char, SYNC_3, "expected CHAR"));
                        cur = 37;
                    }
                    _ => { cur = 36; event = Some(p.error_here("unexpected token")); p.recover_to(SYNC_3); }
                }
            }
            36 => { // char_primary:exit
                event = Some(p.exit(RuleKind::CharPrimary));
                cur = p.ret();
            }
            37 => { // char_primary:alt0:opt
                match p.look(0).kind {
                    Some(TokenKind::Dotdot) => {
                        event = Some(p.expect(TokenKind::Dotdot, SYNC_3, "expected DOTDOT"));
                        cur = 38;
                    }
                    _ => {
                        cur = p.ret();
                    }
                }
            }
            38 => { // char_primary:alt0:opt-body:expect:CHAR
                event = Some(p.expect(TokenKind::Char, SYNC_3, "expected CHAR"));
                cur = p.ret();
            }
            39 => { // neg_class:enter
                event = Some(p.enter(RuleKind::NegClass));
                cur = 40;
            }
            40 => { // neg_class:expect:BANG
                event = Some(p.expect(TokenKind::Bang, SYNC_3, "expected BANG"));
                cur = 41;
            }
            41 => { // neg_class:dispatch
                match p.look(0).kind {
                    Some(TokenKind::Lparen) => {
                        p.push_ret(42);
                        event = Some(p.expect(TokenKind::Lparen, SYNC_3, "expected LPAREN"));
                        p.push_ret(43);
                        cur = 34;
                    }
                    Some(TokenKind::Dot) => {
                        p.push_ret(42);
                        event = Some(p.enter(RuleKind::CharPrimary));
                        cur = 35;
                    }
                    Some(TokenKind::Char) => {
                        p.push_ret(42);
                        event = Some(p.enter(RuleKind::CharPrimary));
                        cur = 35;
                    }
                    _ => { cur = 42; event = Some(p.error_here("unexpected token")); p.recover_to(SYNC_3); }
                }
            }
            42 => { // neg_class:exit
                event = Some(p.exit(RuleKind::NegClass));
                cur = p.ret();
            }
            43 => { // neg_class:alt1:star
                match p.look(0).kind {
                    Some(TokenKind::Pipe) => {
                        p.push_ret(43);
                        event = Some(p.expect(TokenKind::Pipe, SYNC_3, "expected PIPE"));
                        cur = 34;
                    }
                    _ => {
                        cur = 44;
                    }
                }
            }
            44 => { // neg_class:alt1:expect:RPAREN
                event = Some(p.expect(TokenKind::Rparen, SYNC_3, "expected RPAREN"));
                cur = p.ret();
            }
            _ => unreachable!("unknown state"),
        }
        p.set_state(cur);
        event
    }
}



/// Parse the `file` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_file_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_FILE)
}

/// Parse the `file` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_file_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_FILE)
}

/// Parse the `decl` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_decl_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_DECL)
}

/// Parse the `decl` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_decl_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_DECL)
}

/// Parse the `annots` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_annots_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_ANNOTS)
}

/// Parse the `annots` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_annots_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_ANNOTS)
}

/// Parse the `annot` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_annot_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_ANNOT)
}

/// Parse the `annot` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_annot_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_ANNOT)
}

/// Parse the `alt_expr` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_alt_expr_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_ALT_EXPR)
}

/// Parse the `alt_expr` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_alt_expr_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_ALT_EXPR)
}

/// Parse the `seq_expr` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_seq_expr_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_SEQ_EXPR)
}

/// Parse the `seq_expr` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_seq_expr_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_SEQ_EXPR)
}

/// Parse the `group` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_group_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_GROUP)
}

/// Parse the `group` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_group_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_GROUP)
}

/// Parse the `atom` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_atom_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_ATOM)
}

/// Parse the `atom` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_atom_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_ATOM)
}

/// Parse the `char_primary` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_char_primary_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_CHAR_PRIMARY)
}

/// Parse the `char_primary` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_char_primary_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_CHAR_PRIMARY)
}

/// Parse the `neg_class` rule from an in-memory string.
///
/// Zero-copy: tokens borrow their text from `src`.
pub fn parse_neg_class_from_str<'a>(src: &'a str) -> Parser<'a, Scanner<'a, TokenKind, LexerDfa>> {
    Parser::new(Scanner::new(src), ENTRY_NEG_CLASS)
}

/// Parse the `neg_class` rule from any [`Read`] source.
///
/// Streaming: tokens own their text; memory use stays bounded regardless of
/// input size.
pub fn parse_neg_class_from_reader<R: Read>(reader: R) -> Parser<'static, StreamingLexer<R, TokenKind, LexerDfa>> {
    Parser::new(StreamingLexer::new(reader), ENTRY_NEG_CLASS)
}

