//! Transpile a `.parsuna` grammar into a tree-sitter `grammar.js`.
//!
//! The emitted grammar is a faithful shape-preserving translation: each
//! rule becomes a tree-sitter rule using `seq`/`choice`/`repeat`/etc.,
//! tokens become `token(...)` wrappers, and skip tokens become the
//! `extras` list. Useful for plugging a parsuna grammar into an editor
//! tool-chain that already speaks tree-sitter.

use std::fmt::Write;

use crate::analysis::AnalyzedGrammar;
use crate::grammar::ir::*;

/// Produce the contents of a tree-sitter `grammar.js` for `ag`.
pub fn emit(ag: &AnalyzedGrammar) -> String {
    let g = &ag.grammar;
    let mut out = String::new();
    writeln!(out, "// Generated by parsuna. Do not edit by hand.").unwrap();
    writeln!(out, "// Grammar: {}", g.name).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "module.exports = grammar({{").unwrap();
    writeln!(out, "  name: {},", js_string(&sanitize_name(&g.name))).unwrap();
    writeln!(out).unwrap();

    let skips: Vec<&TokenDef> = g
        .tokens
        .values()
        .filter(|t| t.skip && !t.is_fragment)
        .collect();
    write!(out, "  extras: $ => [").unwrap();
    for (i, t) in skips.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        write!(out, "$.{}", t.name).unwrap();
    }
    writeln!(out, "],").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "  rules: {{").unwrap();

    let mut need_blank = false;
    for r in g.rules.values().filter(|r| !r.is_fragment) {
        if need_blank {
            writeln!(out).unwrap();
        }
        writeln!(out, "    {}: $ => {},", r.name, render_expr(&r.body)).unwrap();
        need_blank = true;
    }
    for r in g.rules.values().filter(|r| r.is_fragment) {
        if need_blank {
            writeln!(out).unwrap();
        }
        writeln!(out, "    {}: $ => {},", r.name, render_expr(&r.body)).unwrap();
        need_blank = true;
    }
    for t in g.tokens.values().filter(|t| !t.is_fragment) {
        if need_blank {
            writeln!(out).unwrap();
        }
        writeln!(
            out,
            "    {}: $ => token({}),",
            t.name,
            render_token(&t.pattern, g)
        )
        .unwrap();
        need_blank = true;
    }

    writeln!(out, "  }},").unwrap();
    writeln!(out, "}});").unwrap();
    out
}

fn render_expr(e: &Expr) -> String {
    match e {
        Expr::Empty => "blank()".to_string(),
        Expr::Token(name) | Expr::Rule(name) => format!("$.{}", name),
        Expr::Seq(xs) => {
            let parts: Vec<String> = xs.iter().map(render_expr).collect();
            format!("seq({})", parts.join(", "))
        }
        Expr::Alt(xs) => {
            let parts: Vec<String> = xs.iter().map(render_expr).collect();
            format!("choice({})", parts.join(", "))
        }
        Expr::Opt(x) => format!("optional({})", render_expr(x)),
        Expr::Star(x) => format!("repeat({})", render_expr(x)),
        Expr::Plus(x) => format!("repeat1({})", render_expr(x)),
    }
}

fn render_token(p: &TokenPattern, g: &Grammar) -> String {
    match p {
        TokenPattern::Empty => "''".to_string(),
        TokenPattern::Literal(s) => js_string(s),
        TokenPattern::Class(cc) => render_class(cc),
        TokenPattern::NegLook { chars, strings } => render_neg_look(chars, strings),
        TokenPattern::Ref(name) => {

            let t = g.tokens.get(name).expect("reference validated upstream");
            render_token(&t.pattern, g)
        }
        TokenPattern::Seq(xs) => {
            let parts: Vec<String> = xs.iter().map(|x| render_token(x, g)).collect();
            format!("seq({})", parts.join(", "))
        }
        TokenPattern::Alt(xs) => {
            let parts: Vec<String> = xs.iter().map(|x| render_token(x, g)).collect();
            format!("choice({})", parts.join(", "))
        }
        TokenPattern::Opt(x) => format!("optional({})", render_token(x, g)),
        TokenPattern::Star(x) => format!("repeat({})", render_token(x, g)),
        TokenPattern::Plus(x) => format!("repeat1({})", render_token(x, g)),
    }
}

/// Render a NegLook pattern as a JS regex with negative lookaheads for
/// the multi-byte strings plus a negated char class for the chars. The
/// emitted regex matches a single byte; tree-sitter's regex engine
/// handles `(?!...)` natively, so this stays accurate for the typical
/// `!"L"*` block-comment idiom.
fn render_neg_look(chars: &CharClass, strings: &[String]) -> String {
    let mut out = String::from("/");
    for s in strings {
        out.push_str("(?!");
        out.push_str(&regex_escape_literal(s));
        out.push(')');
    }
    if chars.items.is_empty() {
        out.push('.');
    } else {
        out.push_str("[^");
        for item in &chars.items {
            match *item {
                ClassItem::Char(c) => out.push_str(&escape_class_char(c)),
                ClassItem::Range(lo, hi) => {
                    out.push_str(&escape_class_char(lo));
                    out.push('-');
                    out.push_str(&escape_class_char(hi));
                }
            }
        }
        out.push(']');
    }
    out.push('/');
    out
}

/// Escape a literal string for inclusion inside a JS regex (in `(?!...)`).
/// Same metacharacter set as a regex pattern body.
fn regex_escape_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' | '/' | '.' | '*' | '+' | '?' | '(' | ')' | '[' | ']' | '{' | '}' | '|'
            | '^' | '$' => {
                out.push('\\');
                out.push(c);
            }
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || (c as u32) == 0x7F => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

fn render_class(cc: &CharClass) -> String {
    let mut out = String::from("/[");
    if cc.negated {
        out.push('^');
    }
    for item in &cc.items {
        match *item {
            ClassItem::Char(c) => out.push_str(&escape_class_char(c)),
            ClassItem::Range(lo, hi) => {
                out.push_str(&escape_class_char(lo));
                out.push('-');
                out.push_str(&escape_class_char(hi));
            }
        }
    }
    out.push_str("]/");
    out
}

fn escape_class_char(cp: u32) -> String {
    let c = match char::from_u32(cp) {
        Some(c) => c,
        None => return format!("\\u{:04x}", cp),
    };
    match c {
        '\\' => "\\\\".into(),
        ']' => "\\]".into(),
        '/' => "\\/".into(),
        '^' => "\\^".into(),
        '-' => "\\-".into(),
        '\n' => "\\n".into(),
        '\r' => "\\r".into(),
        '\t' => "\\t".into(),
        _ if (cp < 0x20) || (cp == 0x7F) || (cp > 0x7E) => format!("\\u{:04x}", cp),
        c => c.to_string(),
    }
}

fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\'' => out.push_str("\\'"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}

fn sanitize_name(s: &str) -> String {
    let mut out = String::with_capacity(s.len().max(1));
    for c in s.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.chars().next().map_or(false, |c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analysis::analyze;
    use crate::grammar::parse_grammar;

    fn analyze_src(src: &str, name: &str) -> crate::AnalyzedGrammar {
        let mut g = parse_grammar(src).expect("parse");
        g.name = name.into();
        let outcome = analyze(g);
        assert!(!outcome.has_errors(), "{:?}", outcome.diagnostics);
        outcome.grammar.expect("grammar")
    }

    #[test]
    fn sanitize_name_handles_special_chars() {
        assert_eq!(sanitize_name("foo"), "foo");
        assert_eq!(sanitize_name("foo-bar"), "foo_bar");
        assert_eq!(sanitize_name(""), "_");
        assert_eq!(sanitize_name("123abc"), "_123abc");
        assert_eq!(sanitize_name("a.b.c"), "a_b_c");
    }

    #[test]
    fn js_string_quotes_and_escapes() {
        assert_eq!(js_string("hi"), "'hi'");
        assert_eq!(js_string("it's"), "'it\\'s'");
        assert_eq!(js_string("a\\b"), "'a\\\\b'");
        assert_eq!(js_string("\n"), "'\\n'");
    }

    #[test]
    fn render_class_emits_regex_literal() {
        let cc = CharClass {
            negated: false,
            items: vec![ClassItem::Range(b'a' as u32, b'z' as u32)],
        };
        assert_eq!(render_class(&cc), "/[a-z]/");

        let neg = CharClass {
            negated: true,
            items: vec![ClassItem::Char(b'a' as u32)],
        };
        assert_eq!(render_class(&neg), "/[^a]/");
    }

    #[test]
    fn render_expr_maps_each_node_to_tree_sitter_helper() {
        assert_eq!(render_expr(&Expr::Empty), "blank()");
        assert_eq!(render_expr(&Expr::Token("A".into())), "$.A");
        assert_eq!(render_expr(&Expr::Rule("main".into())), "$.main");
        assert_eq!(
            render_expr(&Expr::Opt(Box::new(Expr::Token("A".into())))),
            "optional($.A)"
        );
        assert_eq!(
            render_expr(&Expr::Star(Box::new(Expr::Token("A".into())))),
            "repeat($.A)"
        );
        assert_eq!(
            render_expr(&Expr::Plus(Box::new(Expr::Token("A".into())))),
            "repeat1($.A)"
        );
    }

    #[test]
    fn emit_includes_extras_for_skip_tokens_and_rule_names() {
        let ag = analyze_src(
            "WS = \" \"+ -> skip; T = \"t\"; main = T;",
            "demo",
        );
        let js = emit(&ag);
        assert!(js.contains("module.exports = grammar({"));
        assert!(js.contains("name: 'demo'"));
        assert!(js.contains("$.WS"), "extras list missing skip token: {}", js);
        assert!(js.contains("main: $ => $.T"));
        assert!(js.contains("T: $ => token('t')"));
    }

    #[test]
    fn emit_with_no_skip_tokens_has_empty_extras() {
        let ag = analyze_src("T = \"t\"; main = T;", "demo");
        let js = emit(&ag);
        assert!(js.contains("extras: $ => [],"), "{}", js);
    }
}
